### ISSUE TITLE
Need to have backups for RDPC-QA Kafka

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#100]
- Retention policy is being set to forever to facilitate better testing. 
- need to have a restorable backup the same as production incase we have to reindex/reinstantiate

**Comment by akachru-github** [comment]
Backups were deployed in DEV and QA before going ot production. @yalturmes will verify the details of the configuration in QA to ensure it matches our current prod config.

**Comment by yalturmes** [comment]
Confirming backups are in place for DEV/QA envs.
A quick summary on the kafka backup setup follows.

Kafka topics backed up: weblog, graphlog_info_debug, graphlog_error_warning
The list of kafka topics to backup is consistent in all envs.
Backup Schedule: daily
Location: Encrypted partition on management VM in RDPC DEV/QA env
Current retention policy: 14 days

@rosibaj Please let me know if any additional details/actions required for this ticket.

**Comment by rosibaj** [comment]
this looks good @yalturmes - i will close this ticket when @lepsalex confirms the change to the retention policy to be longer than 14 days!

**Comment by lepsalex** [comment]
@rosibaj @yalturmes confirmed that the default settings for QA have been updated to retain forever and all existing topics have configs set to retain forever. Forever in our case is defined as 20 years or 18gb per topic, whichever come first.
