### ISSUE TITLE
Data Issue: Some payloads still have `library_strategy`

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#109]
Example query, against prod api, `analysisId = 0023cf83-0b4f-417e-a3cf-830b4f717e03`

![image](https://user-images.githubusercontent.com/15824252/110407080-4566bf80-8051-11eb-87d2-2d74cc4231db.png)

```
query example_analysis_dates_for_dashboard{
  analyses(filter: { studyId: "PACA-CA", analysisId: "0023cf83-0b4f-417e-a3cf-830b4f717e03"}) {
    info {
      totalHits
    }
    content {
      analysisId
      analysisState
      analysisType
      updatedAt
      firstPublishedAt
      donors{
        specimens{
          tumourNormalDesignation
          samples{
            sampleId
          }
        }
      }
      experiment
      workflow{
        workflowName
      }
    }
    
  }
}
```

## Expected Behaviour
Many queries are expecting `experiemental_strategy` not `library_strategy`.  We need any payloads with this discrepancy to be updated.

**Comment by lindaxiang** [comment]
@rosibaj , these payloads were submitted to `intermediate-song` before we changed `library_strategy` to `experimental_strategy` in the schema. I think we can update the payloads to make all of them consistent.

**Comment by rosibaj** [comment]
@lindaxiang is this completed?

**Comment by lindaxiang** [comment]
@hknahal do you have any idea about this? 
This wont affect workflow running in RDPC, but does it affect Platform portal index?

**Comment by lindaxiang** [comment]
This has been addressed.
