### ISSUE TITLE
Investigate why 116 OCCAMS-GB donors are missing raw data - intermediate-song indexing issue

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#110]
409 donors were imported to intermediate-song, but 116 are missing raw reads. See https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/OCCAMS-GB/dashboard Investigate why these donors are missing raw data.

**Comment by hknahal** [comment]
Example using donorID DO234380 (submitter_donor_id: 9c1aa33d8cca6743039c73afa57991b46d5aae3796e1a1d2f7ad8480deb57bf7)

**Platform (QA)**: this donor shows that it has a missing normal raw read:

![missing_normal](https://user-images.githubusercontent.com/4992044/110842507-2cd6ef00-8275-11eb-8549-3e5675f05471.png)

**Intermediate-song**: this donor shows published payloads for both tumour and normal:

Normal: https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/9db59479-ac74-49ab-b594-79ac74c9ab98
Tumour: https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/1ce55181-090b-40f2-a551-81090b00f2fc

Next steps: Determine if this is the case for all 116 donors

**Comment by rosibaj** [comment]
reindexedL see the correct data for this donor now: 
![image](https://user-images.githubusercontent.com/15824252/110956736-edfa7500-8318-11eb-806c-520880d591d7.png)

**Comment by hknahal** [comment]
Re-indexing resolved most of the donor issues, but there are still 16 donors that are either missing a tumour/normal pair or both. Will investigate these further

![occams-gb_donors](https://user-images.githubusercontent.com/4992044/110994977-9a535000-8347-11eb-8922-4b6dbcb9b80c.jpg)

**Comment by hknahal** [comment]
Both normal and tumour payloads are published for these 9 donors, but they are showing as missing raw reads in Platform QA:

Donor ID | Normal Sample | Tumour Sample | Normal raw read | Tumour raw read | Normal published payload | Tumour published payload
-- | -- | -- | -- | -- | -- | --
DO234190 (92e63aeec5d5bfb17bdf90ebb4da303a859f9d663ef931cdd8fc89ec4d807919) | 1N | 1T | 0N | 1T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/9b111987-e7bc-48e1-9119-87e7bcb8e10e | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/ca7a96dc-b8d4-4e77-ba96-dcb8d49e773d
DO234348 (03037cb67402cd2882ddc346bbbcacf2574475a18fef75aa96b2e42fc90532d9) | 1N | 1T | 0N | 1T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/307c0f6a-e891-4a8c-bc0f-6ae8914a8ca3 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/2834cb7b-a56f-4cc9-b4cb-7ba56f0cc9a5
DO234322 (ab989ee5292af30a60ec0513ddc11cf15438035981075b0857e0d057d010c1fb) | 1N | 1T | 0N | 1T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/f65aca84-8836-4f40-9aca-848836cf4099 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/91f904f2-00c0-4f21-b904-f200c06f212e
DO234320 (c5470714db694a4a422ae88accca649e5a1c1101caedd86d2585edb7a1ab4d71) | 1N | 1T | 0N | 1T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/5395b3e8-443b-4378-95b3-e8443b937863 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/b1014f70-58dc-4248-814f-7058dc024833
DO234439 (64565a24a525ce7b4e1a958d9ab3410a8ba5975337aa731ef00bab7625a20bc1) | 1N | 1T | 0N | 1T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/c418411e-f539-475f-9841-1ef539175f24 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/89e57bee-0ca1-45f8-a57b-ee0ca1d5f8df
DO234402 (16ecc4c79c9ca8e731e9b0f2c6084c63a222890ad8d448c3658736dbc6eff424) | 1N | 1T | 0N | 1T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/78748f0e-6203-4244-b48f-0e6203824469 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/8a4e3b31-ae88-4097-8e3b-31ae88c09731
DO234299 (729ae39c61839b5c6bb6d8ec86b4e41bd4073cc8fac262bd32732144b1608045) | 1N | 1T | 0N | 0T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/f7bd60d1-2afa-4183-bd60-d12afaa18397 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/06e5dbaa-54d7-4240-a5db-aa54d77240b9
DO234207 (e28ac921f54f5818462d387b9c61bba5f72d25451cbc98f5e1804f741c1f1fe7) | 1N | 1T | 0N | 0T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/23dfff94-05cc-4ccf-9fff-9405ccbccfa0 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/52f6c8b8-970f-462a-b6c8-b8970fc62a18
DO234189 (1aa5c1b7dc0951139f6eee1476ac8edcba8ddee881eeec50897c81d13d42a4f6) | 1N | 1T | 0N | 0T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/c4a14dd1-72bb-40e0-a14d-d172bba0e009 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/cf370c5f-ea9c-47ec-b70c-5fea9c47ecdf

**Comment by hknahal** [comment]
The following donors have either a tumour or normal sample that needs to be transferred from Collab to ARGO (will prepare SONG payloads for these), or I need to find the file at EGA (once found, will transfer to Collab). Last column indicates action that will be taken:

Donor ID | Normal Sample | Tumour Sample | Normal raw read | Tumour raw read | Normal published payload | Tumour published payload | Action
-- | -- | -- | -- | -- | -- | -- | --
DO234206 (d9b28bce2ac1e8c6a6ea51c8363ea95bf522dea7876935acb451648cfe407994) | 1N | 1T | 0N | 0T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/f3f5cc9f-a963-4578-b5cc-9fa963e57847 | https://dcc.icgc.org/repositories/files/FI811606 | Transfer tumour from Collab→ ARGO
DO234201 (078773cc36a9ab58ece5c92e50368462dea52ded70f1b0da8c66e65066a3ce53) | 1N | 1T | 0N | 0T | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/56c16c86-dacd-4531-816c-86dacd8531fa | https://dcc.icgc.org/repositories/files/FI811611 | Transfer tumour from Collab→ ARGO
DO10842 (OCCAMS-PS-015) | 1N | 1T | 0N | 0T | https://dcc.icgc.org/repositories/files/FI811380 | https://dcc.icgc.org/repositories/files/FI811222 | Transfer normal from Collab→ARGO
DO10859 (OCCAMS-PS-003) | 1N | 1T | 0N | 0T | https://dcc.icgc.org/repositories/files/FI811357 | https://dcc.icgc.org/repositories/files/FI811253 | Transfer normal from Collab→ARGO
DO50319 (OCCAMS-AH-071) | 1N | 1T | 0N | 1T | https://dcc.icgc.org/repositories/files/FI349381 | https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/78d4b3c9-ae53-4fd2-94b3-c9ae53bfd220 | Transfer normal from Collab→ARGO
DO234180 (953dec19dc05015c97eb8cf35a0a4fabf53021d2fb65e7f4e770886db560e5f2) | 1N | 0T | 0N | 0T | https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22repoName%22:%7B%22is%22:%5B%22Collaboratory%20-%20Toronto%22%5D%7D,%22donorId%22:%7B%22is%22:%5B%22DO234180%22%5D%7D%7D%7D&files=%7B%22from%22:1,%22size%22:25%7D | Missing in Portal because EGA->Collab transfer failed for this file (https://github.com/icgc-argo/ega-file-transfer/issues/7) | Try to resolve EGA transfer issue.
DO234196 (69445a60bb3d928af26692ed3220960c8f142c5863af068392e92837bf271819) | 1N | 1T | 0N | 1T | Normal file was transferred from EGA to Collab: https://github.com/icgc-argo/ega-file-transfer/blob/master/ega_transfer_jobs/completed-jobs/job.EGAR00001192957.ESAD-UK.LP6005408-DNA_H02.EGAN00001198175/job.EGAR00001192957.ESAD-UK.LP6005408-DNA_H02.EGAN00001198175.json (Why isn't it showing in Portal??)| https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/026c0989-0e27-499b-ac09-890e27399b4c | Find out what happened to normal file in Collab (https://github.com/icgc-argo/ega-file-transfer/issues/11)

**Comment by rosibaj** [comment]
I investigated a donors on this list (DO234348) 

Query used against prod RDPC API (https://api.rdpc.cancercollaboratory.org/graphql): 
```
query example_analysis_dates_for_dashboard {
  analyses(filter: { donorId: "DO234348", analysisType:"sequencing_experiment", analysisState: PUBLISHED }, page: { size: 50, from: 0 }) {
    info {
      totalHits
    }
    content {
      analysisId
      analysisState
      analysisType
      updatedAt
      firstPublishedAt
      repositories{
        code
      }
      donors {
        specimens {
          tumourNormalDesignation
          samples {
            sampleId
          }
        }
      }
      experiment
      workflow {
        workflowName
      }
    }
  }
}
```
----
According to `Intermediate-song-prod`:
```
curl -X GET "https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/search/id?donorId=DO234348" -H "accept: */*"
```
There ARE two published `sequencing_experiment` analysis, both PUBLISHED on February18th around the same time: 
- 2834cb7b-a56f-4cc9-b4cb-7ba56f0cc9a5", (tumour) 
- 307c0f6a-e891-4a8c-bc0f-6ae8914a8ca3 (normal) 

According to the `RDPC-API-prod`, both of these donors have only 1 analysis of type `sequencing_experiment` published. 
- 2834cb7b-a56f-4cc9-b4cb-7ba56f0cc9a (tumour)  

- the second analysis is `SUPPRESSED` in RDPC APi. 
- 307c0f6a-e891-4a8c-bc0f-6ae8914a8ca3 (normla) 

![image](https://user-images.githubusercontent.com/15824252/111005649-33d72d80-8359-11eb-9d22-308bdb3fb89b.png)


Thus:
-  the dashboard is correctly reporting the information it is given
- The RDPC Prod API `is not` correctly reporting the state of at least some Analyses in `intermediate-song`. 

@andricDu or @lepsalex : 
1. Can we just reindec `intermediate-song-prod` to make sure it is accurate since we did have some configs that were not working in the past? 
2. Confirm in any way if we can trace this issue to anything specific? if not , then 1) should suffice to fix this issue I think.

**Comment by jaserud** [comment]
I can't reproduce this behaviour, SONG and maestro seem to be working correctly. I am able to suppress and republish an analysis in QA SONG and it is reflected in rdpc-gateway as expected. Intermediate-SONG is fundamentally the same (same versions just different score config) so I don't see why it wouldn't work their. 

From what I can see in the configs though, it looks like intermediate-song in prod had a recent network-policy update to allow it to talk to kafka (13 days ago). I think this analysis was just published before that and it didn't get indexed because the message never made it to kafka for maestro to pick up. The normal analysis `307c0f6a-e891-4a8c-bc0f-6ae8914a8ca3` was last updated Feb-18 which is well before the np updates, I suspect the same is true for any other such analysis.

**Comment by jaserud** [comment]
Verified my theory, after republished the analysis today in intermediate-song, it is showing up now as PUBLISHED (epoch time is Monday, 22 March 2021 14:33:05.639).

![image](https://user-images.githubusercontent.com/34698315/112007154-ccf50980-8afa-11eb-8d6a-a2b29ca7d85b.png)

**Comment by Buwujiu** [comment]
Verified that all these donors have seq exp PUBLISHED analysis in prod rdpc:
DO234190 
DO234348 
DO234322
DO234320 
DO234439 
DO234402 
DO234299 
DO234207 
DO234189

**Comment by Buwujiu** [comment]
> DO234189

Verified that all these donors have seq exp PUBLISHED analysis in prod rdpc:
DO234190
DO234348
DO234322
DO234320
DO234439
DO234402
DO234299
DO234207
DO234189

**Comment by rosibaj** [comment]
confirming prod platform dashboard reindex  for PACA-CA wtih @joneubank
