### ISSUE TITLE
payload migration of alignment worklow

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#113]
***When current batch of alignment finishes (~1 week from 4/6)

**Comment by lindaxiang** [comment]
Create separate tickets for updating payload generation tool for alignment:
https://github.com/icgc-argo/data-processing-utility-tools/issues/117
https://github.com/icgc-argo/data-processing-utility-tools/issues/116

**Comment by lindaxiang** [comment]
All aln payloads have been updated for the data release.
