### ISSUE TITLE
Finalize the SONG schemas

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#115]
1. variant_calling, variant_calling_supplement, qc_metrics
2. sequencing_alignment

**Comment by lindaxiang** [comment]
Document the specs on wiki: https://wiki.oicr.on.ca/display/icgcargotech/SONG+schema+adjustments+in+the+context+of+mapping+to+file+repo+facet
https://wiki.oicr.on.ca/display/icgcargotech/File+dataType+specification
