### ISSUE TITLE
Update WF versions and default params in Model Tee

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/workflow-roadmap#117]
New workflow versions (as a result of https://github.com/icgc-argo/workflow-roadmap/issues/120):

- dna-seq-processing-wfs: 1.7.0
- sanger-wgs-variant-calling: 2.1.0-9.3.0
- sanger-wxs-variant-calling: 3.1.6-3.3.0
- gatk-mutect2-variant-calling: 4.1.8.0-3.0

The new versions include support for retry on song/score failures. Two new params are added related to the retry:
- `max_retries` (number of retries before giving up, suggesting 5)
- `first_retry_wait_time` (wait time is in seconds, suggesting 10 seconds for `first_retry_wait_time`. Wait time of each subsequent retry doubles that of the previous one)

Task completion checklist:
- [x] optional (since the current `20.07.1` should work), update `nextflow` to `20.10.0` (or higher)
- [x] dna-seq-processing-wfs deployed and new params added 
- [x] sanger-wgs-variant-calling deployed and new params added
- [x] sanger-wxs-variant-calling and new params added
- [x] gatk-mutect2-variant-calling and new params added

**Comment by junjun-zhang** [comment]
newer versions of variant calling workflows available, ready to be deployed: https://github.com/icgc-argo/workflow-roadmap/issues/127

**Comment by lepsalex** [comment]
params updated, nextflow version is more involved so will leave it alone for now

**Comment by rosibaj** [comment]
@lepsalex is this last version upgrade still needed?

**Comment by lepsalex** [comment]
it's done in dev, needs QA release

**Comment by rosibaj** [comment]
@lepsalex is that something you think we can handle while you are on vacation, or should i wait one more sprint?
