### ISSUE TITLE
Payload migration of Sanger & Mutect2 calls

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#119]
These can be done now (4/6) since no Sanger & Mutect2 are running. Check with Rosi on specs

**Comment by lindaxiang** [comment]
Create separate tickets for updating payload generation tool:
https://github.com/icgc-argo/data-processing-utility-tools/issues/118

**Comment by lindaxiang** [comment]
Dynamic portion update in analysis use Endpoint: https://song.rdpc.cancercollaboratory.org/swagger-ui.html#/Analysis/updateAnalysisUsingPUT

File portion update in base schema use Endpoint: https://song.rdpc.cancercollaboratory.org/swagger-ui.html#/File/updateUsingPUT
