### ISSUE TITLE
🐛 Concurrent running jobs being kicked off by Model Tee?

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#121]
There are some jobs being kicked off by Model-Tee concurrently. For example:
![Screen Shot 2021-04-13 at 7 42 44 AM](https://user-images.githubusercontent.com/7522294/114591676-25ca4480-9c58-11eb-8e18-6a67319e2847.png)

Some investigation are needed for the potential issue.

**Comment by lindaxiang** [comment]
This happened to GATK-Mutect2 runs:

**studyId**|**donorId**|**sampleId**|**tumourNormalDesignation**|**experimental\_strategy**|**input\_analysisId**|**workflow\_name**|**latest\_complete\_time**|**runId**|**complete\_time**|**output\_analysis\_to\_suppress**|**reason**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
OCCAMS-GB|DO234444|SA594885|Tumour|WGS|4cd8f7fc-8a66-41bf-98f7-fc8a6601bf33|gatk-mutect2-variant-calling|2021-04-26 10:27|wes-62b60b5c3e674cb5b16880dca5cc4591|2021-04-26 9:00|['f617fc52-bef3-4b09-97fc-52bef3ab095c', '88c472ea-2c65-45f7-8472-ea2c65a5f752', '8033ba8c-4db0-4eb5-b3ba-8c4db01eb51c']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234444|SA594885|Tumour|WGS|4cd8f7fc-8a66-41bf-98f7-fc8a6601bf33|gatk-mutect2-variant-calling|2021-04-26 10:27|wes-acfd9259916140cfb87e5a1a4adc9565|2021-04-26 7:30|['0c39c518-b1cf-4ee8-b9c5-18b1cf6ee829', 'aa8ba459-2b73-473b-8ba4-592b73773bad', '57db63cc-9201-47ef-9b63-cc9201d7ef64']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234411|SA594610|Tumour|WGS|4dd45e81-3676-436d-945e-813676e36d97|gatk-mutect2-variant-calling|2021-04-26 7:15|wes-cea375f5903346f4aeab687e836fd4c2|2021-04-26 6:33|['1b3f68e1-d46f-4128-bf68-e1d46f712824', 'f3186758-3f7a-4b5c-9867-583f7a7b5cbe', 'c97e368d-da80-433a-be36-8dda80833aea']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234411|SA594610|Tumour|WGS|4dd45e81-3676-436d-945e-813676e36d97|gatk-mutect2-variant-calling|2021-04-26 7:15|wes-c201f33bf8784045b5628718247c3a36|2021-04-26 5:22|['f8c349a1-fab6-4cf1-8349-a1fab6bcf18d', 'ad9747d5-86dc-40f5-9747-d586dce0f5aa', 'f4dffc2e-7cda-4863-9ffc-2e7cdaf8637f']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234411|SA594610|Tumour|WGS|4dd45e81-3676-436d-945e-813676e36d97|gatk-mutect2-variant-calling|2021-04-26 7:15|wes-b42076143dfd4519966dc22d5033e9f9|2021-04-26 5:08|['9af86e54-f1e3-46ae-b86e-54f1e3c6ae4b', '7e9d938c-cb27-4fa7-9d93-8ccb27afa7e3', '0ddd3ba8-d9c1-464d-9d3b-a8d9c1664d6e']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234411|SA594610|Tumour|WGS|4dd45e81-3676-436d-945e-813676e36d97|gatk-mutect2-variant-calling|2021-04-26 7:15|wes-0926dad5a1764fa6bbac012e8ef1c9bd|2021-04-26 6:54|['70648d61-baa6-4174-a48d-61baa6517440', '4985448f-798c-4795-8544-8f798c37950d', '2945cf39-ddeb-4b7c-85cf-39ddebdb7ca0']|duplicated\_run\_output\_analysis
OCCAMS-GB|DO234411|SA594610|Tumour|WGS|4dd45e81-3676-436d-945e-813676e36d97|gatk-mutect2-variant-calling|2021-04-26 7:15|wes-77eceeecbe5549fe9da4af3683a64d72|2021-04-26 6:46|['0c25f242-c2c9-4f4f-a5f2-42c2c9df4fc2', '90ffba82-f7ef-4fe7-bfba-82f7ef5fe717', '703998ef-1097-4a10-b998-ef1097ea1013']|duplicated\_run\_output\_analysis

**Comment by lindaxiang** [comment]
@rosibaj @lepsalex
I will need to suppress the duplicated analysis listed in the above table. Will that impact the investigation of Model Tee kicking off duplicated runs?

**Comment by lepsalex** [comment]
no it will not @lindaxiang, you can go ahead

**Comment by lindaxiang** [comment]
There is one job been kicked off for 3 times again.

**studyId**|**donorId**|**sampleId**|**tumourNormalDesignation**|**experimental\_strategy**|**input\_analysisId**|**workflow\_name**|**latest\_complete\_time**|**runId**|**complete\_time**|**output\_analysis\_to\_suppress**|**reason**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
APGI-AU|DO34392|SA410646|Normal|WXS|ec030bdb-16a7-41ba-830b-db16a7b1baf0|dna-seq-processing-wfs|2021-06-11 19:45|wes-2c1af18cc20342d0993a80ed3d05eb3a|2021-06-11 19:22|['622d89ad-3637-451f-ad89-ad3637f51fe8', 'ca132c14-2b44-4a6e-932c-142b446a6e2f']|duplicated\_run\_output\_analysis
APGI-AU|DO34392|SA410646|Normal|WXS|ec030bdb-16a7-41ba-830b-db16a7b1baf0|dna-seq-processing-wfs|2021-06-11 19:45|wes-fc05fec50f814e16bd39dc9416a33472|2021-06-11 19:26|['afe9f33c-beca-41ba-a9f3-3cbecae1baad', 'fb6299a7-053e-49eb-a299-a7053ef9eb74']|duplicated\_run\_output\_analysis

**Comment by andricDu** [comment]
Closing, no longer relevant. Larger scope to be handled by automation.
