### ISSUE TITLE
Create a script to generate summary and report issuses related to RDPC SONG analysis objects

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#122]
As it has been observed often workflow runs could be duplicated resulting in duplicated SONG analysis objects. If the duplicates are not identified, it can cause cascaded downstream problems when feed the analysis to launch subsequent workflows.

A script can be run periodically (eg nightly), to get a summary of all existing SONG analysis objects, identify duplications and what analysis (workflow runs) remain to be launched.

- [ ] wiki page to document rules how many and what song analysis objects are expected per donor
- [ ] script to perform the check of above rules and report instances

**Comment by junjun-zhang** [comment]
Spec wiki: https://wiki.oicr.on.ca/display/icgcargotech/Integrity+Validation+of+ICGC+ARGO+SONG+Analysis+Objects
