### ISSUE TITLE
Update WF versions in production

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/workflow-roadmap#127]
Update workflow to latest versions in prod.

Task completion checklist:
- [x] sanger-wgs-variant-calling updated to 2.1.0-9.5.0
- [x] sanger-wxs-variant-calling updated to 3.1.6-3.5.0
- [x] gatk-mutect2-variant-calling updated to 4.1.8.0-5.0

**Comment by lepsalex** [comment]
done
