### ISSUE TITLE
RNA-Seq alignment workflows

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#129]
https://docs.google.com/document/d/1nJaY-h-knpGmmj5u54DzmtDiRZCPq4PsCwiRTyG3eeA/edit#heading=h.mda8iyj4pxc3

**Comment by junjun-zhang** [comment]
just to summarize what we discussed during today's bioinfo planning meeting about the RNA-Seq alignment workflow:
1. the production workflow (similar to other current ARGO workflows) contains four major parts: 1) song/score download; 2) core RNA-Seq alignment; 3) song payload generation for aligned RNA-Seq results; 4) song/score upload
2. production workflow will be hosted under this github org: https://github.com/icgc-argo-workflows that will incorporate all of the above four parts
3. all parts can be independently developed using WFPM
4. song/score download and upload have already been developed and used in other production workflows, expected to be directly importable into RNA-Seq production workflow
5. payload generation tool needs to be developed after SONG schema is finalized and released
6. the core RNA-Seq alignment portion is current being developed by the RNA-Seq group at: https://github.com/icgc-argo-rna-wg/rna-seq-workflows

pinging @akahles

**Comment by akachru-github** [comment]
Next step: 
- Create test data sets for DEV and QA environments, create reference data files and stage in the environments.

**Comment by b-f-chan** [comment]
@lindaxiang was testing in production but got access token denied error, but worked in QA - Need to revisit and re-test, if still happens reach out to Dev for support

**Comment by b-f-chan** [comment]
QA tickets have already been done and workflow already releases.  We haven't run the workflow in production jobs yet however.  We don't close this until a production run is done for ticket #271.
