### ISSUE TITLE
RNA-Seq customized SONG DYNAMIC schema

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#130]
This is for both input and output data.

**Comment by akachru-github** [comment]
RNA schema is mostly the same as DNA schema, so it is worth thining about potentially having a single conditional schema describing both rather than two independent ones that would be maintained separately.

**Comment by akachru-github** [comment]
Suggestion: 
- Can we share some of the dynamic schema portion of the Song schemas? This may reduce headaches in the future. This is not explicitly a software development change. It will be a change to how we approach designing the dynamic schemas.

**Comment by akachru-github** [comment]
In the interest of keeping the RNA Seq moving forward, we will go ahead and create a new schema for RNA Seq (even though it dups 80-90% of the original alignment schema). We will create a separate ticket for long term goals on how to take advantage of this overlap in the future.

**Comment by lindaxiang** [comment]
PR: https://github.com/icgc-argo/argo-metadata-schemas/pull/61

**Comment by lindaxiang** [comment]
SONG adjustments: https://wiki.oicr.on.ca/display/icgcargotech/SONG+schema+adjustments+in+the+context+of+RNA-Seq+pipelines

**Comment by b-f-chan** [comment]
Tested in QA, waiting for real data to go to prod, then can close
