### ISSUE TITLE
Deploy alignment workflow version 1.8.0 in prod

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/workflow-roadmap#137]
New version of alignment workflow is available: https://github.com/icgc-argo/dna-seq-processing-wfs/releases/tag/1.8.0, with new features:
* pass on `info` field in input metadata
* new `data_subtypes` under file.info
* updated `dataType` under file

**Comment by rosibaj** [comment]
@lindaxiang has this update been completed?

**Comment by lindaxiang** [comment]
Yes. @rosibaj the version `1.8.0` is currently deployed in Prod.
