### ISSUE TITLE
Resume Mutect2 jobs and Sanger jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#142]
- [x] The following mutect2 jobs failed and need to resume.

**No.**|**run\_id**|**session\_id**
:-----:|:-----:|:-----:
1|wes-8d4ae26886e9443f989a84f934c42f99|f3da6398-acd8-49fe-a956-8abe81a05b86
2|wes-600c9069ba1b4083a8ff3a80cf1db6d0|85ea8c63-cba1-49f8-99c0-16aa0e11f2ce
3|wes-1fe56ac8879642b2a967966413456149|ec4aa3f6-baf3-439b-a2ea-b74ef3926e69
4|wes-affe227c8cfb42ae8245b13d11c8f912|398b9d23-3ef1-46de-a4f7-61baa9b42f30
5|wes-cc23f3f201e445aa865a6f596bfbb112|57fd8c6b-1fd5-49a3-bc99-8cd90c9b2a10
6|wes-a8d06d45ffca43eeb43c14d4b8c6e600|b349b53c-861c-4146-af40-3ae958dcea2f

- [x] The following Sanger jobs failed and need to resume with adjusted `cpu/pindelcpu` params

**No.**|**run\_id**|**session\_id**
:-----:|:-----:|:-----:
1|wes-6d85bb355f14427d981c2aaec7f52273|dde8038d-0444-464d-8fdb-5f0f5be77f07
2|wes-d9760ab286744b03ac0b9c56d5311ba3|ccec3a7b-8bc7-4eca-a07b-1706d7d85c7f
3|wes-236a49526ccf4d8190a0d3373b72ca9d|28e7ac46-a8bd-498f-83b6-35adc6c998d9
4|wes-f0183b59b3504479ab402ab1e560d0ea|1bf3424d-cd9c-4242-8667-26f114324925
5|wes-4a9491310ad740ed9321e79090a1e2bd|08dc89ff-baca-4011-8383-2e491ec92f76
6|wes-b344c10dba024738ab302ed19a15d116|be2498f0-f715-4751-ba80-e708775bd5c4
7|wes-6cd97708bc704675857de46b899c55a2|526f1f1e-3352-4004-98f2-e01101ea20c5
8|wes-df067019868945219278ac93d94e6556|a2e6936f-7555-4284-8cdc-866cd70d59a2
9|wes-1c9a9dc8026e4fa5a1f207a4853c251c|825e09a3-9de2-49bb-9c8f-6157656b832c
10|wes-c22a2b3e7b9a45e08c38f4041b79bfcf|ade43bc7-0702-42a1-9e0a-7ab01dc2d79f
11|wes-b086ff3d44f24312a554eafa220f5719|e1ecf682-de8d-425f-a2ca-9c478a762941
12|wes-4bf18b0fa1ad4a2d8120f16fc1b57b46|8e3e67fa-8099-4921-9d69-9aad7516a5b5
13|wes-f03565eb05e54c7395a4f7cb5acf7c03|7188bfe5-1a52-413f-9020-2c8fdf0e5e8e
14|wes-c78ee619107941efb5c39479a69f46a5|8b2ff57e-542b-450a-996d-2226b2e6bdaf

**Comment by lepsalex** [comment]
all jobs resumed
