### ISSUE TITLE
Update WF versions in Production

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#143]
Update workflow to latest versions in prod.

Task completion checklist:
- [x] sanger-wgs-variant-calling updated to 2.1.0-9.6.0
- [x] sanger-wxs-variant-calling updated to 3.1.6-3.6.0
- [x] gatk-mutect2-variant-calling updated to 4.1.8.0-6.0

**Comment by lepsalex** [comment]
done
