### ISSUE TITLE
Rerun a previous complete job but generated corrupted file object

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#152]
Re-run the alignment job with following information

**submitter\_donor\_id**|**submitter\_sample\_id**|**tumour\_normal\_designation**|**sequencing\_strategy**|**donor\_id**|**sample\_id**|**study\_id**|**analysis\_id**|**work\_dir**|**run\_id**|**session\_id**|**state**|**start**|**end**|**duration**|**note**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
2e84eea0e07ed72ce78dbc3111fb143778370d58de40f30a66e36a37cc314191|LP6005935-DNA\_G01|tumour|WGS|DO234233|SA547432|OCCAMS-GB|170cdada-8ce8-4620-8cda-da8ce8d620dc|nfs-3-c2|wes-bf741e23d17c42f8afd7bc5280385c2a|1ee98abf-1a2f-4248-a8b8-b61fbcf917f7|COMPLETE|2021-03-31 12:22:02.330000-04:00|2021-04-01 15:05:43.160000-04:00|26.73|broken object. to be re-run

**Comment by rosibaj** [comment]
on hold until collab is back up and running

**Comment by lepsalex** [comment]
new run initiated: https://wes.rdpc.cancercollaboratory.org/runs/wes-9eaeda80e1ca4359bc03b7dda3cf7fec
