### ISSUE TITLE
New batch of alignment jobs from `APGI-AU`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#155]
Totally 184 jobs = 96 WGS + 88 WXS

[APGI-AU.wgs.txt](https://github.com/icgc-argo/workflow-roadmap/files/6599502/APGI-AU.wgs.txt)
[APGI-AU.wxs.txt](https://github.com/icgc-argo/workflow-roadmap/files/6599503/APGI-AU.wxs.txt)

**Comment by lindaxiang** [comment]
Use alignment workflow dna-seq-processing-wfs version of `1.8.0` in prod.

**Comment by lepsalex** [comment]
jobs kicked off with model-tee after maintenance
