### ISSUE TITLE
Workflow Run Failure - OCCAMS-GB ``donorSubmitterId` and `specimenSubmitterId` was not found

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#156]
## Detailed Description
1. error: `specimenSubmitterId 'OC-AH-093-S-T2' was not found`
sessionId: 16804f36-1159-45db-a4ed-bc657e0bb475
runId: wes-741b21b429284cb8b5e5bb353a99996d
    
Detail error report: 
`Error executing process > 'DnaAln:upAln:songSub (OCCAMS-GB)'\n\nCaused by:\n  Process `DnaAln:upAln:songSub (OCCAMS-GB)` terminated with an error exit status (1)\n\nCommand executed:\n\n  export CLIENT_SERVER_URL=https://song.rdpc.cancercollaboratory.org\n  export CLIENT_STUDY_ID=OCCAMS-GB\n  export CLIENT_ACCESS_TOKEN=`cat /tmp/rdpc_secret/secret`\n  \n  set -euxo pipefail\n  sing submit -f d2823b2d-36b2-4b59-8c41-1c510d93a82e.dna_alignment.payload.json | jq -er .analysisId | tr -d '\\n'\n\nCommand exit status:\n  1\n\nCommand output:\n  (empty)\n\nCommand error:\n  + sing submit -f d2823b2d-36b2-4b59-8c41-1c510d93a82e.dna_alignment.payload.json\n  + jq -er .analysisId\n  + tr -d '\\n'\n  SONG_SERVER_ERROR[id.not.found @ 1619036233750]: [SpecimenService::id.not.found] - The specimenId for studyId 'OCCAMS-GB' and specimenSubmitterId 'OC-AH-093-S-T2' was not found\n\nWork dir:\n  /nfs-1-c2/work/4f/aa0b2c143f6fcabab5a2eb39a84588\n\nTip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run``

2. error `donorSubmitterId 'OCCAMS-AH-100' was not found`
sessionId: da066151-0c1b-4079-a9d8-6f2c38fb6d1e
runId: wes-dafb09531f0846b7b875bd88da19aa68

Details error report:
`Error executing process > 'DnaAln:upAln:songSub (OCCAMS-GB)'\n\nCaused by:\n  Process `DnaAln:upAln:songSub (OCCAMS-GB)` terminated with an error exit status (1)\n\nCommand executed:\n\n  export CLIENT_SERVER_URL=https://song.rdpc.cancercollaboratory.org\n  export CLIENT_STUDY_ID=OCCAMS-GB\n  export CLIENT_ACCESS_TOKEN=`cat /tmp/rdpc_secret/secret`\n  \n  set -euxo pipefail\n  sing submit -f 1e39979e-8843-4488-b6c3-11a7218c62c3.dna_alignment.payload.json | jq -er .analysisId | tr -d '\\n'\n\nCommand exit status:\n  1\n\nCommand output:\n  (empty)\n\nCommand error:\n  + sing submit -f 1e39979e-8843-4488-b6c3-11a7218c62c3.dna_alignment.payload.json\n  + jq -er .analysisId\n  + tr -d '\\n'\n  SONG_SERVER_ERROR[id.not.found @ 1619015216559]: [DonorService::id.not.found] - The donorId for studyId 'OCCAMS-GB' and donorSubmitterId 'OCCAMS-AH-100' was not found\n\nWork dir:\n  /nfs-1-c4/work/d2/4d7b362e9ed32a8005257657fe8a62\n\nTip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh``

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by lindaxiang** [comment]
Some investigation for ID changes:
- Clinical DB has already been updated
- intermediate song analysis have been update
- The analysis had a `completed` run before with incorrect IDs
- The re-run job did NOT re-run from the very beginning but resume using the cached analysis which is out of date. 

Need to completely re-run the jobs to pick up modified IDs from updated intermediate song analysis.

**Comment by rosibaj** [comment]
@lindaxiang this is a job from april that was resumed; i dont think this ticket is valid.

**Comment by lindaxiang** [comment]
@rosibaj you are right. re-run these two jobs should solve the problem.

**Comment by rosibaj** [comment]
@lindaxiang i am closing this ticekt as INVALID as tracking these jobs for resolution are not needed.

**Comment by rosibaj** [comment]
Note: these issues for these two jobs will be handles in scope of: https://github.com/icgc-argo/workflow-roadmap/issues/160
