### ISSUE TITLE
RDPC DEV / QA: Update Jenkins pipeline for each RDPC Service

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#16]
We have a new jenkins, and all of the services need updates charts for deployment
- use new task 
- delete multiple branch pipelines from old server and created in new one

--------

- [x] workflow management
- [x] workflow search
- [x] workflow-relay
- [x] workflow-ui
- [x] workflow-docs
- [x] workflow-gateway
- [x] rdpc-status

**Comment by andricDu** [comment]
Workflow search has been migrated.

**Comment by yalturmes** [comment]
Following jobs copied to jenkins.rdpc-dev.cancercollaboratory.org:
- workflow-management
- workflow-relay
- workflow-ui
- workflow-docs
- workflow-gateway
- rdpc-status

Deploy (CD) step is not implemented on the copied jobs yet.

**Comment by yalturmes** [comment]
All copied jobs have been disabled for platform Jenkins instance (jenkins.qa.cancercollaboratory.org/) to avoid multiple release/tagging/deploy on a single SCM event.

**Comment by yalturmes** [comment]
All work on following pipelines is done - PRs merged into `develop` branch.
- workflow management
- workflow-ui
- workflow-docs
- workflow-gateway
- rdpc-status

The only one remaining is `workflow-relay` due to a more complex CD scenario. Already engaged @andricDu for assistance.

**Comment by yalturmes** [comment]
All work on the remaining pipeline `workflow-relay` completed. PR to merge into the `develop` branch created.
