### ISSUE TITLE
Finish processing all ICGC-25k data (Alignment, Sanger, Mutect2) 

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#162]
We are hoping to process all the left ICGC-25k jobs other than OCCAMS-GB donors of IDs renaming issue, including:
- Alignment ( 7 resume WGS + 1 resume WXS) 
- Sanger WGS( 5 new jobs)
- Sanger WXS ( 1 new job) 
- Mutect2 ( 6 new jobs + 2 resume jobs)

All jobs have been added/noted in Model-T worksheet.

**Comment by lepsalex** [comment]
all jobs have been initiated

**Comment by lindaxiang** [comment]
@lepsalex There are still some variant calling jobs to run:
- 6 Sanger wgs
- 6 GATK mutect2 
Both have been added to the Model-T worksheet.

**Comment by lepsalex** [comment]
all 12 jobs have been initiated

**Comment by lindaxiang** [comment]
@lepsalex There are 6 more variant calling jobs to run from OCCAMS-GB:
- 3 Sanger jobs
- 3 Mutect2

**Comment by lepsalex** [comment]
6 remaining jobs have all been kicked off

**Comment by rosibaj** [comment]
@lindaxiang the last set of jobs are in process of being added right?

**Comment by lindaxiang** [comment]
@rosibaj yes. I am waiting for the intermediate-song to be reindexed into graphQL

**Comment by akachru-github** [comment]
We have a failed deployment of intermediate song in production right now. This needs to be investigated before we can runt these jobs.

**Comment by lindaxiang** [comment]
@lepsalex There are 4 WGS + 7 WXS alignment jobs adding to the worksheet.

**Comment by lepsalex** [comment]
all jobs have been kicked off

**Comment by lindaxiang** [comment]
@lepsalex all the above 11 alns have completed. Downstream variant calling jobs are added to the worksheet:
- 3 sanger-wgs
- 7 sanger-wxs
- 10 gatk-mutect2

**Comment by lepsalex** [comment]
all jobs have been scheduled

**Comment by lepsalex** [comment]
@lindaxiang are we expecting any more jobs or can we close this ticket?

**Comment by lindaxiang** [comment]
@lepsalex I think we can close this ticket for now.
