### ISSUE TITLE
Batch Schedule: MUTO-INTL 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#168]
MUTO-INTL has completed the first external data upload for 10 donors - analysis id attached in file below: 

[MUITO-INTL_first_10_dionors_sequencing_reads.txt](https://github.com/icgc-argo/workflow-roadmap/files/6787464/MUITO-INTL_first_10_dionors_sequencing_reads.txt)

**Comment by lindaxiang** [comment]
@lepsalex this batch of 20 aln jobs have been added to the worksheet.

**Comment by rosibaj** [comment]
Aligns have been kicked off.

**Comment by lindaxiang** [comment]
@lepsalex Aligns have complete.
10 Sanger + 10 Mutect2 have been added to the worksheet.

**Comment by lepsalex** [comment]
all MUTO-INTL Sanger/Mutect2 jobs have been kicked off

**Comment by lindaxiang** [comment]
all MUTO-INTL Aln/Sanger/Mutect2 jobs have completed.
