### ISSUE TITLE
Finish all OCCAMS-GB jobs related to IDs renaming issue (alignment, sanger, gatk-mutect2)

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#169]
Currently there are the following jobs that are ready to be initiated:

- 6 Alignment jobs need to re-run
- 5 Sanger WGS
- 5 GATK-Mutect2

All jobs have been added/labelled in the Model-Tee worksheet.

**Comment by lindaxiang** [comment]
More Sanger WGS and GATK-mutect2 jobs:
- 22 Sanger WGS
- 22 Gatk-mutect2 
All jobs have been added to the Model-Tee worksheet.

**Comment by lepsalex** [comment]
model-tee running
