### ISSUE TITLE
Generate documentation on logistics on running the open access filtering workflow

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#182]
- Does this need to be monitored as it is running?
- What will the process be for presenting the results once they are available?
- exit criteria: wiki page. 

wiki: https://wiki.oicr.on.ca/display/icgcargotech/ARGO+Open+Access+Filtering+Workflow

**Comment by lindaxiang** [comment]
Wiki: https://wiki.oicr.on.ca/display/icgcargotech/ARGO+Open+Access+Filtering+Workflow
