### ISSUE TITLE
ICGC25K Azure transfer - failed jobs

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#186]
Here are the status for all failed jobs:

**Project**|**# of failed**|**Reason**|**Action**|**Issue**
:-----:|:-----:|:-----:|:-----:|:-----:
BOCA-UK|4| | | 
BRCA-UK|26| | | 
CLLE-ES|10| | | 
CMDI-UK|7| | | 
ESAD-UK|59| | | 
LAML-KR|10| | | 
LICA-FR|36| | | 
LINC-JP|16| | | 
LIRI-JP|4| | | 
MELA-AU|18| | | 
OV-AU|4| | | 
PACA-AU|18| | | 
PACA-CA|92| | | 
PRAD-CA|1| | | 
PRAD-UK|2| | |

**Comment by junjun-zhang** [comment]
These jobs failed most likely due to size being greater than 200GB before the fix of score upload. After verified this is the case, jobs can be moved back to the `backlog` folder to resume

**Comment by lindaxiang** [comment]
Has dependencies of:
- https://github.com/icgc-argo/icgc-25k-azure-transfer/issues/36
- https://github.com/icgc-argo/icgc-25k-azure-transfer/issues/31

**Comment by rosibaj** [comment]
Dependencies of: 
- https://github.com/icgc-argo/icgc-25k-azure-transfer-job-tracking/issues/8

**Comment by lindaxiang** [comment]
Updated status on Sep.01, 2021

**Project**|**# of backlog**|**# of failed**|**Status**|**Todo**|**Issue**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
CMDI-UK|0|116|  Some mismatch song IDs found | | https://github.com/icgc-argo/workflow-roadmap/issues/193|
LINC-JP|0|4| Some jobs report Data file objectId mismatch |   | https://github.com/icgc-argo/workflow-roadmap/issues/194|
LIRI-JP|0 |44| Some mismatch song IDs found | | https://github.com/icgc-argo/workflow-roadmap/issues/195
PACA-AU| 0|156|   | | https://github.com/icgc-argo/workflow-roadmap/issues/187|
PACA-CA|0|10| |  | https://github.com/icgc-argo/workflow-roadmap/issues/192|
PRAD-UK|0| 72| Some mismatch song IDs found | | https://github.com/icgc-argo/workflow-roadmap/issues/190 |

**Comment by akachru-github** [comment]
All failed jobs have been cleared.
