### ISSUE TITLE
Workflow Raccoon

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-roadmap#189]
Scaffold new project based on following spec:

https://wiki.oicr.on.ca/display/icgcargotech/Workflow+Garbage+Collection

Exit criterial:

- [x] github repo
- [x] docker build
- [x] jenkinsfile
- [x] inclusion of dependencies for K8s client
- [x] Scaffold of OpenAPI spec (not implemented returns are okay)

**Comment by rosibaj** [comment]
- still trying to deploy to develop 
- was blocked by the upgrade
- waiting to make PR's

**Comment by rosibaj** [comment]
@andricDu to make the docker image public on github

**Comment by jaserud** [comment]
Raccoon repo has been initialized and the docker image is publicly available. Closing as there is an implementation ticket to track that progress their.
