### ISSUE TITLE
ICGC25k Azure transfer - PRAD-UK IDs issues

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#190]
Many PRAD-UK project jobs failed because of SONG IDs mismatch issues. 

Here are some examples and context info:
Example1:
```
The source song analysis: https://song.cancercollaboratory.org/studies/PRAD-UK/analysis/dd218a70-86d3-4c31-834b-a2590da73f6a
and the azure song analysis:  https://song.azure.icgc.overture.bio/studies/PRAD-UK/analysis/dd218a70-86d3-4c31-834b-a2590da73f6a
- why the same sampleSubmitterId (0006_CRUK_PC_0006_T4_DNA) has mapped to different sampleId
```
```
https://song.azure.icgc.overture.bio/studies/PRAD-UK/all
- First search DO48577
- Then search for  `0006_CRUK_PC_0006_T4_DNA`
- You will find It maps to 2 different sampleId
```

Example-2
```
collab song: https://song.cancercollaboratory.org/studies/PRAD-UK/analysis/eb7050c6-de21-4716-931e-67744caac889
azure song: https://song.azure.icgc.overture.bio/studies/PRAD-UK/analysis/eb7050c6-de21-4716-931e-67744caac889
- The Ids mappings are also out of sync.
- New song server at azure did not create the same number of samples (not sure if this is related to IDs mismatch issue)
```

```
https://song.azure.icgc.overture.bio/studies/PRAD-UK/all
- First search DO51962
- Then search for  A34C-0022_CRUK_PC_0022_M2_DNA
- You will find It maps to 2 different sampleId
```

**Comment by andricDu** [comment]
@lindaxiang In your first example, the submitter specimen Ids are different

**Comment by lindaxiang** [comment]
> @lindaxiang In your first example, the submitter specimen Ids are different

@andricDu Yes. The `specimenSubmitterId` are different, but `sampleSubmitterId` are the same. The metadata itself looks not correct to me.
However, what are the rules for SONG system ID generation and mapping? Will the difference between `specimenSubmitterId` affect the mapping of `sampleId`?

**Comment by andricDu** [comment]
before we continue, can we confirm that the song submission to azure was incorrect? If the submitter Id is wrong, I'm not 100% sure what the expected behaviour is.

**Comment by lindaxiang** [comment]
Error messages of failed jobs
[PRAD-UK_job_state.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092142/PRAD-UK_job_state.txt)

**Comment by lindaxiang** [comment]
72 failed jobs in TOTAL
- 45 failed with error message: 
`Payload upload failed at save with status code: 409. Response: {"errorId":"sample.already.exists","httpStatusCode":409`

- 13 failed with error message:
`Mismatch(es) of system ID identified.`

- 10 failed with error message:
`Payload upload failed at save with status code: 500.`

- 4 failed with error message:`KeyError`
