### ISSUE TITLE
ICGC25k Azure transfer - correct `specimen_type` for `PACA-AU` RNA-Seq Tumour samples at Collab and AWS Song

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#197]
Details are describe in issue: https://github.com/icgc-argo/workflow-roadmap/issues/187

Here is the all 156 affected RNA-Seq analysis which contain incorrect `speciment_type`=`Primary tumour`.
[PACA-AU.incorrect_speciment_type.analysis.txt](https://github.com/icgc-argo/workflow-roadmap/files/7092528/PACA-AU.incorrect_speciment_type.analysis.txt)

Both Collab and AWS Song are confirmed to contain the incorrect `speciment_type` for the above analysis. E.g.,
https://virginia.song.icgc.org/studies/PACA-AU/analysis/009bebd8-3cf9-45a8-8546-1a09a8bf91a1
https://song.cancercollaboratory.org/studies/PACA-AU/analysis/009bebd8-3cf9-45a8-8546-1a09a8bf91a1

As legacy song server does not support endpoint to modify the information at `sample` section, this may need backend database operations. 

## Implementation 
- Update `specimenType` in Collab SONG payloads so it is correct `Primary tumour - solid tissue`
 - done in SQL in db 

- [x] complete collab song update
- [x] complete aws song update

**Comment by andricDu** [comment]
@lindaxiang this is now done.
