### ISSUE TITLE
Workflow Run Failure: Score Download

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#2]
## Describe the issue
```Checksum: 100%, Write/sec: 26.3M/s, Read/sec: 26.3M/s Finalizing... Total execution time: 1.268 h Total bytes read : 124,897,045,812 Total bytes written : 124,897,045,812 Verifying checksum... WARN: MD5 for ./out/d267a27e-fc6d-54bb-8ead-cc2b8072146d was fca1d10c12031102780866f5dc3c7192 but was expecting 5a5d05ee2abd81a78493a42887e0d31c ERROR: Command error: Number of retries exhausted Please check the log for detailed error messages Work dir: /nfs-1-c2/work/c6/bfebd8f52319e5725a87244f95d805 Tip: view the complete command output by changing to the process work dir and entering the command cat .command.out```

more info:
https://jira.oicr.on.ca/browse/DCCBIO-2

posisbly related ot the md5 audit that was previously performed in song

## List all runids affected
- wes-38342b77d5b9445b9b022bc7cd1ae4d7
- wes-af5eafbff778444d9037b4ac17cf2be1
- wes-6965297faacf42c4ba76d0eebf16f9b2
- wes-1da80f0a39a340529add03ec4dec6525

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by lindaxiang** [comment]
FYI. I downloaded following files from score-storage(https://storage.cancercollaboratory.org)
- the object: d267a27e-fc6d-54bb-8ead-cc2b8072146d(5a5d05ee2abd81a78493a42887e0d31c.bam) 
- the meta file: d267a27e-fc6d-54bb-8ead-cc2b8072146d.meta

As I know there are 3 places which contain md5sum information(correct me if I am wrong), but for this object, all three md5sum match with each other. 
- MD5 in SONG: 5a5d05ee2abd81a78493a42887e0d31c
- calculated MD5 of downloaded object: 5a5d05ee2abd81a78493a42887e0d31c
- MD5 in *.meta: 5a5d05ee2abd81a78493a42887e0d31c

But based on the error message: `Total bytes written : 124,897,045,812` seems not correct.
Should be: `Total bytes written : 125,155,383,508`
So the downloaded bam in the prod may be a corrupted one.

**Comment by rtisma** [comment]
I can confirm the same 3 MD5s @junjun-zhang mentioned. This seems like the downloaded bam was corrupted. The concerning thing is that it exhausted all retires to download it. If the disk was full during the download, then the client would fail to download the object, and would retry. Can @lepsalex see the diskspace available on that nfs mount (and any additional metrics that would cause write failures) around the time period of the failure?

**Comment by lepsalex** [comment]
Nowhere near full. Maybe it was downloading too many things at once?

![Screen Shot 2020-03-18 at 10 16 52 AM](https://user-images.githubusercontent.com/3143103/76970112-c6d5b700-6901-11ea-920f-ac3cfc4c4c66.png)

**Comment by rosibaj** [comment]
Next step: kick off one of these manually to see if the error occurs.

**Comment by rosibaj** [comment]
closing as this was a nfs load issue
