### ISSUE TITLE
Normalize wf identification values

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#203]
![image](https://user-images.githubusercontent.com/15824252/135469570-12cda406-c9f2-4220-b1bb-d581ce7bf4a6.png)

searching for open-access-variant-filtering does not result in any runs, but we there are actually many runs present. This ticket is to normalize the naming to allow for successful search. 

Ideas: 
- Different text analyzer
- Move to a wildcard field

**Comment by akachru-github** [comment]
Not in prod, but ready to be testing in QA.
