### ISSUE TITLE
Open Access Workflow documentation in preparation for data release

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#204]
PR: https://github.com/icgc-argo/argo-docs/pull/479

**Comment by lindaxiang** [comment]
- [x] Add workflow operation and technical documentation at: https://github.com/icgc-argo-workflows/open-access-variant-filtering/blob/main/README.md
- [x] Add one section for Open-access-filtering workflow
https://docs.icgc-argo.org/docs/analysis-workflows/dna-open-access-filtering
- [x] Extend data and file types to incorporate the open-access workflow outputs
https://docs.icgc-argo.org/docs/data/variant-calls
- [x] Add overview diagram for DNA-Seq pipelines: https://docs.icgc-argo.org/docs/analysis-workflows/analysis-overview

**Comment by lindaxiang** [comment]
@akachru-github 
- [ ] need to add release notes for Data release 5.0 after completing the data curation so as to close PR: icgc-argo/argo-docs#479 and this ticket.

**Comment by kcullion** [comment]
All docs updates made it to production
