### ISSUE TITLE
🐛 several analysis are PUBLISHED in SONG but missing from the RDPC GraphQL  

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#206]
## Describe the bug
The following 4 analysis are PUBLISHED in SONG but missing from the RDPC GraphQL
```
https://song.rdpc.cancercollaboratory.org/studies/LUCA-KR/analysis/5215f238-c4ae-4509-95f2-38c4aed50927
https://song.rdpc.cancercollaboratory.org/studies/LUCA-KR/analysis/e365141d-37d7-4540-a514-1d37d73540ba
https://song.rdpc.cancercollaboratory.org/studies/LUCA-KR/analysis/0939917b-8241-47b8-b991-7b8241d7b81f
https://song.rdpc.cancercollaboratory.org/studies/LUCA-KR/analysis/92430809-f756-435e-8308-09f756135e76
```

**Comment by jaserud** [comment]
@lindaxiang There was a blib in RDPC around the time these analysis were publishsed and it looks like maestro didn't get the events to index these analyses. I've reindexed these analysis via maestro so they should be correctly returned in gql now.

**Comment by lindaxiang** [comment]
@jaserud thank you for looking into this and get it sorted out so quickly.

**Comment by lindaxiang** [comment]
The issue has been addressed.
