### ISSUE TITLE
RNA seq aligner testing and feedback 

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#207]
- reviewing the 2 aligners and getting feedback: Hisat2 & Star
- making a whole workflow to test both aligners. 
- Receive and provide feedback to RNA Seq working group

Ticket can be closed when: 
- [ ] Feedback addressed
- [x] Both aligners are successfully tested in local
- [ ] Both aligners are successfully tested in RDPC DEV (this will require data to be staged in RDPC environment)

**Comment by akachru-github** [comment]
Current status: 
- Star already has been reviewed and approved. 
- Waiting for feedback from Andre on HiSat2.

**Comment by lindaxiang** [comment]
HiSat2 has been reviewed and work on the feedback now

**Comment by akachru-github** [comment]
- Both aligners have been tested independently
- Now using benchmark data to test in it's own VM

**Comment by akachru-github** [comment]
Next step:  
- blocked by https://github.com/overture-stack/SONG/issues/741. Song base schema needs to be updated to accept txt. 
- run workflow in RDPC DEV.

**Comment by akachru-github** [comment]
New version of Song with https://github.com/overture-stack/SONG/issues/741 has been deployed to QA. Unblocked.

**Comment by b-f-chan** [comment]
Tested successfully, waiting real data to go to prod before closing
