### ISSUE TITLE
Kafka for COVID Song to RDPC Prod

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-roadmap#21]
- [x] Deploy Kafka in COVID Project
- [ ] Use K-Ship to send events to prod RDPC
- [ ] Ingest service for events on the RDPC side
- [ ] Consume events in Prod RDPC to place on kafka in RDPC
- [ ] Model Tee will then consume this to schedule workflow runs.

**Comment by andricDu** [comment]
On hold for now.

**Comment by rosibaj** [comment]
Closing as no longer valid.
