### ISSUE TITLE
Ignore `.git` from fuzzy search in workflow repository URL

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#211]
Currently in the `repository` field of graphQL, we have some URLs with `.git` at the end, while some do not have. 
In principal, they are the same workflow URLs.

The current `fuzzy` search needs to support user to provide:
- URLs with `.git`
- URLs without `.git`

**Comment by akachru-github** [comment]
Requires a re-index when deployed to production. Probably take a couple of days
Required to fix donor dashboard issues.
