### ISSUE TITLE
Data Release 5.0 curation

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#218]
- @lindaxiang will identify what data is meant for release to the public.
- ticket can be closed once scope of the data being released is finalized. 

FYI @hknahal

**Comment by akachru-github** [comment]
Clicking the "Synchronize" button in staging does not seem to have the desired effect. This ticket is blocked until this is resolved. 
cc. @joneubank

**Comment by akachru-github** [comment]
ticket for "SYNC" blocker issue: https://github.com/icgc-argo/donor-submission-aggregator/issues/233

**Comment by akachru-github** [comment]
Blocked on https://github.com/icgc-argo/roadmap/issues/857.

**Comment by lindaxiang** [comment]
@joneubank QC the file repo on https://platform.staging.icgc-argo.org/repository
- There is one VCF from MUTO-INTL which is shown to be public in Staging while it should not be. 

The following donors/analysis are continued to be excluded from the data release 5.0 
- [x] MUTO-INTL: should NOT go to public
- [x] OCCAMS-GB: exclude the following 8 donors 

**Donor**|**Experiment**|**Exclude Reason**
:-----:|:-----:|:-----:
DO234196|WGS|Only Tumour aln
DO234235|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/144
DO234197|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/145
DO234216|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/146
DO50319|WGS|Only Tumour aln
DO234427|WGS|Sanger ASCAT failed: https://github.com/icgc-argo/workflow-roadmap/issues/146
DO234206|WGS|Only Normal aln
DO234201|WGS|Only Normal aln

- [x] PACA-CA 

Donor | Experiment| Status | Note | Action
-- | -- | -- | -- | --
DO35226 | WGS| Only Tumour Aln | The same donor has WXS data | **Exclude analysis**. [DO35226.wgs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435495/DO35226.wgs.exclude_analysisId.txt)
DO35140 | WXS | Only Tumour Aln | The same donor has WGS data. WXS share one same tumour sample with WGS| **Exclude analysis** [DO35140.wxs.exclude_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/6435504/DO35140.wxs.exclude_analysisId.txt)
DO35158 | WXS | Missing Sanger and Mutect2 | Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/94 | **Exclude donor**


- [x] PTC-SA Exclude the following donors

**Donor**|**Status**|**Note**
:-----:|:-----:|:-----:
DO234005|Missing Sanger|Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/95
DO231493|Missing Sanger and Mutect2| Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/29
DO231311|Missing Sanger and Mutect2| Data issue: https://github.com/icgc-argo/workflow-roadmap/issues/29

- [x] APGI-AU: exclude the following 2 donors

**Donor**|**Experiment**|**Exclude Reason**
:-----:|:-----:|:-----:
DO32887|WXS|Only Tumour aln
DO49123|WXS|Only Tumour aln

**Comment by kcullion** [comment]
@lindaxiang this can be closed now right?
