### ISSUE TITLE
Stage the reference files for RNA-Seq alignment workflow into Prod

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#220]

**Comment by lindaxiang** [comment]
**Reference genome and annotation**
1. Genome build: GRCh38 ([1000 Genome Project Version (http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/))
- Includes the primary assembly and alternate sequences from GRCh38
- Includes the decoy sequences
- Includes additional alternate versions of the HLA locus
- Includes EBV

2. Genome annotation: GENCODE 


**Reference datasets**
1. STAR
     - [Ref_genome_index_star](https://public.bmi.inf.ethz.ch/resources/icgc-argo/indexes/GRCh38_full_analysis_set_plus_decoy_hla.STARindex/)

2. HiSAT2
     - [Ref_genome_index_hisat2](https://public.bmi.inf.ethz.ch/resources/icgc-argo/indexes/GRCh38_full_analysis_set_plus_decoy_hla.STARindex/)

3. Picard: CollectRnaSeqMetrics
     - Ref_flat: a tab-delimited file containing information about the location of RNA transcripts, exon start and stop sites, etc. (an example [refFlat](http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/refFlat.txt.gz) file for GRCh38)
     - ribosomal_interval_list: provide the locations of rRNA sequences in the genome in interval_list format. If not specified no bases will be identified as being ribosomal.

**Comment by b-f-chan** [comment]
@lindaxiang to add additional info, once available, will stage to RDPC and close

**Comment by b-f-chan** [comment]
Met with RNA Seq working group, finalized versions for index file, etc - What remains is to release workflow

**Comment by b-f-chan** [comment]
Uploaded to object store but need to stage to RDPC - Need @jmimico help to get permission to access prod RDPC VMs

**Comment by lindaxiang** [comment]
Since RNA-Seq aligners are not ALT-aware, a slightly different version(GRCh38_Verily_v1) of reference genome is used by ICGC-ARGO for RNA-Seq Analysis. This file is a subset of GRCh38DH, and it is composed of the following sequences:
- GRCh38 primary assembly
- Decoy sequences
- Epstein-Barr virus (EBV) sequence

The reference files for RNA-Seq alignment workflow have been generated and uploaded to Collaboratory Open Bucket at:
```
https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data/rna-seq-references
```
@jmimico

**operation**|**folder**|**path on Collaboratory**|**path on RDPC Prod**
:-----:|:-----:|:-----:|:-----:
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-1/vol-1/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-1/vol-2/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-1/vol-3/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-1/vol-4/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-2/vol-1/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-2/vol-2/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-2/vol-3/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-2/vol-4/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-3/vol-1/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-3/vol-2/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-3/vol-3/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-3/vol-4/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-4/vol-1/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-4/vol-2/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-4/vol-3/reference
add | rna-seq-references |  https://object.cancercollaboratory.org:9080/swift/v1/genomics-public-data | /nfs/nfs-4/vol-4/reference

**Comment by jmimico** [comment]
Reference files have been seeded to all nfs mounts / volumes and should be ready for use in workflows. @lindaxiang please validate when you can and close this ticket once everything looks good on your end. Ping me if anything isn't right!

**Comment by b-f-chan** [comment]
Workflow is not running production yet, let's put pending in QA, can use test project in prod to verify all files are accessible and in good shape

**Comment by jmimico** [comment]
@lindaxiang Are these staged files sufficient for this ticket to be closed? Thank you!

**Comment by lindaxiang** [comment]
Yes. The reference files have all been staged into Prod. thanks @jmimico
