### ISSUE TITLE
RNA-Seq alignment performance optimization

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#224]
Prepare the following stats and logs for Andre to review and look for potential optimization 
- [x] Get a breakdown stats for each step in the workflow
- [x] Get the log files of Star and Hisat2

**Comment by lindaxiang** [comment]
@akahles 
Here is the list of all tasks which took more than 30min running time in RDPC, all the other steps are running less than 10min. 
**task\_name**|**running\_time(minutes)**|**note**
:-----:|:-----:|:-----:
hisat2|424| 
star|254.7| 
merMkdupHisat2|85.6|markdup and convert bam to cram
toLaneBam|81.8| 
alignedSeqQcHisat2|74.2|picard tool
alignedSeqQcStar|66.5|picard tool
fastqc (1)|43.4|fastqc tool
merMkdupStar|32.4|markdup and convert bam to cram

Here are two log files retrieved from Star and Hisat2 results:
[TCRB-CA.DO262483.SA622780.rna-seq.20220106.hisat2.supplement.tar.gz](https://github.com/icgc-argo/workflow-roadmap/files/7865534/TCRB-CA.DO262483.SA622780.rna-seq.20220106.hisat2.supplement.tar.gz)
[TCRB-CA.DO262483.SA622780.rna-seq.20220106.star.supplement.tar.gz](https://github.com/icgc-argo/workflow-roadmap/files/7865535/TCRB-CA.DO262483.SA622780.rna-seq.20220106.star.supplement.tar.gz)

Can you help to review them?

**Comment by b-f-chan** [comment]
Can move to QA testing, but when we do the alignment with real data and we see some performance issue, might need to revisit and adjust/tune
