### ISSUE TITLE
re-process PCAWG datasets to QC RNA-Seq alignment workflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#225]
This is to test the scientific correctness of the workflow output and ensure it has the correct output. 

- choose 10 PCAWG datasets
- re-align the datasets to GRCh38
- compare the stats

**Comment by lindaxiang** [comment]
Here are the major steps:

- [x] - manually download 10 datasets into one VM for ICGC
- [x] - payloads preparation
- [x] - activate the program in clinical qa
- [x] - create study in song.qa and submission-song.qa
- [x] - submit payloads and upload datasets to QA submission-song
- [x] - kick off the jobs (needs SONG base schema changes applied in RDPC-QA)
- [x] - generate the QC reports and review

**Comment by akachru-github** [comment]
- readgroup id has unacceptable characters for our current workflow. 
- working with the WG to find a workaround.

**Comment by akachru-github** [comment]
Found a workaround. Should be able to run this test in QA now.

**Comment by lindaxiang** [comment]
Here are some plots for the results comparison:
https://nbviewer.org/github/icgc-argo/qc-metrics-analysis/blob/main/notebooks/benchmark_rna_seq_qc.ipynb
