### ISSUE TITLE
Suppress SONG entries due to duplicated variant calling runs

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/workflow-roadmap#23]
It appears two jobs were doubly scheduled to run resulting in duplicated SONG entires.

Here are the run IDs:
- wes-fc723828e3f346c2b7ba93f70e4e252f duplicated with wes-7e1413a6d6a740c0b361df7f3e9228f4
-  wes-1c762f623a714568aa44f86747d2a7fd duplicated with wes-012467255a5c4e15a6222ecdb9b71391

The following SONG analysis entries need to be suppressed:
**from: wes-fc723828e3f346c2b7ba93f70e4e252f**
- bdd46fda-2147-4a70-946f-da2147ea702c
- f67098be-f7b1-4a26-b098-bef7b1aa2616
- 60e7cf15-f97c-444d-a7cf-15f97cc44db9
- f5cc62bc-b407-4374-8c62-bcb40743747a
- dd18a1cc-8a4c-4955-98a1-cc8a4c29557d
- 2c398c3e-326b-4799-b98c-3e326bc7994a

**from: wes-1c762f623a714568aa44f86747d2a7fd**
- be0c113e-79d2-4534-8c11-3e79d2d534a8
- 65addbf3-28f1-451f-addb-f328f1a51fd4
- 26d71163-82b9-47ab-9711-6382b917ab4d
- 4fc155d1-2a36-48e6-8155-d12a36c8e696
- 6eec46af-279d-4e87-ac46-af279d1e87a6
- 862a948d-0d35-4ec2-aa94-8d0d357ec254

**Comment by lindaxiang** [comment]
Suppressed the above duplicated analysis.
