### ISSUE TITLE
Gather user stories based on ongoing and incoming data submissions

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#237]
User stories: https://wiki.oicr.on.ca/display/icgcargotech/Data+Submission+User+Stories
Data submission log: https://docs.google.com/spreadsheets/d/1-CmHtdbTnSeTLQX4bhK4c5irVoDI7Ip9tRGssKH8BbQ/edit?usp=sharing

**Comment by b-f-chan** [comment]
Need Dev team (Jon) to generate SOP as output of this, but @lindaxiang task here is complete, so let's close

If new user stories or scenarios come up, we'll create separate ticket

Closing
