### ISSUE TITLE
OCCAMS-GB thoroughly cross check and audit the possible overlaps between processed and incoming data

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#248]

**Comment by edsu7** [comment]
- [reclassified reds to grey](https://docs.google.com/spreadsheets/d/1eiDOr79ZAg1wts7WmJzJXeNCT8MUBiDJGAlgkjiKzm4/edit?pli=1#gid=822596956) for samples that had a previously submitted `submitterSampleId` or `EGAR`
- did a search of known ARGO OCCAM-GB submitterSampleIds against the new IDs. No conflicts were detected however 
IDs that were renamed could bypass this.
- Of the remaining edge cases:
EGAR00001566520's matched normal exists in ARGO
EGAR00001436324's matched normal exists in ARGO
EGAR00001192957's matched tumour exists in ARGO
EGAR00001130626's matched normal exists in ARGO
[EGAR00001130631 and EGAR00001130630 were previously referenced as problematic](https://github.com/icgc-argo/argo-meta/tree/batch5-occams-gb/icgc_song_payloads/OCCAMS-GB/WGS/not-imported-batch4/DO10859)

**Comment by b-f-chan** [comment]
Scope of this ticket is just cross-check and audit, and we will address the remaining 4 edge cases to close it off

@hknahal to check these 4 and they get flagged, just omit from metadata payload

**Comment by b-f-chan** [comment]
@edsu7 - Hardeep has completed her audit and you an use her results/recommendations to proceed with the transferring

@hknahal to update ticket with relevant numbers

**Comment by b-f-chan** [comment]
Audit complete, @edsu7 reviewed the results, closing
