### ISSUE TITLE
QC WG pre-processing QC workflow development

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#251]

**Comment by lindaxiang** [comment]
workflow repo: https://github.com/icgc-argo-workflows/pre-alignment-qc
- New tools: seq-data-to-lane-fastq, multiqc, payload-gen-qc
- Update tools: fastqc, cutadpat

**Comment by b-f-chan** [comment]
@lindaxiang to convert to epic and add sub-tasks to breakdown the work more granularly

**Comment by b-f-chan** [comment]
@lindaxiang to create a separate ticket in this epic for testing the entire workflow itself end to end

**Comment by b-f-chan** [comment]
This workflow has actually been released and tested in QA - Can close epic after documentation wiki ticket completed
