### ISSUE TITLE
Investigate Sanger Caveman's preprocess requirements

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#252]
Determine what their stance is on:
- low quality reads
- adapter trimming/marking
- BaseRecalibration
- Indel-Realignment

**Comment by lindaxiang** [comment]
Details in wiki: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=154539988

**Comment by b-f-chan** [comment]
Analysis complete, feedback shared with working group, this task can be closed, no further investigation needed
