### ISSUE TITLE
Create argo-data-submission-wf

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#260]

**Comment by edsu7** [comment]
Tracking progress in [branch](https://github.com/icgc-argo/argo-data-submission/tree/argo-data-submission-wf)

**Comment by b-f-chan** [comment]
PR reviews still ongoing

**Comment by b-f-chan** [comment]
Payload generation has been updated, but no PR made yet for new version to be released; @lindaxiang needs to test also

**Comment by b-f-chan** [comment]
Note: Functionality was added to support backwards compatibility for those who have already prepared their own payloads

**Comment by b-f-chan** [comment]
MVP complete, can add more features later, can make formal version 1 release; leave ticket open until release @edsu7

**Comment by b-f-chan** [comment]
Released!  Can be closed
