### ISSUE TITLE
Create differentiate-json

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#261]

**Comment by edsu7** [comment]
Tracking progress in [branch](https://github.com/icgc-argo/argo-data-submission/tree/differentiate-json%400.1.0)

Running and Locally tested.

Remaining tasks:
- [x] Add exceptions
- [x] Update tests
- [ ] PR review

**Comment by edsu7** [comment]
Hey @hknahal and @lindaxiang,
I've uploaded an [error log output](https://github.com/icgc-argo/argo-data-submission/blob/differentiate-json/differentiate-json/tests/expected/expected_ERRORS.log) demonstrating expected behaviour when comparing user provided payload versus generated. Could you give it a look and tell me what you guys think?

1) [Example of conflicting values](https://github.com/icgc-argo/argo-data-submission/blob/da117d740b15346f019329cfad4653a5ba7c2433/differentiate-json/tests/expected/expected_ERRORS.log#L1)
```
Differing values found when comparing 'studyId' : user - TEST-PR vs auto_gen - OCCAMS-GB
```
2) [Example of conflicting values nested](https://github.com/icgc-argo/argo-data-submission/blob/da117d740b15346f019329cfad4653a5ba7c2433/differentiate-json/tests/expected/expected_ERRORS.log#L2)
```
Differing values found when comparing 'samples/specimen/submitterSpecimenId' : user - TEST_SPECIMEN vs auto_gen - SLX-18928.UDP0002
Differing values found when comparing 'samples/specimen' : user - {'submitterSpecimenId': 'TEST_SPECIMEN', 'specimenTissueSource': 'Blood derived', 'specimenType': 'Normal', 'tumourNormalDesignation': 'Normal'} vs auto_gen - {'submitterSpecimenId': 'SLX-18928.UDP0002', 'specimenTissueSource': 'Blood derived', 'specimenType': 'Normal', 'tumourNormalDesignation': 'Normal'}
```
- a bit of feature/bug if a nested conflict is detected, higher level dictionaries are returned. See [here](https://github.com/icgc-argo/argo-data-submission/blob/da117d740b15346f019329cfad4653a5ba7c2433/differentiate-json/tests/expected/expected_ERRORS.log#L2-L7)
3) [User payload missing term](https://github.com/icgc-argo/argo-data-submission/blob/da117d740b15346f019329cfad4653a5ba7c2433/differentiate-json/tests/expected/expected_ERRORS.log#L15)
```
'files/info/origin' not found in user generated JSON
```
4) [Differing list lengths e.g. different # of read groups found](https://github.com/icgc-argo/argo-data-submission/blob/da117d740b15346f019329cfad4653a5ba7c2433/differentiate-json/tests/expected/expected_ERRORS.log#L21)
```
Differing read_groups list length found in ' : user - 4 vs auto_gen - 7
```
One item to address is that the workflow logic expects lists to be alphabetically sorted else will report values as conflicting

**Comment by edsu7** [comment]
Pull request : https://github.com/icgc-argo/argo-data-submission/pull/10

**Comment by b-f-chan** [comment]
Closing, legacy items that no longer required for the general data submission workflow
