### ISSUE TITLE
Create download-aspera

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#262]

**Comment by edsu7** [comment]
Tracking progress in  [branch](https://github.com/icgc-argo/argo-data-submission/tree/download-aspera%400.1.0)

Running and Locally tested.

Remaining tasks:
- [x] Update tests
- [x] PR review

**Comment by edsu7** [comment]
Pull request : https://github.com/icgc-argo/argo-data-submission/pull/11

**Comment by b-f-chan** [comment]
PR reviewed and released (available on GitHub and WFPM can access/find it), closing
