### ISSUE TITLE
Create download-pyega3

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#263]

**Comment by edsu7** [comment]
Tracking progress in branch [branch](https://github.com/icgc-argo/argo-data-submission/tree/download-pyega3%400.1.0)

Running and Locally tested.

Remaining tasks:
- [x] Update tests
- [x] PR review

**Comment by edsu7** [comment]
Pull request : https://github.com/icgc-argo/argo-data-submission/pull/9

**Comment by b-f-chan** [comment]
Can be closed
