### ISSUE TITLE
Create generate-json

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#264]

**Comment by edsu7** [comment]
Tracking progress in [branch](https://github.com/icgc-argo/argo-data-submission/tree/generate-json%400.1.0)

Running and Locally tested.

Remaining tasks:
- [x] Add support for FASTQ
- [x] Update tests
- [ ] PR review

**Comment by edsu7** [comment]
Hi @hknahal and @lindaxiang 

Could you take a look at the [generated payload](https://github.com/icgc-argo/argo-data-submission/blob/generate-json/generate-json/tests/expected/expected_output.json) and your thoughts?

Some remaining items to address:
1) `experimental_strategy` is generated by checking `SampleType`.
- Add a new workflow parameter to account for `WES`,`WXS`,`Target WGS`?
2) What do to when `library_name` cannot be identified in bam
- Use other fields to populate else fail?
3) FASTQs
- `library_name`?
4) Hardeep posed a check to verify conflicting read groups across files
5) Verify read group concordance between header and body?

**Comment by edsu7** [comment]
Pull request : https://github.com/icgc-argo/argo-data-submission/pull/8

**Comment by b-f-chan** [comment]
Closing, legacy items that no longer required for the general data submission workflow
