### ISSUE TITLE
Create decrypt-aspera

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#265]

**Comment by edsu7** [comment]
Tracking progress in [branch](https://github.com/icgc-argo/argo-data-submission/tree/decrypt-aspera%400.1.0)

Running and Locally tested.

Remaining tasks:
- [x] Update tests
- [x] PR review

**Comment by edsu7** [comment]
Pull request : https://github.com/icgc-argo/argo-data-submission/pull/7

**Comment by b-f-chan** [comment]
PR reviewed and released (available on GitHub and WFPM can access/find it), closing
