### ISSUE TITLE
Update Song Base and Dynamic schema to latest across all 3 Env to support RNA-Seq data process

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#266]
To support RNA-Seq data process across all 3 ENVs, both base and dynamic SONG schema need to be updated to have the following two features:  
- Base schema changes: https://github.com/overture-stack/SONG/issues/750
- Dynamic schema changes: https://github.com/icgc-argo/argo-metadata-schemas/tree/master/schemas

Here is the current status:
 
| |Have Base schema changes |  Have Dynamic schema changes|
|-----|-----|-----|
|Prod-intermediate-song |No | No|
|Prod-submission-song|No|Yes|
|Prod-song|No|No|
|QA-intermediate-song |  |  | 
|QA-submission-song|Yes|Yes|
|QA-song|Yes|Yes|
|Dev-intermediate-song|Yes|No|
|Dev-submission-song|Yes|Yes|
|Dev-song|Yes|Yes|

**Comment by lindaxiang** [comment]
Updated on June28
| |Have Base schema changes |  Have Dynamic schema changes| Dynamic SONG version |
|-----|-----|-----|-----|
|Prod-intermediate-song |YES | YES - sequencing_experiment | [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|Prod-submission-song|YES|YES  - sequencing_experiment | [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|Prod-song|YES| YES - sequencing_alignment, qc_metrics, splice_junctions, supplement | [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|QA-intermediate-song |  |  | [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|QA-submission-song|Yes|Yes  - sequencing_experiment | [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|QA-song|Yes|Yes- sequencing_alignment, qc_metrics, splice_junctions, supplement| [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|Dev-intermediate-song|Yes|YES - sequencing_experiment| [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|Dev-submission-song|YES|Yes  - sequencing_experiment| [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|
|Dev-song|Yes|YES - sequencing_alignment, qc_metrics, splice_junctions, supplement| [0.8.0](https://github.com/icgc-argo/argo-metadata-schemas/releases/tag/0.8.0)|

**Comment by b-f-chan** [comment]
Work has been done and tested in different workflow environments, results look fine, can be closed

(Was just a task to update the schema in each environment)
