### ISSUE TITLE
Adjust payload-gen-seq-experiment to handle extra-info

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#269]
This tool accepts 3 TSVs but we are adjusting it to handle an optional 4th (captured within an extra-info field)

However, some of this extra-info would make more sense to move into the primary TSVs

Ultimate decision --> These fields not always needed, are rather conditional, so best that the logic mimics conditional fields in the clinical dictionary

**Comment by edsu7** [comment]
[Branch started](https://github.com/icgc-argo-workflows/data-processing-utility-tools/tree/payload-gen-seq-experiment%400.6.0.1/payload-gen-seq-experiment)
[PR requested](https://github.com/icgc-argo-workflows/data-processing-utility-tools/pull/152)

**Comment by puneet-oicr** [comment]
Schema validation needed where payload is generated

**Comment by edsu7** [comment]
Added in a step that validates files against schema.
Noticed typo in schema.
Started branch to address https://github.com/icgc-argo/argo-metadata-schemas/blob/seq_experiment_typo/schemas/sequencing_experiment.json
