### ISSUE TITLE
Use APGI-AU RNA-Seq imported data for QC benchmarking tests in RDPC-QA

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#273]

**Comment by b-f-chan** [comment]
First step in collecting stats for receiving data --> @lindaxiang planning to do this prior to meeting with RNA-Seq working group, wants to share some of the results/stats with them

**Comment by lindaxiang** [comment]
- 10 samples have been selected to run the pre-alignment-qc-wf
- qc metrics are collected to be reviewed: https://docs.google.com/spreadsheets/d/1g7o45YdGvPEaBwOk8Wo0H4mkKjH70gXcLcd19U3TDtc/edit?usp=sharing

Next step:
- discuss with QC wg to come up with a strategy or define criteria to assess the quality of the samples
For example, in PCAWG a sample was marked as a candidate for exclusion if 3 out of 5 main FastQC measures (base-wise quality, k-mer overrepresentation, guanine-cytosine content, content of N bases and sequence quality) did not pass
- Planning how to integrate the collected QC metrics into program QC dashboard, and pipeline automation running decider.
ref wiki: https://wiki.oicr.on.ca/display/icgcargotech/Program+QC+Molecular+Data+Interface+Specs

**Comment by puneet-oicr** [comment]
Scope completed. New ticket needed for the "next steps" listed by Linda
