### ISSUE TITLE
Create wiki page for argo-data-submission-wf

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#274]
wiki page: https://wiki.oicr.on.ca/display/icgcargotech/ICGC-ARGO+Molecular+Data+Submission

**Comment by lindaxiang** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Pre+Alignment+QC+Workflow

**Comment by puneet-oicr** [comment]
Set up meeting with Melanie for her inputs. Blocking for now

**Comment by b-f-chan** [comment]
Already demo'ed to Melanie and got good feedback and existing wikii page has the content we need, so closing
