### ISSUE TITLE
Strategize with QC to assess the quality of the samples

### ISSUE THREAD

**Issue by puneet-oicr** [icgc-argo/workflow-roadmap#275]

**Comment by puneet-oicr** [comment]
Refer #273 
For example, in PCAWG a sample was marked as a candidate for exclusion if 3 out of 5 main FastQC measures (base-wise quality, k-mer overrepresentation, guanine-cytosine content, content of N bases and sequence quality) did not pass

**Comment by lindaxiang** [comment]
Got feedback from QC working group meeting on Sep02. 
For both DNAseq and RNAseq:
- An aggregated metric:`total de-duplicated reads pass filter`=`total_sequences`*`(1-duplicated_percentage`) > 5 millions will be used as the cutoff to assess the sample quality and potentially stop the downstream analysis. (Ref: [Critical Metrics](https://docs.google.com/document/d/1Ssv85FkO6zOSq-lpp97mYR_wr3RFP3pTGf3y6B68_pU/edit#heading=h.m9qpynety2ec)) 
- Both `total_sequences` and `duplicated_percentage` are reported from [FastQC in `pre-alignment-qc-wf`](https://docs.google.com/spreadsheets/d/1g7o45YdGvPEaBwOk8Wo0H4mkKjH70gXcLcd19U3TDtc/edit#gid=0) will be used to calculate the above aggregated metric. 
- All the other metrics reported from both `FastQC` and `Cutadapt` will be tracking but not be used as the cutoff to stop the downstream analysis.

**Comment by b-f-chan** [comment]
To be determined --> How and where we automatically calculated the `total de-duplicated reads pass filter`.  Should be straightforward calculation, but need to decide where to do this.

Need to compute before indexing into Elasticsearch, OR we create a field in ES to do this calculation,  need to discuss with Dev team.  This may be a wider more general discussion how how we compute/store these aggregated fields that are outputs from the workflows.

**Comment by b-f-chan** [comment]
Closing for now, as longer-term strategy will be handled separately.  Decision has been made for this ticket on what metrics to use.

Note this ticket is only for Pre-Alignment workflow metrics.  Other workflows will have different decisions.

**Comment by b-f-chan** [comment]
We'll create a separate wiki page to track the decisions on what stats to track for each workflow - Brandon to setup for Linda.  Closing.
