### ISSUE TITLE
Investigate Support for CRAM file submission

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#277]
Request from P1000-US program to support CRAM file submission.

Need to first investigate and compare various approaches before deciding on implementation.

**Comment by b-f-chan** [comment]
Received an email from P1000-US asking us to support CRAM file submission, do we need to prioritize?   At the least P1000-US wanted a target date/timeline.  They're holding off on their submission until we have CRAM file submission support.  Need to check priority with @mcourtot first and @puneet-oicr concerning bandwidth.

@lindaxiang @edsu7 have investigated an initial approach, recommendation is this can be higher priority than the RNA-Seq strandedness work.  Will need more investigation into the approach and compare different submission methods out there for CRAM.

**Comment by b-f-chan** [comment]
Closing, investigation done
