### ISSUE TITLE
Request from RNA-Seq WG: test RNA-Seq packages with PCAWG data

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#280]
The purpose is to test all RNA-Seq packages which will go into join workflow for Prod, to see whether we find any bumps, check how they work together, and compare the results:

- [ ] - Alignment
- [ ] - Expression counting
- [ ] - Alternative promoter
- [ ] - ASE
- [ ] - Splicing

**Comment by b-f-chan** [comment]
Need to collect this data to support the workflow group publication/paper that plans to be written

**Comment by b-f-chan** [comment]
Plan to resume this work this week

**Comment by b-f-chan** [comment]
Note: The Working Group does expect us to report back these results to them --> Recall that end goal is to publish a paper about these tools.  Linda to take first stab, might pull Edmund in if needed

**Comment by lindaxiang** [comment]
Not to do atm.
