### ISSUE TITLE
Create Draft User Documentation for New Generalized Data Submission Workflow

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#281]
Create draft of user docs for general data submission workflow

Start with internal Google Doc --> We will review and polish it internally, then later decide on publishing method

**Comment by edsu7** [comment]
Draft:
https://docs.google.com/document/d/16XvfFPjiIiXsy0dIldLJDXTbXBBOKIT5Opg8JJjenTY/edit?usp=sharing

**Comment by b-f-chan** [comment]
Draft ready for review, @lindaxiang @hknahal to review

**Comment by b-f-chan** [comment]
Linda did quick review but needs deeper dive, this will be priority task for Linda this week of Sept 14; need to better structure content to different users, specifically regular scientists vs senior developers

**Comment by lindaxiang** [comment]
Revised draft: https://docs.google.com/document/d/14crfWmOaCJ85kVgKtik9kVJQ-pTDud_iX04wbviFDj4/edit

**Comment by b-f-chan** [comment]
Continuing to add more details this week, but bulk of content is there.  Main sticking point is how to create a secure test project for users.  Create separate ticket for that to check feasibility.  If can't do, remove it from document.

@lindaxiang before creating ticket, can we do quick huddle with @joneubank to discuss feasibility and get their input first?

**Comment by b-f-chan** [comment]
Initial is done, closing, we'll track feedback in separate tickets
