### ISSUE TITLE
Update Metadata Dictionary for General Data Submission Workflow

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#282]
The existing google sheet with the metadata dictionary for the general data submission workflow needs updates:

https://docs.google.com/spreadsheets/d/1-s5ZpRRjWukgmqWiboQ549doAclPBlJuW4iPCAa0w2c/edit#gid=1984561086

After internal review and approval, we will have separate ticket to add this to the ARGO doc site

**Comment by b-f-chan** [comment]
Edmund to prioritize for this week so we can finalize the sheet

**Comment by edsu7** [comment]
Current draft looks solid

**Comment by lindaxiang** [comment]
The metadata dictionary has been added into github: https://github.com/icgc-argo/argo-data-submission/tree/main/metadata_dictionary

**Comment by b-f-chan** [comment]
Field list finalized, no additional work needed unless major feedback is received.  Closing, will track feedback in separate tickets.
