### ISSUE TITLE
Update Model-Tee to include `pre-alignment-qc-wf` scheduler

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#283]
Update the Model Tee Python script to include the specific job parameters to run the new `pre-alignment-qc-wf`

Model Tee retrieves the info from the workflow scheduling spreadsheet and generates the necessary JSON files, it also checks the RDPC workload and does the scheduling

Normally would test in QA, but currently the environments need to be cleaned up first

**Comment by b-f-chan** [comment]
Closing ticket because has work has been done, no PR review required
