### ISSUE TITLE
Remove samples for POG-CA program

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#286]
Related to ARGO HelpDesk ticket: https://extsd.oicr.on.ca/browse/ARGOHD-264

Program submitted samples for these donors in error. They have requested that we remove the samples for the following donors.
DO252119 (submitter_donor_id "30822")
DO252078 (submitter_donor_id "23674")

**Comment by hknahal** [comment]
For both donors, only sample registration and molecular data have been submitted. No other clinical data has been submitted.

**DO252119** (submitter_donor_id = "30822")
- Program registered a tumour/normal pair of samples for this donor
- Program also submitted BAM files for each sample

| Tumour/normal | submitter_sample_id | submitter_specimen_id | analysis_id |
|--|--|--|--|
|Tumour | P01567 | 30822-OCT-2-P01567 | [a443c8cc-2565-4285-83c8-cc2565128595](https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/search/id?sampleId=SA612990) |
|Normal | P01582 | 30822-PB-P01582 | [af015f2b-4aae-41cf-815f-2b4aae61cf3d](https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/search/id?sampleId=SA612991) |

```
{
  "schemaMetadata": {
    "lastValidSchemaVersion": "1.14",
    "isValid": true,
    "originalSchemaVersion": "1.14"
  },
  "gender": "Female",
  "submitterId": "30822",
  "programId": "POG-CA",
  "specimens": [
    {
      "samples": [
        {
          "sampleType": "Total DNA",
          "submitterId": "P01567",
          "sampleId": "SA612990"
        }
      ],
      "clinicalInfo": {},
      "specimenTissueSource": "Lymph node",
      "tumourNormalDesignation": "Tumour",
      "specimenType": "Metastatic tumour",
      "submitterId": "30822-OCT-2-P01567",
      "specimenId": "SP212990"
    },
    {
      "samples": [
        {
          "sampleType": "Total DNA",
          "submitterId": "P01582",
          "sampleId": "SA612991"
        }
      ],
      "clinicalInfo": {},
      "specimenTissueSource": "Blood derived - peripheral blood",
      "tumourNormalDesignation": "Normal",
      "specimenType": "Normal",
      "submitterId": "30822-PB-P01582",
      "specimenId": "SP212991"
    }
  ],
  "clinicalInfo": {},
  "primaryDiagnoses": [],
  "familyHistory": [],
  "followUps": [],
  "treatments": [],
  "comorbidity": [],
  "exposure": [],
  "biomarker": [],
  "createdAt": "2022-09-20T21:41:53.983Z",
  "updatedAt": "2022-09-20T21:41:53.983Z",
  "donorId": "DO252119"
}
```



**DO252078** (submitter_donor_id = "23674")

- Program registered 2 tumour samples for this donor
- Program submitted a BAM file for only one of the samples (submitter_sample_id = "P00394")

| Tumour/normal | submitter_sample_id | submitter_specimen_id | analysis_id |
|--|--|--|--|
| Tumour | P00286 | 23674-FF-1-P00286 | |
| Tumour | P00394 | 23674-FFPE-3-P00394 | [72c626f0-48c2-4b8b-8626-f048c25b8b53](https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/search/id?donorId=DO252078&sampleId=SA612909) |

```
{
  "schemaMetadata": {
    "lastValidSchemaVersion": "1.14",
    "isValid": true,
    "originalSchemaVersion": "1.14"
  },
  "gender": "Female",
  "submitterId": "23674",
  "programId": "POG-CA",
  "specimens": [
    {
      "samples": [
        {
          "sampleType": "Total DNA",
          "submitterId": "P00286",
          "sampleId": "SA612908"
        }
      ],
      "clinicalInfo": {},
      "specimenTissueSource": "Bone",
      "tumourNormalDesignation": "Tumour",
      "specimenType": "Metastatic tumour",
      "submitterId": "23674-FF-1-P00286",
      "specimenId": "SP212908"
    },
    {
      "samples": [
        {
          "sampleType": "Total DNA",
          "submitterId": "P00394",
          "sampleId": "SA612909"
        }
      ],
      "clinicalInfo": {},
      "specimenTissueSource": "Solid tissue",
      "tumourNormalDesignation": "Tumour",
      "specimenType": "Recurrent tumour",
      "submitterId": "23674-FFPE-3-P00394",
      "specimenId": "SP212909"
    }
  ],
  "clinicalInfo": {},
  "primaryDiagnoses": [],
  "familyHistory": [],
  "followUps": [],
  "treatments": [],
  "comorbidity": [],
  "exposure": [],
  "biomarker": [],
  "createdAt": "2022-09-12T19:00:14.006Z",
  "updatedAt": "2022-09-12T19:00:14.006Z",
  "donorId": "DO252078"
}
```

**Comment by hknahal** [comment]
Steps for removing tumour sample "P01567" for donor ID DO252119 using Data Deletion SOP at  https://wiki.oicr.on.ca/pages/viewpage.action?pageId=150638363

- [x] No clinical data has been submitted for these donors.
- [x] No active sample registration/clinical submission

Steps:
1. Do 'dry-run' of deletion of registered submitter_sample_id "P01567" using DELETE endpoint (DELETE /submission/program/{programId}/registration/unregister)

```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/POG-CA/registration/unregister?dryRun=true&sampleSubmitterIds=P01567' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer my_ego_token'
```

Result:
```
{
  "dryRun": true,
  "samplesDeleted": [
    "P01567"
  ],
  "specimensDeleted": [
    "30822-OCT-2-P01567"
  ],
  "donorsDeleted": []
}
```

This deletes the affected submitter_specimen_id "30822-OCT-2-P01567" as well without deleted the donor ID.

2. Do the actual deletion using the same DELETE endpoint without 'dry-run':
```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/POG-CA/registration/unregister?dryRun=false&sampleSubmitterIds=P01567' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer my_ego_token'
```
Result:
```
{
  "dryRun": false,
  "samplesDeleted": [
    "P01567"
  ],
  "specimensDeleted": [
    "30822-OCT-2-P01567"
  ],
  "donorsDeleted": []
}
```
3. Suppress analysis ID a443c8cc-2565-4285-83c8-cc2565128595 in SONG:

```
curl -X PUT "https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/suppress/a443c8cc-2565-4285-83c8-cc2565128595" -H "accept: */*" -H "Authorization: Bearer my_ego_token"
```
Result:
```
AnalysisId a443c8cc-2565-4285-83c8-cc2565128595 was suppressed
```
4. Attempted to delete sample "SA612990"  in submission SONG, but delete sample endpoint does not work:
```
curl -X DELETE "https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/samples/SA612990" -H "accept: */*" -H "Authorization: Bearer my_ego_token"
```
Result: 500 Error
```
 cache-control: no-cache, no-store, max-age=0, must-revalidate 
 date: Wed, 28 Sep 2022 20:16:45 GMT 
 expires: 0 
 pragma: no-cache 
 strict-transport-security: max-age=15724800; includeSubDomains 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block 
```

This error appears to be related to https://github.com/overture-stack/SONG/issues/777

5. Confirmed tumour sample has been removed in Platform:

![DO252119_tumour_sample_removed](https://user-images.githubusercontent.com/4992044/192880833-ca0d4bb9-92b6-464b-8a4d-60e518851299.png)

---------------------------------------------------------------------------------------------------

Checklist:
- [x]  Sample removed in clinical
- [x]  Specimen removed in clinical
- [x]  Confirm Sample/specimen removed reflected on program dashboard
- [x]  Downloading clinical data should reflect the removal
- [x]  Suppress analysis ID in submission SONG 
- [ ]  Delete sample in submission SONG **Unable to delete sample and specimen in SONG because deletion endpoints are not working**

**Comment by hknahal** [comment]
Followed same steps above to delete normal sample "P01582":

Steps:
1. Do 'dry-run' of deletion of registered submitter_sample_id "P01582" using DELETE endpoint (DELETE /submission/program/{programId}/registration/unregister):
```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/POG-CA/registration/unregister?dryRun=true&sampleSubmitterIds=P01582' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer my_ego_token'
```
Result:
```
{
  "dryRun": true,
  "samplesDeleted": [
    "P01582"
  ],
  "specimensDeleted": [
    "30822-PB-P01582"
  ],
  "donorsDeleted": [
    "30822"
  ]
}
```
Notice, this time submitter_donor_id "30822" will be deleted because it has no other samples/specimens associated with it.

2. Do the actual deletion using the same DELETE endpoint without 'dry-run':
```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/POG-CA/registration/unregister?dryRun=false&sampleSubmitterIds=P01582' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer my_ego_token'
```
Result:
```
{
  "dryRun": false,
  "samplesDeleted": [
    "P01582"
  ],
  "specimensDeleted": [
    "30822-PB-P01582"
  ],
  "donorsDeleted": [
    "30822"
  ]
}
```
3. Suppress analysis ID af015f2b-4aae-41cf-815f-2b4aae61cf3d in submission SONG:
```
curl -X PUT "https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/suppress/af015f2b-4aae-41cf-815f-2b4aae61cf3d" -H "accept: */*" -H "Authorization: Bearer my_ego_token"
```
Result:
```
AnalysisId af015f2b-4aae-41cf-815f-2b4aae61cf3d was suppressed
```
4. Attempted to delete sample "SA612991"  in submission SONG, but delete sample endpoint does not work:
```
curl -X DELETE "https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/samples/SA612991" -H "accept: */*" -H "Authorization: Bearer my_ego_token"
```
Result: 500 Error
```
cache-control: no-cache, no-store, max-age=0, must-revalidate 
 date: Wed, 28 Sep 2022 20:41:15 GMT 
 expires: 0 
 pragma: no-cache 
 strict-transport-security: max-age=15724800; includeSubDomains 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block 
```

5. Confirmed tumour sample has been removed in Platform. Can no longer filter for donor ID "DO252119" in POG-CA Dashboard.

------------------------------------------------------------------
Checklist:
- [x]  Sample removed in clinical
- [x]  Specimen removed in clinical
- [x]  Confirm Sample/specimen removed reflected on program dashboard
- [x]  Downloading clinical data should reflect the removal
- [x]  Suppress analysis ID in submission SONG 
- [ ]  Delete sample in submission SONG **Unable to delete sample and specimen in SONG because deletion endpoints are not working**

**Comment by hknahal** [comment]
Blocked by https://github.com/overture-stack/SONG/issues/777 (unable to delete samples in submission SONG)

**Comment by joneubank** [comment]
Original samples were deleted from clinical then re-registered. The Analyuses in submission song that relate to the original samples have been suppressed.
https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/search/id?sampleId=SA612990
https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/search/id?sampleId=SA612991

We are requesting the BAMs to be resubmitted.

**Comment by hknahal** [comment]
submitter_sample_ids "P00286" and "P00394" were deleted in clinical. Only "P00394" had an analysis in submission-song, so analysis_id for it was suppressed: https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/search/id?donorId=DO252078&sampleId=SA612909

Will let data submitter know and request BAMs to be re-submitted.

**Comment by b-f-chan** [comment]
Has been resolved and submitter notified to do BAM resubmission, closing
