### ISSUE TITLE
Evaluate wfpm vs. nf-core

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#288]
Background
- We've been using [wfpm](https://wfpm.readthedocs.io/en/latest/README.html#) in ARGO workflow development for package authoring and management. It provides assistance to write sharable and reusable workflow packages among all ARGO pipelines.
- [nf-core](https://nf-co.re/) provides a framework to collect community efforts for the development of collaborative and peer-reviewed analysis pipelines. It has developed a suite of tools that automate pipeline creation, testing, deployment and synchronization.

Expected Output
- We need to investigate and evaluate whether we should switch to join `nf-core` for workflow and pipeline development.

**Comment by lindaxiang** [comment]
Preliminary evaluation: https://docs.google.com/document/d/15pjSc5K_p8U8WeVL-rDWkzltQq52tqRdsN0YAOg6SwM/edit?usp=sharing

**Comment by b-f-chan** [comment]
Further evaluate/investigate whether to switch to `nf-core` BEFORE circulating any news to the working groups/community --> Need to finalize decision first; also need to understand and estimate effort.  Might not be appropriate for ARGO to release code from another org's GitHub if we take this on.  May need Brandon's help to coordinate stakeholders who will make this decision.

Suggestion --> Setup meeting with `nf-core` to present to all OICR stakeholders

**Comment by b-f-chan** [comment]
NF-Core available to give us an overview next week; @lindaxiang will coordinate with other working group members & leaders

**Comment by b-f-chan** [comment]
DCM-WG meeting, most participants are favouring switch to NF-Core, but need some extra evaluation/guidelines --> Lincoln has nominated folks from RNA-Seq WG to do this additional analysis.  In meantime, we'll test NF-Core on a new workflow on RDPC.

**Comment by b-f-chan** [comment]
RNA-Seq WG still doing their additional evaluation (Andre, Raquel), investigating how to migrate WFPM workflow to NF-Core workflow, still pending

**Comment by b-f-chan** [comment]
Need to brainstorm how to incorporate NF-Core into our Git repo codebase!

Suggestion --> We should have a separate repo just to handle the NF-Core integration, so original users of WFPM repo don't encounter any compatibility issues

**Comment by puneet-oicr** [comment]
We need to prepare for the switch.
New ticket for the same - https://github.com/icgc-argo/workflow-roadmap/issues/298
