### ISSUE TITLE
Investigate failed Sanger WXS runs

### ISSUE THREAD

**Issue by junjun-zhang** [icgc-argo/workflow-roadmap#29]
Two Sanger WXS runs failed:
https://wes.rdpc.cancercollaboratory.org/runs/wes-d89d1836ec324b7690fd02d1bc0c37ee
https://wes.rdpc.cancercollaboratory.org/runs/wes-c357b48900284bc898951f56b39372ab

**Comment by rosibaj** [comment]
@junjun-zhang @lindaxiang are these still issues?

**Comment by lindaxiang** [comment]
@rosibaj , yes. they are still unsolved and in progress issues.

**Comment by joneubank** [comment]
Closing stale issue.
