### ISSUE TITLE
Suppress the output analysis from the previous runs with workflow version `0.1.1`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#295]
New version `0.2.0` has added transcriptome output bam from Star. We'll need to suppress all the output analysis from the previous runs with workflow version `0.1.1`. Here is the list:
[APGI-AU.to_suppress.RNAseq.txt](https://github.com/icgc-argo/workflow-roadmap/files/10086097/APGI-AU.to_suppress.RNAseq.txt)

**donorID**|**analysisType**|**firstPublishDate**|**workflowVersion**|**analysisId**
:-----:|:-----:|:-----:|:-----:|:-----:
DO32831|qc\_metrics|2022-09-27T22:29:42.938927|0.1.1|6abdadb8-14d4-4e41-bdad-b814d47e4140
DO32831|qc\_metrics|2022-09-28T02:16:54.350445|0.1.1|f93918b8-0f8c-4fca-b918-b80f8cafca20
DO32831|sequencing\_alignment|2022-09-27T22:31:23.047521|0.1.1|b810e064-d79b-421d-90e0-64d79b021d1f
DO32831|sequencing\_alignment|2022-09-28T02:19:25.637649|0.1.1|9a766cfd-f478-4acb-b66c-fdf478aacbaa
DO32831|splice\_junctions|2022-09-27T21:35:05.345244|0.1.1|3127e430-4d51-4dd5-a7e4-304d518dd524
DO32831|splice\_junctions|2022-09-28T00:29:23.190143|0.1.1|d1b6c4df-b477-4fe7-b6c4-dfb4775fe737
DO32831|supplement|2022-09-27T21:34:55.418677|0.1.1|91c8fc6e-d0b5-4a9c-88fc-6ed0b59a9c12
DO32831|supplement|2022-09-28T00:29:15.22764|0.1.1|304afd00-2b5c-45f4-8afd-002b5ca5f4f6
DO32860|qc\_metrics|2022-09-21T01:30:10.828076|0.1.1|75e7b20a-4a13-466b-a7b2-0a4a13566b7d
DO32860|qc\_metrics|2022-09-21T05:10:11.047887|0.1.1|16c27184-de27-4c44-8271-84de27dc4499
DO32860|sequencing\_alignment|2022-09-21T01:32:06.575949|0.1.1|8510889f-e8c5-4ca5-9088-9fe8c5fca5e6
DO32860|sequencing\_alignment|2022-09-21T04:46:07.558448|0.1.1|607e1885-c47a-468b-be18-85c47ad68b6d
DO32860|splice\_junctions|2022-09-20T23:47:17.305674|0.1.1|d99ca984-124d-45f3-9ca9-84124d25f3e0
DO32860|splice\_junctions|2022-09-21T04:08:46.99266|0.1.1|8ca1840e-056d-478f-a184-0e056de78f15
DO32860|supplement|2022-09-20T23:47:18.364608|0.1.1|41b8de4c-f065-49c6-b8de-4cf06509c6c2
DO32860|supplement|2022-09-21T04:08:48.426685|0.1.1|fa0bc55e-35fa-4da8-8bc5-5e35fa0da8c4
DO32900|qc\_metrics|2022-09-21T00:10:46.53859|0.1.1|d26b9fcb-6896-4b16-ab9f-cb6896ab16d1
DO32900|qc\_metrics|2022-09-21T07:45:40.168994|0.1.1|14175f0d-62dc-471e-975f-0d62dc971e96
DO32900|sequencing\_alignment|2022-09-20T23:48:35.261428|0.1.1|ccb7757c-2922-4fb8-b775-7c29228fb809
DO32900|sequencing\_alignment|2022-09-21T07:49:11.042945|0.1.1|8c70222a-89f5-4869-b022-2a89f5a869bc
DO32900|splice\_junctions|2022-09-20T22:55:33.110414|0.1.1|6bbe56d7-e6d9-478c-be56-d7e6d9378c39
DO32900|splice\_junctions|2022-09-21T05:57:02.215638|0.1.1|da108fea-4aa9-4ae9-908f-ea4aa92ae9eb
DO32900|supplement|2022-09-20T22:55:29.574399|0.1.1|3017ed13-1642-466a-97ed-131642f66ac5
DO32900|supplement|2022-09-21T05:57:07.875264|0.1.1|9ba78cb9-fe73-4b7e-a78c-b9fe73db7e50
DO33392|qc\_metrics|2022-09-20T22:33:34.701867|0.1.1|3628f856-4e53-470d-a8f8-564e53070db4
DO33392|qc\_metrics|2022-09-21T04:28:42.628184|0.1.1|ba8c80d9-ed96-4e0e-8c80-d9ed965e0e1c
DO33392|sequencing\_alignment|2022-09-20T21:56:33.582|0.1.1|75696bc0-de5a-4838-a96b-c0de5a6838be
DO33392|sequencing\_alignment|2022-09-21T04:10:23.866171|0.1.1|df01dbc8-c7a8-4630-81db-c8c7a8a63091
DO33392|splice\_junctions|2022-09-20T20:56:54.705187|0.1.1|982ba647-02b6-483f-aba6-4702b6d83fb3
DO33392|splice\_junctions|2022-09-21T02:35:42.30767|0.1.1|91869ef9-8ff4-4b73-869e-f98ff44b73f0
DO33392|supplement|2022-09-20T20:56:46.133939|0.1.1|ba754e4d-7394-47b8-b54e-4d739417b814
DO33392|supplement|2022-09-21T02:35:41.949626|0.1.1|80fbb3e7-74f0-4a6c-bbb3-e774f04a6c5b
DO34849|qc\_metrics|2022-09-20T19:40:24.841549|0.1.1|2f6e4ac8-8a32-4d94-ae4a-c88a324d947d
DO34849|qc\_metrics|2022-09-20T22:12:22.068383|0.1.1|359b53fc-b922-4e44-9b53-fcb9220e44b9
DO34849|sequencing\_alignment|2022-09-20T19:19:46.517579|0.1.1|d231e7e2-3dac-4957-b1e7-e23dac69572b
DO34849|sequencing\_alignment|2022-09-20T22:13:23.594961|0.1.1|e6138722-e35f-4cdb-9387-22e35f1cdb0b
DO34849|splice\_junctions|2022-09-20T18:51:01.510513|0.1.1|8f9ce363-e48d-46ca-9ce3-63e48d56ca88
DO34849|splice\_junctions|2022-09-20T21:25:11.64924|0.1.1|e3c85f08-25ae-4e98-885f-0825ae6e98d5
DO34849|supplement|2022-09-20T18:50:52.812323|0.1.1|dfc075ca-47be-4562-8075-ca47be156241
DO34849|supplement|2022-09-20T21:24:54.283545|0.1.1|17a1edcf-d3f5-4431-a1ed-cfd3f5343122

**Comment by lindaxiang** [comment]
This has been addressed in Prod for the listed analysisId of APGI-AU

**Comment by b-f-chan** [comment]
Everything suppressed, closing
