### ISSUE TITLE
Suppress all recently submitted samples for MUTO-INTL

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#296]
Will remove all recently submitted data (including duplicated samples) for MUTO-INTL as per program's request during Nov 24 meeting with them. They want to re-submit all the payloads because they submitted some incorrect read groups/platform field information. 

https://docs.google.com/spreadsheets/d/1Tg2BvetA2B3Im1zvtceUJkooTAhfJ-xRP5hJA_YBsEs/edit?usp=sharing

**Comment by hknahal** [comment]
Suppressed 1,028 analysis_ids for MUTO-INTL, except the red rows in the [table](https://docs.google.com/spreadsheets/d/1Tg2BvetA2B3Im1zvtceUJkooTAhfJ-xRP5hJA_YBsEs/edit?usp=sharing) because we need to investigate these further still, and the 10 donors that have processed data already (DO250000, DO250005, DO250002, 
DO250007, DO250006, DO250004, DO250009, DO250003, DO250001, DO250008).

[muto_suppressed_analyses.log](https://github.com/icgc-argo/workflow-roadmap/files/10106871/muto_suppressed_analyses.log)

- Program Dashboard is not updating to reflect this recent update, so will wait until it updates to confirm everything has been supressed properly.
Example: Both normal samples for DO250126 have been suppressed: https://submission-song.rdpc.cancercollaboratory.org/studies/MUTO-INTL/analysis/search/id?donorId=DO250126, but in the Program Dashboard it still shows `1N` under the "Raw Reads" column:
![muto_DO250126](https://user-images.githubusercontent.com/4992044/204057933-f4606c94-8445-40ea-8f07-bd6acbacd632.png)

**Comment by hknahal** [comment]
Jon and Rakesh re-indexed MUTO-INTL, so the Program Dashboard is updated to reflect the suppressed analyses now.

**Comment by puneet-oicr** [comment]
Testing pending till program dashboard is permanently fixed. The solution is in.
Will be closed after testing.
