### ISSUE TITLE
Gather workflow running stats from RDPC-Prod workflows

### ISSUE THREAD

**Issue by puneet-oicr** [icgc-argo/workflow-roadmap#297]
Gather running stats for all workflows in the past from RDPC-Prod:
- workflow_name
- workflow_version
- tasks
   - name
   - duration
   - realtime
   - cpus
   - memory
   - container
   - readBytes
   - writeBytes
   - vmem
   - peakVmem

**Comment by edsu7** [comment]
TSVs and visualization summaries:
https://drive.google.com/drive/folders/1KaOAgBA2gDjOLbuxZNOKgd7LMlur4_5N?usp=sharing

**Comment by edsu7** [comment]
Added visualizations for :
- RNA-seq QA
https://docs.google.com/presentation/d/13-Yv9DE0XLzEwAcEsKwpdUSVWGQZQEMa5pS72Sjqk6M/edit?usp=share_link
- DNA-Seq Prod
https://docs.google.com/presentation/d/1-7f2TE9-xrwiIiB-x_AJ1dALZAEH_55FL72NEJ8i-SU/edit?usp=share_link

**Comment by b-f-chan** [comment]
@lindaxiang to further analyze stats collected by @edsu7 before sharing with @jmimico @henro001

**Comment by edsu7** [comment]
Closing. Code will be generalized to be re-usable, see ticket:
https://github.com/icgc-argo/workflow-roadmap/issues/312
