### ISSUE TITLE
Benchmark DNA alignment WF run time in Dev with hyper threading ON vs. OFF

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#299]
Test job info:
- Workflow Repository: https://github.com/icgc-argo-workflows/dna-seq-processing-wfs
- Workflow Version: dna-seq-alignment@1.9.1
- analysis can be used for testing: 
    1. tumour wxs (following are duplicated analysis for the same dataset in Dev vs. QA): 
    - https://submission-song.rdpc-dev.cancercollaboratory.org/studies/TCRB-CA/analysis/dbe1ff4d-265e-42e2-a1ff-4d265ee2e202
    - https://submission-song.rdpc-qa.cancercollaboratory.org/studies/TCRB-CA/analysis/6daf9f7a-db7a-499a-af9f-7adb7af99a4f
    3. normal wxs (following are duplicated analysis for the same dataset in Dev vs. QA): 
    - https://submission-song.rdpc-dev.cancercollaboratory.org/studies/TCRB-CA/analysis/641afdc9-d14b-4c3b-9afd-c9d14bdc3b30
    - https://submission-song.rdpc-qa.cancercollaboratory.org/studies/TCRB-CA/analysis/f6929a82-8ffc-4975-929a-828ffc89752f

Benchmark steps:
- launch the wfs runs on nodes with hyper threading ON vs. OFF
- record the difference in run times specifically for step: `bwaMemAligner`
- information can be found from graphQL

Test requests setup:
- hyper threading ON with 38 cpus
     "bwaMemAligner": {
		"mem": 128,
		"cpus": 32 
     }
- hyper threading OFF with 19 cpus
    "bwaMemAligner": {
		"mem": 36,
		"cpus": 16 
     }

**Comment by lindaxiang** [comment]
The above two tumour/normal analysis have been both ran in QA last year with the following runId and params requests
- Tumour WXS: https://submission-song.rdpc-qa.cancercollaboratory.org/studies/TCRB-CA/analysis/6daf9f7a-db7a-499a-af9f-7adb7af99a4f
    - RDPC-QA runId: wes-00d2871edd764512a3dfe767d8b6de8c
    - engine params
```
          "engineParameters": {
            "launchDir": "/nfs-dev-1-vol-qa-1/wfgn-launch",
            "projectDir": "/nfs-dev-1-vol-qa-1/wfgn-project/icgc-argo-workflows/dna-seq-processing-wfs",
            "workDir": "/nfs-dev-1-vol-qa-1/wfgn-work",
            "revision": "1.9.0",
            "resume": "false"
          }
```
- bwa-mem requested params
```
          "bwaMemAligner": {
              "mem": 18,
              "cpus": 6
            }
```
- bwa-mem run time stats

```
            {
              "name": "DnaAln:bwaMemAligner (9854181989)",
              "duration": 7511395,
              "state": "COMPLETE",
              "startTime": "1637902202000",
              "tag": "9854181989",
              "workdir": "/nfs-dev-1-vol-qa-1/wfgn-work/46/8d142307d99eb6b46a4722e77104ae"
            }
```

- Normal WXS: https://submission-song.rdpc-qa.cancercollaboratory.org/studies/TCRB-CA/analysis/f6929a82-8ffc-4975-929a-828ffc89752f
    - RDPC-QA runId: wes-6fe9d376eb7c4162a366656ea5ac6935
    - engine params
```
          "engineParameters": {
            "launchDir": "/nfs-dev-1-vol-qa-1/wfgn-launch",
            "projectDir": "/nfs-dev-1-vol-qa-1/wfgn-project/icgc-argo-workflows/dna-seq-processing-wfs",
            "workDir": "/nfs-dev-1-vol-qa-1/wfgn-work",
            "revision": "1.9.0",
            "resume": "false"
          }
```

- bwa-mem requested params
```
          "bwaMemAligner": {
              "mem": 18,
              "cpus": 6
            }
```
- bwa-mem run time stats

```
           {
              "name": "DnaAln:bwaMemAligner (9570276415)",
              "duration": 7105444,
              "state": "COMPLETE",
              "startTime": "1637915954000",
              "tag": "9570276415",
              "workdir": "/nfs-dev-1-vol-qa-1/wfgn-work/42/43514fe736348eb5aa71eb6adcc00a"
            }
```
Note: duration is milliseconds.

**Comment by lindaxiang** [comment]
In contrast, the same datasets running in Dev
- Tumour WXS:  https://submission-song.rdpc-dev.cancercollaboratory.org/studies/TCRB-CA/analysis/dbe1ff4d-265e-42e2-a1ff-4d265ee2e202
  - RDPC-Dev runId: wes-380d7c8d8815451696e12090e67b650d
```
          "engineParameters": {
            "launchDir": "/nfs-dev-1-vol-dev-1/wfuser",
            "projectDir": "/nfs-dev-1-vol-dev-1/linda-projects/icgc-argo-workflows/dna-seq-processing-wfs",
            "workDir": "/nfs-dev-1-vol-dev-1/wfuser/work",
            "revision": "1.9.0",
            "resume": "false"
          }
```
  - bwa-mem requested params
```
            "bwaMemAligner": {
              "mem": 18,
              "cpus": 6
            }
```
  - bwa-mem run time stats
```
            {
              "name": "DnaAln:bwaMemAligner (9854181989)",
              "duration": 298606119,
              "cpus": 6,
              "memory": 19327352832,
              "state": "COMPLETE",
              "startTime": "1670012928000",
              "tag": "9854181989",
              "workdir": "/nfs-dev-1-vol-dev-1/wfuser/work/ad/a80d2f2f74ce0b6a5384c4419fab07"
            }
```

**Comment by lindaxiang** [comment]
- Normal WXS: https://submission-song.rdpc-dev.cancercollaboratory.org/studies/TCRB-CA/analysis/641afdc9-d14b-4c3b-9afd-c9d14bdc3b30
- RDPC-Dev runId: wes-0cf9b38a33594f19a4df2be4b4954f7e
- engine parameters
```
          "engineParameters": {
            "launchDir": "/nfs-dev-1-vol-dev-1/wfgn-launch",
            "projectDir": "/nfs-dev-1-vol-dev-1/wfgn-project/icgc-argo-workflows/dna-seq-processing-wfs",
            "workDir": "/nfs-dev-1-vol-dev-1/wfgn-work",
            "revision": "dna-seq-alignment@1.9.1",
            "resume": "false"
          }
```
- bwa-mem requested params
```
            "bwaMemAligner": {
              "mem": 128,
              "cpus": 24
            }
```
- bwa-mem run time stats
```
            {
              "name": "DnaAln:bwaMemAligner (9570276415)",
              "duration": 3360711,
              "cpus": 24,
              "memory": 137438953472,
              "state": "COMPLETE",
              "startTime": "1670347007000",
              "tag": "9570276415",
              "workdir": "/nfs-dev-1-vol-dev-1/wfgn-work/37/996766c079d85765a059888bd5aad7"
            }
```

**Comment by b-f-chan** [comment]
Plan for next week: Resume jobs, see if they go through Song/Score, then for new jobs/runs, use latest Song/Score modules to do a comparative analysis and see if same issues hapepn

**Comment by lindaxiang** [comment]
Summarize the benchmarking info:
| |**HT ON**|**HT OFF**|**HT ON (last year in QA)**
:-----:|:-----:|:-----:|:-----:
input\_analysis|641afdc9-d14b-4c3b-9afd-c9d14bdc3b30 (Dev)|641afdc9-d14b-4c3b-9afd-c9d14bdc3b30 (Dev)|f6929a82-8ffc-4975-929a-828ffc89752f (QA, same dataset as in Dev)
workflow\_version|dna-seq-alignment@1.9.1|dna-seq-alignment@1.9.1|1.9.0
bwa-mem\_params|24 cpus / 128 GB|12 cpus / 128 GB|6 cpus / 18GB
bwa-mem run time|3361 seconds|4018 seconds|7106 seconds

**Comment by puneet-oicr** [comment]
Still troubleshooting

**Comment by lindaxiang** [comment]
Based on the tests we had, we can conclude:
- HT ON has better performance vs. OFF on the new added nodes.
- WXS Aln with 24cpu/128GB for bwa took ~3 hours to complete whole job, ~1 hour for BWA step on the new added nodes. In theory, if we have resource reservation in place and the node is not overloaded, with 12 cpus request for bwa, it is estimated to be ~2h for bwa.
- Automation tests were all successful in Dev on the new added nodes.

We will do further tests when resource reservation in Dev/QA is in place.

**Comment by UmmulkiramR** [comment]
For reference, this is the summary of the runs on DEV.

```
1. RunId: wes-f45b9bbdd7754e83bd80a9fd264e9539
  Analysis: f77ce78b-3366-40c9-bce7-8b336630c9bd
  Params:
"bwaMemAligner": {
		"mem": 18,
		"cpus": 6
	}
  Status: WARN: K8s pod cannot be scheduled -- 0/21 nodes are available: 10 Insufficient cpu, 3 node(s) had taint {[node-role.kubernetes.io/ingress](http://node-role.kubernetes.io/ingress): }, that the pod didn't tolerate, 3 node(s) had taint {[node-role.kubernetes.io/master](http://node-role.kubernetes.io/master): }, that the pod didn't tolerate, 5 node(s) had taint {type: infra}, that the pod didn't tolerate. . Later the pods crashed
```

 ```
  2.  RunId: wes-64c3cea680874b4ebc25e3f56c02f397
   Analysis: dbe1ff4d-265e-42e2-a1ff-4d265ee2e202
   Params:
      "bwaMemAligner": {
		          "mem": 36,
		          "cpus": 8
	          } 

    Status: DnaAln:bwaMemAligner kept going for 3 days so we had to kill it.
```

```
 3. RunId: wes-50df2a9724e1488e82dcf41f318daedd
    Analysis: dbe1ff4d-265e-42e2-a1ff-4d265ee2e202 --Tumour
    Params:
"bwaMemAligner": {
		"mem": 36,
		"cpus": 32
	}
    Status: This one ran into a memory issue.
```

 ```
4. RunId: wes-0cf9b38a33594f19a4df2be4b4954f7e
   Analysis: 641afdc9-d14b-4c3b-9afd-c9d14bdc3b30  — Normal
  Params:
"bwaMemAligner": {
		"mem": 128,
		"cpus": 24
	}

  Status: Here HT was turned on and  bwaMemAligner took about 3 hours to finish.
```

We also had one trial with 32CPUs before this one but we reduced the CPUs to 24 after @henro001 
suggested that the nodes were getting overloaded.
