### ISSUE TITLE
Workflow Run Failure: Song to Clinical

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#3]
## Detailed Description
![image](https://user-images.githubusercontent.com/15824252/77321658-dfbadf80-6ce8-11ea-888b-ceee332ee2c3.png)

SONG_SERVER_ERROR[id.service.error @ 1584763365847]: [FederatedIdService::id.service.error] - The request 'GET https://clinical.qa.argo.cancercollaboratory.org/clinical/donors/id?programId=OCCAMS-GB&submitterId=OCCAMS-AH-011' failed with HttpStatus 'GATEWAY_TIMEOUT[504]' and message: 504 

When i try this endpoint i the above error I get this error:
(https://clinical.qa.argo.cancercollaboratory.org/clinical/donors/id?programId=OCCAMS-GB&submitterId=OCCAMS-AH-011) i get this `DO50325`

## List all runids affected
wes-5688e42dba324c9cb3db281d7d1080cc
wes-d00804f213bf4137a3df4b7e0f62a800
wes-273ac69209964a18bf4cb3bb7462593f
wes-1bed2b582ceb467584dffb1d30f792ad
wes-0a0f926bd8c246be949f8e679bc34933
wes-8d62f93bc8094db7b39dcf44f5a9e373
wes-f5ae7abd1527444b9017c69f3574c570
wes-ca91c9ead4ed4a409778b2837ab856a2
wes-563a66ccc1ab448995a764baf720d749
wes-a451bb3c064f4a98b0b6e6ebfa24205c

## Exit Criteria
- [ ]Problem is fixed
- [ ] Run is resumed

**Comment by rosibaj** [comment]
@lepsalex assigning to you to try resume!

**Comment by lepsalex** [comment]
Sounds good. I'm going to run a resume test on dev first.

**Comment by rosibaj** [comment]
closed as the timeout issue was a service upgrade issues
