### ISSUE TITLE
Workflow Run Failure - RNAseq Aln runs failed at song/score uploading steps in Prod

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#300]
### Type 1 Error
`
ERROR: Data transfer has been interrupted. Some parts are missing. Waiting to retry... Total execution time: 1.948 h Total bytes read : 0 Total bytes written : 133,083,242,090 ERROR: Command error: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://score.rdpc.cancercollaboratory.org/upload/1d9cd514-816b-51cb-a45d-122a4ea13ef4/parts": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
`

*List all runids affected*
### List all runids affected
- wes-aa947dae738a4973888deb417bab9dfe
- wes-8d446b69ad5d4ad78014675572e39adc
- wes-a7df92111d554e318b8658d0f34f7ac3
- wes-cc29c8a9ee654dfd8afa933e2bd68d6d

### Type 2 Error
`
ERROR: Command error: bio.overture.score.client.exception.RetryableException: java.io.IOException: Storage server error: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> 
`
### List all runids affected
- wes-27b84bfc6bec466ea28d78398d43cddf
- wes-f338619ebff14c7facea6b9e01c60196

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by b-f-chan** [comment]
Workflow is currently not using latest versions of Song/Score clients -> Trying upgrade first to see if that fixes these issues

**Comment by b-f-chan** [comment]
Plan for next week: Resume jobs, see if they go through Song/Score, then for new jobs/runs, use latest Song/Score modules to do a comparative analysis and see if same issues happen

**Comment by puneet-oicr** [comment]
Blocked until - https://github.com/icgc-argo/workflow-management/issues/209 is resolved

**Comment by b-f-chan** [comment]
Looks like @UmmulkiramR may have already fixed this, @lindaxiang to check and re-test

**Comment by UmmulkiramR** [comment]
This issue is not related to [icgc-argo/workflow-management#209](https://github.com/icgc-argo/workflow-management/issues/209).

**Comment by b-f-chan** [comment]
@UmmulkiramR implemented a resume function through Model T (UI already has this function) and after resuming the jobs they all completed successfully.  Additional @henro001 restarted almost all working nodes and seems the performance issues have disappeared, although root cause is still unclear and being investigated.  However, this ticket can be closed.
