### ISSUE TITLE
Investigate Extremely Slow Workflow Jobs in Prod

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#301]
Some POG-CA WGS and APGI RNA-Seq jobs are running extremely slow in prod, need to investigate, perhaps some resource allocation issue

@lindaxiang to provide more details if required, @henro001 @jmimico are already aware, this is just for tracking

**Comment by lindaxiang** [comment]
relating ticket: https://github.com/icgc-argo/infra-devops-roadmap/issues/171

**Comment by lindaxiang** [comment]
Henro has rebooted all working nodes. It seems to have effects,  most the resumed jobs are all completed in reasonable time. 
The following is the `cpus_number`/`real_time`/`cpu_time` stats for the tests
<img width="783" alt="Screen Shot 2023-01-06 at 11 03 18 AM" src="https://user-images.githubusercontent.com/7522294/211606200-35bad4d3-7ba9-4346-96da-918635aa4998.png">

Apparently cpu=12 has the best performance overall.

**Comment by puneet-oicr** [comment]
Prod is back to normal, benchmarking completed.
