### ISSUE TITLE
Feature Request - add support to execute workflow automation in batch

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#302]
## Detailed Description

Current implementation of workflow automation is listening the `PUBLISH` events across the song servers. Specifically the
- `PUBLISH` event in `submission-song` for: analysisType(`sequencing_experiment`) & experimental_strategy(`WGS` or `WXS`) will trigger the automated running of `DNA-Seq Alignment Workflow`. 
- Then all the downstream workflows will be auto-triggered when qualified song `PUBLISH` events happen. 

Ideally, this fully automation should work. However in the reality, there are many scenarios we want to have some level of human control over the jobs running due to following use cases:
- some of the submitted analysis may have data or quality issue, which are not ready for `DNA-Seq Alignment Workflow`. DCC will need to do some QC and sanity checks along with the data submitters. 
- due to the RDPC resource limit, we are not able to schedule all the jobs right after the raw data are submitted
- we need to prioritize the jobs runnings across different workflows due to various reasons. 

For the above reasons, we would like to request a feature which can support us to execute workflow running and automation in batch. 

## Possible Implementation

The followings are just some naive and preliminary thoughts:
1. Semi-automation
- Use Model-Tee as the batch submitter for starter workflow e.g., `DNA-Seq Alignment Workflow`
- All the downstream workflows can be auto-kicked off once the alignments are completed

2. Provide the user the capability to create a batch of jobs from the `QUEUE`
- All the jobs which are ready to be kicked off(triggered by song `publish` events and all qualified jobs in the past) can be put into somewhere like `Pre-QUEUE`
- Provide the user UI interface to create a batch of runnable jobs by flagging them
- Move the flagged jobs from `Pre-QUEUE` to `QUEUE`
- All the workflows starting from `DNA-Seq Alignment Workflow` will be auto-kicked off for the flagged jobs.

**Comment by lindaxiang** [comment]
FYI @Buwujiu , may need your help to fresh more details in terms of specifications.

**Comment by Buwujiu** [comment]
Nothing is blocked without this feature request, but would be nice to have more control over automation turn on/off. 
@Buwujiu Check with Melanie about priority.

**Comment by edsu7** [comment]
In discussions with bio-info and Melanie:
"Ready" flag is a priority, batch submission is a nice to have

**Comment by Buwujiu** [comment]
specs needed for the definition of ready flag. @Buwujiu

**Comment by Buwujiu** [comment]
As discussed with Linda, Edmund, and UK, we will let Model Tee trigger automation. This feature request is not needed anymore, closing.
