### ISSUE TITLE
Update User Documentation for Using the New Submission Workflow

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#306]
Need to update existing docs so users know how to run the new ARGO generalized submission workflow

Existing docs: https://docs.google.com/document/d/14crfWmOaCJ85kVgKtik9kVJQ-pTDud_iX04wbviFDj4/edit

**Comment by edsu7** [comment]
Documentation updated!

**Comment by edsu7** [comment]
@lindaxiang and @hknahal to review.
Xindi is currently testing workflow. To meet with MUTO-INTL to suggest testing.

**Comment by b-f-chan** [comment]
Asked @Buwujiu to start feature where we could filter runs by project

**Comment by lindaxiang** [comment]
Both Edmund and Linda have reviewed the Docs. Closing this.
