### ISSUE TITLE
Run QC on APGI RNA-Seq Data

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/workflow-roadmap#307]
Run QC on the ICGC25K data for APGI RNA-Seq

Placeholder ticket, @lindaxiang to fill in details and add sub-tasks to the epic

@edsu7 and @lindaxiang to work on this together to optimize time

**Comment by edsu7** [comment]
[Power point](https://docs.google.com/presentation/d/1fJ8E-3VZM0c50xowXyu_xi8VhsBgvEz5__s0GBr1HXA/edit#slide=id.g1d8d7cacd73_0_124)
[Metrics](https://docs.google.com/spreadsheets/d/1v_lFkPCcZsjGwI3OcsM_Nmo7_gyBYmiCT7oQDkPIPRg/edit#gid=1587824309)

[Previous benchmarking](https://docs.google.com/spreadsheets/d/1U7_t1oG2YvkUyilRYyZ3Q46BcZ4JY3IpYGwGuQa7saM/edit#gid=1480044150)

**Comment by edsu7** [comment]
Code will be generalized to be re-usable, see ticket:
https://github.com/icgc-argo/workflow-roadmap/issues/313

**Comment by lindaxiang** [comment]
Took a closer look at the QC measures collected, here are some observations:

 **Measures**|**TOTAL\_READS**|**DUPLICATION\_PCT**|**MAPPING\_PCT**|**pct\_coding\_bases**|**pct\_ribosomal\_bases**|**pct\_intergenic\_bases + pct\_intronic\_bases**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
Max|471649702|63.1|98.9|0.448528|2.45E-04|0.617675
Min|69990191|17.7|76.8|0.155363|0.00E+00|0.125889
Mean|167624155.7|31.5|95.1|0.333575157|2.37E-05|0.285719441
Median|151922392.5|30.9|96.9|0.3493255|1.10E-05|0.2685635
Reference Range|50-120M|30%-90%|>80%|>35%|<5%|<40%

Most measures are in the normal reference range, however `pct_coding_bases` is a bit low while `pct_intergenic_bases + pct_intronic_bases` is a bit high.

**Comment by lindaxiang** [comment]
Consulted the RNA-Seq WG and got some feedback:
- Raquel Manzano: Looking at those general number I wouldn’t be too concern. Maybe worth looking into the sample were the mapping was somehow low (76.8%), might be just low quality though. Overall looks okay.
- Andre Kahles: 
1. I would concur with Raquel, to have a look at the samples that map relatively few reads. That said, it often is a combination of measures. For instance, if the low mapping rate was at the sample with the max reads, the absolute number of mapped reads in that sample might still be well above average. So in the end I think it will come down to how the QC team decides to integrate these measures.
2. One more statistic I was thinking of when looking over the table. Are you also determining the fraction of covered exome? So not the percentage of exonic bases on read side, but the fraction of annotated positions that have at least 1 (or higher) coverage. This would give you a proxy for information content. Also - do you have the number of spliced alignments per sample?

**Comment by lindaxiang** [comment]
- Did a quick check for the sample with lower (76.8%) mapping rate, that’s Hisat2 aligner (# mapped reads is 132M), while Star has 87.3% mapping rate for the same sample (# mapped reads is 164M), so both are way higher above average.

- Regarding number of spliced alignments per sample, here are the alignment log files from both Star and Hisat2. 
[SA528768_hisat2_align.log](https://github.com/icgc-argo/workflow-roadmap/files/10538299/SA528768_hisat2_align.log)
[SA528768_star_align.final.log](https://github.com/icgc-argo/workflow-roadmap/files/10538300/SA528768_star_align.final.log)

**Comment by lindaxiang** [comment]
This is Star log
```
                                 Started job on |       Jan 09 18:55:04
                             Started mapping on |       Jan 09 19:44:09
                                    Finished on |       Jan 09 23:06:17
       Mapping speed, Million of reads per hour |       31.62

                          Number of input reads |       106529910
                      Average input read length |       202
                                    UNIQUE READS:
                   Uniquely mapped reads number |       70035470
                        Uniquely mapped reads % |       65.74%
                          Average mapped length |       180.57
                       Number of splices: Total |       16187634
            Number of splices: Annotated (sjdb) |       16109705
                       Number of splices: GT/AG |       15901667
                       Number of splices: GC/AG |       219799
                       Number of splices: AT/AC |       31158
               Number of splices: Non-canonical |       35010
                      Mismatch rate per base, % |       1.14%
                         Deletion rate per base |       0.01%
                        Deletion average length |       1.80
                        Insertion rate per base |       0.01%
                       Insertion average length |       1.47
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |       31446776
             % of reads mapped to multiple loci |       29.52%
        Number of reads mapped to too many loci |       2116949
             % of reads mapped to too many loci |       1.99%
                                  UNMAPPED READS:
  Number of reads unmapped: too many mismatches |       0
       % of reads unmapped: too many mismatches |       0.00%
            Number of reads unmapped: too short |       2704835
                 % of reads unmapped: too short |       2.54%
                Number of reads unmapped: other |       225880
                     % of reads unmapped: other |       0.21%
                                  CHIMERIC READS:
                       Number of chimeric reads |       0
                            % of chimeric reads |       0.00%
```

**Comment by lindaxiang** [comment]
This is Hisat2 log:
```
HISAT2 summary stats:
        Total pairs: 26610468
                Aligned concordantly or discordantly 0 time: 8869613 (33.33%)
                Aligned concordantly 1 time: 4014909 (15.09%)
                Aligned concordantly >1 times: 13636207 (51.24%)
                Aligned discordantly 1 time: 89739 (0.34%)
        Total unpaired reads: 17739226
                Aligned 0 time: 9928306 (55.97%)
                Aligned 1 time: 3725896 (21.00%)
                Aligned >1 times: 4085024 (23.03%)
        Overall alignment rate: 81.35%
Time searching: 02:49:59
Overall time: 02:50:10
Time loading forward index: 00:00:07
Time loading reference: 00:00:01
Multiseed full-index search: 02:50:56
HISAT2 summary stats:
        Total pairs: 26855719
                Aligned concordantly or discordantly 0 time: 9876632 (36.78%)
                Aligned concordantly 1 time: 3607929 (13.43%)
                Aligned concordantly >1 times: 13285879 (49.47%)
                Aligned discordantly 1 time: 85279 (0.32%)
        Total unpaired reads: 19753264
                Aligned 0 time: 10981485 (55.59%)
                Aligned 1 time: 4165973 (21.09%)
                Aligned >1 times: 4605806 (23.32%)
        Overall alignment rate: 79.55%
Time searching: 02:50:59
Overall time: 02:51:06
Time loading forward index: 00:00:08
Time loading reference: 00:00:01
Multiseed full-index search: 03:06:32
HISAT2 summary stats:
        Total pairs: 26558695
                Aligned concordantly or discordantly 0 time: 8252535 (31.07%)
                Aligned concordantly 1 time: 4485181 (16.89%)
                Aligned concordantly >1 times: 13725942 (51.68%)
                Aligned discordantly 1 time: 95037 (0.36%)
        Total unpaired reads: 16505070
                Aligned 0 time: 9236424 (55.96%)
                Aligned 1 time: 3521901 (21.34%)
                Aligned >1 times: 3746745 (22.70%)
        Overall alignment rate: 82.61%
Time searching: 03:06:35
Overall time: 03:06:44
Time loading forward index: 00:00:08
Time loading reference: 00:00:01
Multiseed full-index search: 04:12:02
HISAT2 summary stats:
        Total pairs: 26505028
                Aligned concordantly or discordantly 0 time: 8940814 (33.73%)
                Aligned concordantly 1 time: 3945367 (14.89%)
                Aligned concordantly >1 times: 13527442 (51.04%)
                Aligned discordantly 1 time: 91405 (0.34%)
        Total unpaired reads: 17881628
                Aligned 0 time: 9972707 (55.77%)
                Aligned 1 time: 3826061 (21.40%)
                Aligned >1 times: 4082860 (22.83%)
        Overall alignment rate: 81.19%
```

**Comment by lindaxiang** [comment]
- Star alignment: APGI-AU.DO49172.SA528768.rna-seq.20230110.star.genome_aln.cram (analysis [1bb45d55-30ca-4d77-b45d-5530ca8d773f](https://song.rdpc.cancercollaboratory.org/studies/APGI-AU/analysis/1bb45d55-30ca-4d77-b45d-5530ca8d773f))
Star Aln: `the fraction of spliced primary alignments`:  23485183 / 188969058 = 12.4%

- Hisat2 alignment: APGI-AU.DO49172.SA528768.rna-seq.20230109.hisat2.genome_aln.cram (analysis [32e7771b-5cf8-4443-a777-1b5cf87443fd](https://song.rdpc.cancercollaboratory.org/studies/APGI-AU/analysis/32e7771b-5cf8-4443-a777-1b5cf87443fd)
Hisat2 Aln: `the fraction of spliced primary alignments`:  36835150/ 172940898 = 21.3%

**Comment by lindaxiang** [comment]
Closing this
