### ISSUE TITLE
Increase bandwidth for running WGS alignment jobs on RDPC-Prod through configuration

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#308]
We still have ~400+ WGS alignment jobs to run for POG-CA, can we temporarily increase the max allowable # of jobs which can be ran in parallel, so that we can increase the throughput of the jobs running in Prod.

**Comment by lindaxiang** [comment]
Currently the [prod setting](https://github.com/icgc-argo/rdpc-infra/blob/develop/helm/management-scheduler/prod/values.yaml#L42) allows max `8` DNAseq WGS alignment jobs to run in parallel, since we only have DNAseq WGS aln jobs to run, can we temporarily increase the number to `16`?

**Comment by UmmulkiramR** [comment]
Have updated max total runs for both dna-seq and sanger WGS.

**Comment by Buwujiu** [comment]
Config change, can close now.
