### ISSUE TITLE
🐛 The configs for max number of parallel running jobs are not in effect

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#310]
## Describe the bug
Relating to [issue](https://github.com/icgc-argo/workflow-roadmap/issues/308), although @UmmulkiramR has made changes to configuration files, the number of parallel running jobs is limited to `7` in Prod. 

Confirmed by @henro001  that the cluster has enough resource to run more jobs in parallel, but the kafka did not receive the job starting messages, so need to investigate the reason why only 7 jobs (not the configured 16) can be running in parallel in Prod.

## Expected behaviour
Max number of parallel running jobs is the configured number.

**Comment by UmmulkiramR** [comment]
This issue is resolved now.

**Comment by Buwujiu** [comment]
Issue is resolved, Linda has confirmed, closing.
