### ISSUE TITLE
Workflow Run Failure - Score-client uploading takes 24+ hours and failed in the end

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#311]
## Detailed Description

Score-client uploading takes 24+ hours and failed in the end.
Error messages will be attached. 

## List all runids affected
wes-d2552cedb966414597434e7ae1360a2f
wes-0f955d3b625a4c5e836db34460a19948

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by puneet-oicr** [comment]
UK and Aditya working on this

**Comment by UmmulkiramR** [comment]
@henro001 and @jmimico are working on this. 
As confirmed by @lindaxiang, this issue is related to [issue 324](https://github.com/icgc-argo/workflow-roadmap/issues/324)

**Comment by UmmulkiramR** [comment]
[Issue 324](https://github.com/icgc-argo/workflow-roadmap/issues/324) has been resolved. We can close this ticket as well.
