### ISSUE TITLE
Generalize code for plots regarding RDPC stats

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#312]

**Comment by b-f-chan** [comment]
Move to new generic Bioinfo repo @edsu7

**Comment by edsu7** [comment]
PR: https://github.com/gi-bioinfo/Molecular-QC-measures-reporting/pull/1

**Comment by puneet-oicr** [comment]
PR ready for review

**Comment by puneet-oicr** [comment]
no updates, BioInfo to review, not urgent though
