### ISSUE TITLE
switch of payload generation tool for QC metrics

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#316]
wfpm version: https://github.com/icgc-argo-workflows/data-processing-utility-tools/tree/main/payload-gen-qc

**Comment by puneet-oicr** [comment]
PR pending post a few changes.

**Comment by lindaxiang** [comment]
New nf-core implementation: https://github.com/icgc-argo-workflows/argo-modules/tree/main/modules/icgc-argo-workflows/payload/qcmetrics

**Comment by lindaxiang** [comment]
update the module with PR: https://github.com/icgc-argo-workflows/argo-modules/pull/21

**Comment by lindaxiang** [comment]
Closing this issue and open an update ticket: https://github.com/icgc-argo/argo-data-submission/issues/92
