### ISSUE TITLE
QC pipeline Dev - pre alignment QC workflow in nf-core framework

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#317]
wfpm version: https://github.com/icgc-argo-workflows/pre-alignment-qc

**Comment by puneet-oicr** [comment]
In progress, partly completed

**Comment by puneet-oicr** [comment]
Ongoing work.

**Comment by puneet-oicr** [comment]
Implementation complete. Documentation pending. PR to be created soon.

**Comment by lindaxiang** [comment]
New git repo: https://github.com/icgc-argo-workflows/prealnqc

**Comment by edsu7** [comment]
Test on RDPC. Dependency on up to date nextflow ver.
https://github.com/icgc-argo/workflow-management/issues/196

**Comment by lindaxiang** [comment]
Test the workflow in RDPC-QA and got an issue: https://github.com/icgc-argo/workflow-roadmap/issues/388

**Comment by lindaxiang** [comment]
Test the workflow in RDPC-QA and completed successfully:
https://wes.rdpc-qa.cancercollaboratory.org/runs/wes-c6f9a8842bcd48c4a5430384f6fb8e98

**Comment by lindaxiang** [comment]
Next steps:

- [x] - update the payload/qcmetrics module ([updated module PR is under review](https://github.com/icgc-argo-workflows/argo-modules/pull/21)) and make PR after. 
- [x] - depend on payload schema change: https://github.com/icgc-argo/argo-metadata-schemas/issues/78
- [x] - test it in cumulus rdpc

**Comment by justincorrigible** [comment]
Closing as Done
