### ISSUE TITLE
Documentation on doc site

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#318]
- [x] add new section of `RNA-Sequencing Analysis Pipeline` to `analysis overview` page: https://docs.icgc-argo.org/docs/analysis-workflows/analysis-overview
- [x] create `RNA-SEQ ANALYSIS` tab on the facet
- [x] Add `RNA-Seq Alignment` page
- [x] Update `Data and File Types`
- [x] Update `Release Notes` - Data Release

**Comment by b-f-chan** [comment]
For Data Release 6.0
