### ISSUE TITLE
Prod runs states are not back to normal due to `Collab` down

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#319]
All the jobs failed due to the Collab down during the weekend, but their states are still RUNNING from UI.

@UmmulkiramR is investigating the issue, and here is the reason she found:
When the collab went down these pods went into error. But since everything was down (services, kafka, etc) the communication link between all was lost . The failure state never got communicated back and the ES never got updated with it.

The raccoon service is supposed to restore the states of the runs, however it did not do the trick due to some reason. Therefore UK is still doing some deep investigation.

**Comment by Buwujiu** [comment]
Issue resolved, will close ticket.
