### ISSUE TITLE
Rollout Kubernetes Secrets solution for Workflows

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-roadmap#32]
Workflow Management and the Song/Score nextflow tools have been updated:
- https://github.com/icgc-argo/workflow-roadmap/issues/30
- https://github.com/icgc-argo/workflow-management/issues/98

Steps:
- [x] Produce a new tagged version of our workflows using updated song/score processes
- [x] Updated helm values for Workflow Management in dev, qa, prod with run profile set to `apiKey` and providing a base64 encoded access token
- [x] Deploy updated version of workflow management with new values.

**Comment by rosibaj** [comment]
@andricDu @lepsalex i beleive this is done?

**Comment by lepsalex** [comment]
yes
