### ISSUE TITLE
Object Storage Data cleanup in Prod

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#320]
During data processing in RDPC Prod, whenever the jobs failed in between, it has the potential to send lots of temporary files to object store which we need to clean them up due the following reasons:
- each resumed job has different runId
- payload generation requires runId as one of the inputs
- all the payload-gen/song/score uploading are to be re-run during the resume process

Therefore, we should regularly generate reports for all failed runs and their uploaded objects
- `published` analysis: delete relating objects + suppress analysis
- `unpublished` analysis: delete relating objects if existing

**Comment by puneet-oicr** [comment]
Unpublished coding completed.

**Comment by puneet-oicr** [comment]
No new updates

**Comment by puneet-oicr** [comment]
Script complete. PR branch to be created

**Comment by lindaxiang** [comment]
Not needed atm.
