### ISSUE TITLE
Workflow Run Failure - `DnaAln:toLaneBam`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#321]
## Detailed Description

Runs failed at step `DnaAln:toLaneBam`, need some further investigation to see if the submitted data has some data issue. 

## List all runids affected
wes-a12fdc8a722741fda49d115b1510b201
wes-c9fad2e9fa044803a6a7717ed283d2ab

## Approach to address this
- QC the data using samtools
- Run the same process `toLaneBam` on the data on a VM

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by lindaxiang** [comment]
Did some QC for input file from runId: wes-a12fdc8a722741fda49d115b1510b201
Input analysis: https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/b2e82716-3d61-49c6-a827-163d61f9c66d
Input file: P00073_8_lanes_dupsFlagged.reheadered.bam
1. samtools flagstat
```
samtools flagstat P00073_8_lanes_dupsFlagged.reheadered.bam
[E::bgzf_uncompress] Inflate operation failed: progress temporarily not possible, or in() / out() returned an error
[E::bgzf_read] Read block operation failed with error 1 after 0 of 4 bytes
[bam_flagstat_core] Truncated file? Continue anyway.
1961638600 + 131099733 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
3865977 + 527037 supplementary
54675789 + 11567908 duplicates
1944335364 + 112682957 mapped (99.12% : 85.95%)
1957772623 + 130572696 paired in sequencing
978916955 + 65276757 read1
978855668 + 65295939 read2
1895340188 + 89223622 properly paired (96.81% : 68.33%)
1923166151 + 93739144 with itself and mate mapped
17303236 + 18416776 singletons (0.88% : 14.10%)
15199951 + 3774860 with mate mapped to a different chr
8528048 + 1898726 with mate mapped to a different chr (mapQ>=5)
```
2. run the samtools split for the input file
```
samtools split -f 'P00073_8_lanes_dupsFlagged.reheadered/%!.bam' -@ 4 P00073_8_lanes_dupsFlagged.reheadered.bam 

[E::bgzf_read_block] Invalid BGZF header at offset 161634073451
[E::bgzf_read] Read block operation failed with error 6 after 0 of 4 bytes
samtools split: Could not read input record
```
It looks like there are some data issue of the submitted files. 

Nextstep
- May worth to use `seq-tools` to validate the submitted file so as to make sure the submission workflow can capture the errors before they were submitted to RDPC.

**Comment by edsu7** [comment]
For analysis: `b2e82716-3d61-49c6-a827-163d61f9c66d` and `6601cda9-45b5-4a68-81cd-a945b5ea6885`

Performed the following tests:
- [samtools quickcheck](http://www.htslib.org/doc/samtools-quickcheck.html) - okay but only checks header and EOF
- [samtools flagstat](http://www.htslib.org/doc/samtools-flagstat.html) - same findings as linda
```
[E::bgzf_read] Read block operation failed with error -1 after 0 of 4 bytes
[bam_flagstat_core] Truncated file? Continue anyway.
2736226737 + 325286530 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
5686980 + 1388185 supplementary
86715373 + 31458434 duplicates
2707776136 + 279013148 mapped (98.96% : 85.77%)
2730539757 + 323898345 paired in sequencing
1365259987 + 161948507 read1
1365279770 + 161949838 read2
2635172926 + 221246886 properly paired (96.51% : 68.31%)
2673638555 + 231351581 with itself and mate mapped
28450601 + 46273382 singletons (1.04% : 14.29%)
24656886 + 8626363 with mate mapped to a different chr
14500037 + 4029183 with mate mapped to a different chr (mapQ>=5)
```
 - [Picard SamFileValidate](https://gatk.broadinstitute.org/hc/en-us/articles/360036854731-ValidateSamFile-Picard-) - failed but identified reason isn't related to the initial problems.
```
## HISTOGRAM    java.lang.String
Error Type      Count
ERROR:MATE_NOT_FOUND    6968504
```
 - Md5sum was also okay.

Suggests problem is in the body of the file and was corrupted at data submitter's side.

**Comment by edsu7** [comment]
I found this [post](https://gatk.broadinstitute.org/hc/en-us/community/posts/360074728152-Truncated-bam-file-after-running-ReplaceSamHeader-Picard-) which may link the two observations (failing processing) and (missing mates)

Specifically this [comment](https://gatk.broadinstitute.org/hc/en-us/community/posts/360074728152/comments/360013559412)
where reheadering caused certain reads to lose “context” b/c they were mapped to chromosome/sccafold no longer present in the header.

Steve has been informed.

**Comment by puneet-oicr** [comment]
Action - Data to be resubmitted. Old files will be suppressed once new are submitted.

**Comment by edsu7** [comment]
Old files have been unpublished. Steve is working to upload new batch.

**Comment by edsu7** [comment]
Steve confirmed successful upload, new analysis IDs : `3e1c86b4-a2d5-4881-9c86-b4a2d5a88175` and `00c5b595-96e7-4e12-85b5-9596e7ae125c`

**Comment by edsu7** [comment]
`3e1c86b4-a2d5-4881-9c86-b4a2d5a88175` corresponds to `b2e82716-3d61-49c6-a827-163d61f9c66d`
and
`00c5b595-96e7-4e12-85b5-9596e7ae125c` corresponds to `6601cda9-45b5-4a68-81cd-a945b5ea6885`
Both pass previous checks : flagstat and quickcheck

**Comment by puneet-oicr** [comment]
More affected runs to be added @lindaxiang

**Comment by lindaxiang** [comment]
Here are more analysis from `POG-CA` in Prod which have the same issue:

**sample**|**study**|**analysis\_id**|**runId**
:-----:|:-----:|:-----:|:-----:
SA613327|POG-CA|e2460bd1-4217-4d58-860b-d14217dd583f|wes-371fb5a15dab4626ac509124d7d7fe68
SA613225|POG-CA|313df7b5-12a8-4ef4-bdf7-b512a8aef485|wes-f15f722d99024e609b838a28c3b48a38
SA613224|POG-CA|45dddbe5-7004-469e-9ddb-e57004f69e27|wes-af37ebdf5ff743bb887b1982f10d5bae
SA613241|POG-CA|152dedfc-02f9-4015-aded-fc02f93015cf|wes-5ea4b695eb584067a5f045c130e6816f
SA613301|POG-CA|fb30f6c9-f24f-4547-b0f6-c9f24fc54719|wes-922cc5e032cd4503986d60c53104de50
SA613307|POG-CA|56f84713-6196-4ba5-b847-1361968ba54d|wes-d31c9f672c914821a2a55d26916bf6a3
SA613229|POG-CA|a7f9d8e4-c23a-4e66-b9d8-e4c23a0e663b|wes-27e4f878c0f7460cbec7009e2fadceae

**Comment by puneet-oicr** [comment]
Data is corrupted. Steve has been notified

**Comment by puneet-oicr** [comment]
No response yet

**Comment by puneet-oicr** [comment]
This ticket is only for tracking information

**Comment by edsu7** [comment]
Steve has resubmitted data for the following samples. The new analyses have been rechecked and look good. The old analyses have been suppressed.

**submitter sample**|**sampleid**|**old analysis_id**|**new analsis_id**
:-----:|:-----:|:-----:|:-----:
|P00549|SA613327|e2460bd1-4217-4d58-860b-d14217dd583f|ea9280f5-704e-419c-9280-f5704e019c13
|P00741|SA613225|313df7b5-12a8-4ef4-bdf7-b512a8aef485|479f0112-b40b-4205-9f01-12b40b420553
|P00699|SA613224|45dddbe5-7004-469e-9ddb-e57004f69e27|45d1a31a-aefb-406c-91a3-1aaefbd06c37
|P00732|SA613241|152dedfc-02f9-4015-aded-fc02f93015cf|12e6ca68-efb7-4c21-a6ca-68efb7fc21d9
|P00761|SA613301|fb30f6c9-f24f-4547-b0f6-c9f24fc54719|5f62d9e0-c828-4f68-a2d9-e0c828df6828
|P00806|SA613307|56f84713-6196-4ba5-b847-1361968ba54d|c723f980-37d2-43a1-a3f9-8037d263a164
|P00860|SA613229|97f6751d-1c26-4d2d-b675-1d1c26ad2dac|6638e0dd-234a-4ed8-b8e0-dd234a6ed874

**Comment by puneet-oicr** [comment]
Waiting for more samples to fail, so we can track all samples with issues.

**Comment by lindaxiang** [comment]
More samples with the same issue:

**sample\_id**|**study\_id**|**analysis\_id**|**work\_dir**|**run\_id**
:-----:|:-----:|:-----:|:-----:|:-----:
SA613270|POG-CA|183ddc83-1a51-4455-bddc-831a514455b9|/nfs-3-c1/work|wes-61df38a1208c49dd8fa090a07702acb6
SA613081|POG-CA|b6c5882b-3f88-4931-8588-2b3f88593129|/nfs-2-c1/work|wes-f989a4d0861942289eab7553f2cdc22f

**Comment by puneet-oicr** [comment]
No updates. Linda ran a few more. Need to connect with Steve on this.

**Comment by edsu7** [comment]
Edmund will prescreen files to expedite data failure tracking.

**Comment by edsu7** [comment]
Screened files found the following:
```
183ddc83-1a51-4455-bddc-831a514455b9
b158b5a0-3968-4679-98b5-a0396896799c
b6c5882b-3f88-4931-8588-2b3f88593129
```

Two additional objects could not be downloaded. Tracked in 
https://github.com/icgc-argo/workflow-roadmap/issues/345

**Comment by edsu7** [comment]
IDs have been unpublished and Steve has been notified

**Comment by edsu7** [comment]
Closing. If this reappears will open another ticket.
