### ISSUE TITLE
RDPC workDirs cleanup

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#322]
With more and more jobs running in Prod, all workDirs have accumulated a lot of temporary / garbage data which need to cleanup regularly. 

Before we do the cleanup the history, it's better to audit all the failed jobs which are able to be resumed.  
The jobs failed at score-upload step are recorded in ticket: https://github.com/icgc-argo/workflow-roadmap/issues/324

**Comment by lindaxiang** [comment]
Here is the list of workDirs which contain the failed jobs which we will leave them untouched for now
```
/nfs-1-c4/work
/nfs-2-c1/work
/nfs-2-c2/work
/nfs-3-c1/work
/nfs-3-c2/work
/nfs-3-c3/work
/nfs-4-c2/work
```
The other workDirs will be cleanup.

**Comment by lindaxiang** [comment]
Here is the current stats getting from Grafana, the last column is the action to do. 

**Series**|**Time**|**Value**|**Action**
:-----:|:-----:|:-----:|:-----:
nfs-1: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T10:43:43-05:00|21.290927|to-remove
nfs-3: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T10:46:39-05:00|24.458344|to-remove
nfs-1: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T10:46:19-05:00|28.469778|hold
nfs-3: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T10:46:38-05:00|28.791274|hold
nfs-4: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T10:43:57-05:00|29.17872|to-remove
nfs-2: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T10:45:19-05:00|30.05046|hold
nfs-4: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T10:43:55-05:00|33.288168|to-remove
nfs-3: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T10:43:30-05:00|35.686586|hold
nfs-2: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T10:45:18-05:00|36.501112|to-remove
nfs-2: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T10:43:08-05:00|40.591028|hold
nfs-3: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T10:46:38-05:00|40.781281|hold
nfs-1: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T10:46:18-05:00|53.652929|to-remove
nfs-2: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T10:45:20-05:00|56.929137|to-remove
nfs-4: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T10:43:56-05:00|59.950705|to-remove
nfs-4: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T10:43:58-05:00|65.074663|hold
nfs-1: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T10:42:46-05:00|69.740118|to-remove

**Comment by lindaxiang** [comment]
Here is the stats after most workDirs cleanup

**Series**|**Time**|**Value**|**Note**
:-----:|:-----:|:-----:|:-----:
nfs-2: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T13:15:18-05:00|98.959182|Removed
nfs-4: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T13:13:55-05:00|98.959137|Removed
nfs-4: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T13:13:57-05:00|98.958069|Removed
nfs-1: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T13:16:18-05:00|98.957622|Removed
nfs-1: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T13:13:43-05:00|98.957082|Removed
nfs-1: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T13:17:46-05:00|98.955118|Removed
nfs-3: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T13:16:39-05:00|98.805304|Removed
nfs-2: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T13:15:20-05:00|98.803439|Removed
nfs-4: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T13:13:56-05:00|98.682454|Removed
nfs-4: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T13:13:58-05:00|65.074663|Hold
nfs-3: Free disk space on /nfs/vol-3 (percentage)|2023-02-06T13:16:37-05:00|40.780733|Hold
nfs-2: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T13:18:08-05:00|40.591028|Hold
nfs-3: Free disk space on /nfs/vol-1 (percentage)|2023-02-06T13:13:30-05:00|35.686586|Hold
nfs-2: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T13:15:19-05:00|30.05046|Hold
nfs-3: Free disk space on /nfs/vol-2 (percentage)|2023-02-06T13:16:38-05:00|28.791274|Hold
nfs-1: Free disk space on /nfs/vol-4 (percentage)|2023-02-06T13:16:19-05:00|28.469778|Hold

**Comment by lindaxiang** [comment]
All workDir in Prod have been cleanup in RDPC on June19, 2023. 
This ticket can be closed now.

**Comment by justincorrigible** [comment]
close as completed
