### ISSUE TITLE
Workflow Run Failure - Score upload errors

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#324]
## Detailed Description

Runs failed at step `DnaAln:upAln:scoreUp`, all had the similar following two types of errors:
- `Finalizing... ERROR: Data transfer has been interrupted. Some parts are missing. Waiting to retry... Total execution time: 1.419 h Total bytes read : 0 Total bytes written : 260,421,673,432 ERROR: Command error: java.io.IOException: Storage server error: {"timestamp":"2023-02-03T16:31:02.306+0000","status":503,"error":"Service Unavailable","message":"com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: tx0000013b1867e0923b045-0063dd36c6-2110c7d6-default; S3 Extended Request ID: 2110c7d6-default-default), S3 Extended Request ID: 2110c7d6-default-default","path":"/upload/be419423-b1ee-5e63-b103-cecebf97a143"}`
- `Finalizing... ERROR: Data transfer has been interrupted. Some parts are missing. Waiting to retry... Total execution time: 9.290 h Total bytes read : 0 Total bytes written : 1,068,595,133,038 ERROR: Command error: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://score.rdpc.cancercollaboratory.org/upload/da9a11ed-5e50-5870-947f-9884deb11d23/parts": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Please check the log for detailed error messages `

## List all runids affected
wes-955f7e2e769b4cac9097d3b480548a76
wes-f06963561569447bb0f3c2512e7be2a0
wes-d5deb46f3fcb4b2eb533a1463508de64
wes-f5356915a6c342a99244839b7beb0f47
wes-c5d53a23f1b2484dadd29aa745f58394
wes-a5d0b27bdd58494bae0c1e6be6b5c583

## Approach to address this
Need developer's help to debug the Score server/client tool. 

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by lindaxiang** [comment]
Thanks to @jmimico , he did some investigation
 runId: [wes-d5deb46f3fcb4b2eb533a1463508de64](https://wes.rdpc.cancercollaboratory.org/runs/wes-d5deb46f3fcb4b2eb533a1463508de64)
 output analysis: [ecbe5041-fe9d-4be2-be50-41fe9d7be21e](https://song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/ecbe5041-fe9d-4be2-be50-41fe9d7be21e)
 output object: `be419423-b1ee-5e63-b103-cecebf97a143`
```
"objectId": "be419423-b1ee-5e63-b103-cecebf97a143",
"studyId": "POG-CA",
"analysisId": "ecbe5041-fe9d-4be2-be50-41fe9d7be21e",
"fileName": "POG-CA.DO252242.SA613397.wgs.20230203.aln.cram",
"fileSize": 260421673432,
"fileType": "CRAM",
"fileMd5sum": "f749cc76ce64f6021c356ed659422017",
```
Jared found that both fileSize and md5sum match, so this looks like a good upload despite the error at the end.
fileSize: 
```
2023-02-03 16:29 260421673432 s3://icgc-argo-collab/data/be419423-b1ee-5e63-b103-cecebf97a143`
```
md5sum:
```
ubuntu@download-tester:~$ md5sum be419423-b1ee-5e63-b103-cecebf97a143
f749cc76ce64f6021c356ed659422017  be419423-b1ee-5e63-b103-cecebf97a143
```

**Comment by lindaxiang** [comment]
The workDir for the above run declared was `/nfs-4-c2`, however the files are mounted to `nfs-3/vol-3`
```
ls -la nfs-3/vol-3/work/ce/3e4a4a0fb856eafe05b29f6a6f7b0c/*.cram
-rw-r--r-- 1 9999 nfs 278980327691 Jan 12 21:10 nfs-3/vol-3/work/ce/3e4a4a0fb856eafe05b29f6a6f7b0c/grch38-aligned.merged.cram
```
fileSize is `278980327691` which matches with what Jared calculated in the objectstore.

**Comment by mcourtot** [comment]
@puneet-oicr @Buwujiu this has become a blocker for the bionfo team and we anticipate will soon impact planned submissions - can we please up prioritize?

**Comment by henro001** [comment]
test uploads in prod now consistently fail with 404, looking at the event log, seems like the objectd is deleted and then there is GET but the object no longer exists

```
Feb 14, 2023 @ 14:20:47.694	404	GET /icgc-argo-collab.state/upload/be419423-b1ee-5e63-b103-cecebf97a143_2~uRYMJ6Ew9VJM_OrYgFTXkSLSGCfCde3/.meta HTTP/1.1
Feb 14, 2023 @ 14:19:52.267	204	DELETE /icgc-argo-collab.state/upload/be419423-b1ee-5e63-b103-cecebf97a143_2~uRYMJ6Ew9VJM_OrYgFTXkSLSGCfCde3/.meta HTTP/1.1
```

**Comment by UmmulkiramR** [comment]
For the 'NoSuchKey' issue: 
The final step of the upload command deletes all the uploaded parts of the file. But while the finalizing of the uploaded parts is still in progress the score-client keeps retrying the the API call to the score-server. This is when the ‘404 NoSuchKey’ response is returned from Amazon S3. This has been handled now as a ‘404 NoSuchKey’ at this stage indicates the parts have been or are being deleted which is what the method is supposed to do.
This fix is on production now so a retried call to the finalize api will not return this exception anymore.

**Comment by Buwujiu** [comment]
The problem has 2 issues:
1. Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;
2. PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
The fix for point 1 is on prod (comment added on the ticket),
Jared and Henro is investigating issue 2.

**Comment by UmmulkiramR** [comment]
As @lindaxiang confirmed, after the fix for 1 - NoSuchKey went to prod, there has been no occurrence of the issue 2 - SunCertPathBuilderException. 
We'll keep monitoring the situation for the next few days and keep this ticket open for now.

**Comment by Buwujiu** [comment]
issue is fixed, will close it now!
