### ISSUE TITLE
Investigation - customize nfcore/sarek pipeline for ARGO usage

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#328]
As we are working to switch to use nf-core framework to structure ARGO workflows, we can take the following two routes:
1. convert the existing ARGO workflows to nf-core framework by following the guideline to reuse nf-core modules/subworkflows
2. customize the existing nf-core pipelines by adding/creating ARGO specific modules 

[nfcore/sarek](https://github.com/nf-core/sarek) is an open-source workflow to detect germline variants and somatic mutations based on sequencing data from WGS, WXS, or gene panels. The [google sheet](https://docs.google.com/spreadsheets/d/1v9Nh-AUWNxyBQTic6oDwD4X8fl6m2Ek6XjfPjxrrRFM/edit?usp=sharing) summarizes the features of nfcore/sarek pipeline, and compared with ARGO workflows. 

This ticket will investigate the difficulty and estimate the efforts required for taking route #2

**Comment by puneet-oicr** [comment]
Linda and Edmund to decide how to repurpose the ticket

**Comment by puneet-oicr** [comment]
To be changed to an epic

**Comment by puneet-oicr** [comment]
Delayed due to troubleshooting complexity

**Comment by puneet-oicr** [comment]
Still investigating

**Comment by justincorrigible** [comment]
Closing as completed.
