### ISSUE TITLE
Investigation - gather technical gaps to support tumour-only targeted sequencing raw data submission and process

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#329]
In order to evaluate the cost-effectiveness to help us to prioritize the work so as to support tumour-only targeted sequencing data submission and process, we will need to analyze the impacts from the following aspects:
- [x] 1. gather stats of programs/donors which have targeted sequencing data
- [ ] 2. changes to clinical data model and validation
- [x] 3. changes to molecular data module and validation
- [x] 4. changes to molecular data submission workflow
- [ ] 5. analysis workflows development

**Comment by lindaxiang** [comment]
https://docs.google.com/document/d/1TcHswu3bbgc-qXGnjsXjCUqOvDbT7aPJPaEIvUSfmlM/edit?usp=sharing

**Comment by puneet-oicr** [comment]
Workflows to be tested

**Comment by puneet-oicr** [comment]
No new updates, investigation pending

**Comment by lindaxiang** [comment]
Items 3 and 4 will be covered by Epic: https://github.com/icgc-argo/workflow-roadmap/issues/369

**Comment by lindaxiang** [comment]
item 2 need to create dedicated epic to implement changes to core completion rule.
item 5 need to create dedicated epic to implement analysis workflow.

once follow up tickets are created, this investigating ticket can be closed.

**Comment by lindaxiang** [comment]
Core completion rule ticket: https://github.com/icgc-argo/roadmap/issues/1063
Analysis workflow ticket: https://github.com/icgc-argo/workflow-roadmap/issues/402
