### ISSUE TITLE
Remove metrics from SONG payload

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#330]
As per discussions with DCWMG, it was deemed safer to remove ASCAT and mutect related info from payloads, see :
https://docs.google.com/spreadsheets/d/1JeDsoVBSr9KWe_B6nbMVdqUoYQo-hiHU19BvFfGIFd0/edit#gid=0

Testing in QA
- [x] Identify analyses
- [ ] Migrate analyses to latest schema
- [ ] Remove

Run in Prod
- [x] Identify analyses
- [x] Migrate analyses to latest schema
- [x] Remove

**Comment by puneet-oicr** [comment]
Data ready to be tested in QA. If successful, Edmund will run the workflow in prod.

**Comment by edsu7** [comment]
Deployed in prod:
[example](https://song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/011047cd-0221-43b0-9047-cd022153b029)

List of IDs altered:
[https://app.zenhub.com/files/247987212/03e1aee6-a0d7-4a17-a6ba-bb639a279523/download](https://app.zenhub.com/files/247987212/03e1aee6-a0d7-4a17-a6ba-bb639a279523/download)

PR for script:
https://github.com/gi-bioinfo/wes-run-auditing/pull/2

**Comment by edsu7** [comment]
Closing as issue has been completed
