### ISSUE TITLE
🐛 Score-client downloading fails. 

### ISSUE THREAD

**Issue by UmmulkiramR** [icgc-argo/workflow-roadmap#333]
Observed in QA. 
In prod, there is only 1 file per analysis, so not happening in prod.

Runs failed at step `DnaAln:dnld:scoreDn`

`Downloading object: a2e63151-ab58-5aff-9be9-1f1b58e4671c (DTB-097-WBC_2.fq.gz) -------------------------------------------------------------------------------- Restarting ERROR: Command error: I/O error on GET request for "https://submission-score.rdpc-qa.cancercollaboratory.org/download/a2e63151-ab58-5aff-9be9-1f1b58e4671c": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target Please check the log for detailed error messages Work dir: /nfs-1-c1/work/9b/6bd5fe9c3bc7b650383d4ef26e4e3d Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command`

Need to debug the Score server/client tool.

**Comment by UmmulkiramR** [comment]
@dahiyaAD to add more logging in score client and investigate the working of the download APIs

**Comment by Buwujiu** [comment]
We know which code is breaking, but don't know why it's breaking. Could it be network issue, restriction from library download? 
Next step: 
- check network issue, restriction from library download
- is reproducible in other envs? 
 - does it happen to only these 2 files or happen to other files too?
  - Aditiya: also happens in QA
  - Linda: upload 2 test files to prod TEST-INTL to help debug 
- get someone else to help? Leo?

**Comment by edsu7** [comment]
2x ~60gb `fastq.gz` files uploaded to `submission.song`:
Prod under `TEST-INTL` as `5df9be9a-543e-4884-b9be-9a543e288419`
and
Dev under `TEST-INTL` as `1591a7c8-89e5-476b-91a7-c889e5076b7e`

**Comment by lindaxiang** [comment]
> 2x ~60gb `fastq.gz` files uploaded to `submission.song`: Prod under `TEST-INTL` as `5df9be9a-543e-4884-b9be-9a543e288419` and Dev under `TEST-INTL` as `1591a7c8-89e5-476b-91a7-c889e5076b7e`

Thanks @edsu7 . 
Just gave a quick try to download the files from Prod, unfortunately the issue also exists in Prod and give me the error message:

`
  ERROR: Command error: I/O error on GET request for "https://submission-score.rdpc.cancercollaboratory.org/download/21f14053-8d3c-5c7c-99c9-e327d876918e": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
Exactly the issue as we saw in QA, the first fastq file got downloaded successfully, however hit the error when it started to download the second one.

**Comment by edsu7** [comment]
2x ~160gb `fastq.gz` files uploaded to `submission.song`:
Prod under `TEST-INTL` as `0b753bb2-4acd-4d8d-b53b-b24acd2d8ddc`
and
Dev under `TEST-INTL` as `eb2a76fb-baba-403f-aa76-fbbaba403f1c`

**Comment by Buwujiu** [comment]
Let's release this fix first!!

**Comment by Buwujiu** [comment]
Found timeout errors in Jenkins, Henro and Aditiya are looking into it. 
Next: publish the docker image

**Comment by Buwujiu** [comment]
@lindaxiang is testing in QA.

**Comment by Buwujiu** [comment]
@lindaxiang confirmed that it's tested in QA and working as expected!
