### ISSUE TITLE
Deploy Automation to Prod

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/workflow-roadmap#335]
Deploy automation to Prod, not connected to SONG, so it doesn't trigger submitted files.

**Comment by Buwujiu** [comment]
@UmmulkiramR Please add the list of service here.

**Comment by UmmulkiramR** [comment]
As a part of Automation Deployment on prod there will be code merging, version upgrades and additions/changes in RDPC Infra for the following services:
- 5 instances of workflow-graph-node
- workflow-ingest
- registry
- workflow-graphlib
- workflow-graph-manager

**Comment by Buwujiu** [comment]
Testing: can use muto and POG-CA data for DNA seq pipeline.

**Comment by Buwujiu** [comment]
Needs config updates on the graphQL change is in prod. 
https://github.com/icgc-argo/song-search/issues/83

**Comment by UmmulkiramR** [comment]
automation deployed to prod
