### ISSUE TITLE
Run sarek

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#336]
Breaking down of Sarek into modules:

- [x] ascat
- [x] cnvkit
- [x] controlfreec
- [x] deepvariant
- [x] freebayes
- [x] haplotypecaller
- [x] manta
- [x] msisensorpro
- [x] mutect2
- [ ] snpeff
- [x] strelka
- [x] tiddit

**Comment by puneet-oicr** [comment]
Delayed/slow due to troubleshooting complexity

**Comment by puneet-oicr** [comment]
msisensorpro in progress currently

**Comment by justincorrigible** [comment]
closing as completed.
