### ISSUE TITLE
Data release 6.0 Homepage text updates

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#341]
- [ ] Update DR notification
![Screenshot 2023-04-03 at 10 28 30 AM](https://user-images.githubusercontent.com/7522294/229540399-e95567ab-aac2-4f37-a250-f31fc2cb2fdd.png)

- [ ] Update announcements
**Announcements**:
**April 05 2023**: We are excited to announce [Data Release 6.0](https://docs.icgc-argo.org/docs/release-notes/data-releases#data-release-60) on the ICGC ARGO Data Platform, including the first release of a new RNA-Seq analysis workflow: [RNA Seq Alignment](https://docs.icgc-argo.org/docs/analysis-workflows/rna-alignment), available now for transcriptome sequencing data from Australian Pancreatic Cancer Initiative (APGI-AU).

**Comment by Buwujiu** [comment]
Transferring issue to platform UI.
