### ISSUE TITLE
Import 45 DNA-Seq PACA-AU donors from ICGC25K

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#344]
~13~ 45 donors in APGI-AU have only RNA-Seq data in ARGO, but missing DNA-Seq data. As a result, we cannot release these donors until they have DNA-Seq data in ARGO as well. The data is available in ICGC25K, so plan to import it over:

https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22donorId%22:%7B%22is%22:%5B%22ES:134cd156-2425-46c1-8498-63f190be81e5%22%5D%7D,%22experimentalStrategy%22:%7B%22is%22:%5B%22WXS%22,%22WGS%22%5D%7D,%22repoName%22:%7B%22is%22:%5B%22Collaboratory%20-%20Toronto%22%5D%7D%7D%7D&files=%7B%22from%22:1,%22size%22:25%7D

Will follow up with Amber first.

**Comment by hknahal** [comment]
Additional 33 donors from Amber: https://docs.google.com/spreadsheets/d/1q0y7bYaAcIBjq5UF4x5M80fUnoCAJZ9m2qe2Ju6FGVg/edit?usp=sharing


In total, Amber has requested 47 donors to be imported, but only 45 will be imported:
- 46 out the 47 donors have data T/N paired whole genome data in Collab: https://dcc.icgc.org/repositories?filters=%7B%22file%22:%7B%22donorId%22:%7B%22is%22:%5B%22ES:e854a214-ea8f-4848-b108-aac6b863107a%22%5D%7D,%22repoName%22:%7B%22is%22:%5B%22Collaboratory%20-%20Toronto%22%5D%7D%7D%7D&files=%7B%22from%22:1%7D. One of these donors has a missing matched pair so excluded from import.

Total of 45 donors will be imported 
.

**Comment by edsu7** [comment]
@hknahal  will create a ticket to perform for data import. Will need developer assistance. Will also need to verify specifics with @joneubank 

@edsu7 and @lindaxiang to check if objects exist in azure and are unaffected by data migration

**Comment by lindaxiang** [comment]
Have verified that all these 45 donors analysis and objects exist in both aws and azure. Therefore this ticket is not urgent. We can tackle this after new year. 
[paca-au_batch3_45pcawg_donors.analysis_info.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0wvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85ed1ac0d10144a7218554c069c8fa8a680d3381/paca-au_batch3_45pcawg_donors.analysis_info.txt)
