### ISSUE TITLE
Census of ICGC-ARGO data in collab 

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#349]

**Comment by edsu7** [comment]
Census of argo submission:
https://drive.google.com/file/d/1DtpbiyJWgU7Swf76D1iV8MB2SN9ttU0O/view?usp=share_link

Summary of finds:
|foundInCollab|publishedState|objectCount|Notes|
|--|--|--|--|
|False|PUBLISHED|28|Do not copy?  1 `MUTO-INTL` + 18 `TEST-INTL` + 9 `POG-CA`|
|False|SUPPRESSED|424|Do not copy|
|False|UNPUBLISHED|373|Do not copy|
|True|PUBLISHED|1837|Unneeded once processed|
|True|SUPPRESSED|780|Do not copy|
|True|UNPUBLISHED|22|Do not copy|

Additionally I have an objectId `c9d2693f-e54b-592b-97b2-08c4c49bc0d2` with no record in `SONG`

**Comment by edsu7** [comment]
Census of argo prod:
https://drive.google.com/file/d/1FSmqvGwVjpAm02VlfyQ32BNV1VwkEi1u/view?usp=share_link


|foundInCollab|publishedState|objectCount|Notes|
|--|--|--|--|
|False|PUBLISHED|6|Do not copy? 6 `TEST-INTL`|
|False|SUPPRESSED|38|Do not copy|
|False|UNPUBLISHED|373|Do not copy|
|True|PUBLISHED|54326|Copy over|
|True|SUPPRESSED|2122|Do not copy|
|True|UNPUBLISHED|671|Do not copy|

**Comment by edsu7** [comment]
Census of argo qa
https://drive.google.com/file/d/1i6GBYHDWahq2p8iE18hwy2P4YE5wMgt2/view?usp=share_link
|collab|publishedState|ObjectCount|
|--|--|--|
|False|PUBLISHED|10|
|False|UNPUBLISHED|416|
|True|PUBLISHED|15236|
|True|SUPPRESSED|1054|
|True|UNPUBLISHED|812|
|True|noSongRecord|1519|

**Comment by edsu7** [comment]
Census of argo submission-qa:
https://drive.google.com/file/d/1h-U8XwH09PWk8w__nXq0YR0GUTffJM_d/view?usp=share_link
|collab|publishedState|ObjectCount|
|--|--|--|
|False|SUPPRESSED|6|
|False|UNPUBLISHED|349|
|True|PUBLISHED|1544|
|True|SUPPRESSED|155|
|True|UNPUBLISHED|165|
|True|noSongRecord|9|

**Comment by edsu7** [comment]
Census of argo submission-dev:
https://drive.google.com/file/d/1B3w23_fjt7lNT7oB5-462lqqkBcVPRFG/view?usp=share_link
|collab|publishedState|ObjectCount|
|--|--|--|
|False|UNPUBLISHED|14|
|True|PUBLISHED|528|
|True|SUPPRESSED|157|

**Comment by edsu7** [comment]
Census of argo dev:
https://drive.google.com/file/d/1yukHPzd7Cr9pAv3BOpPKBPp6MXAgmgOU/view?usp=share_link
|collab|publishedState|ObjectCount|
|--|--|--|
|False|PUBLISHED|6|
|False|UNPUBLISHED|57|
|True|PUBLISHED|3553|
|True|SUPPRESSED|282|
|True|UNPUBLISHED|71|
|True|noSongRecord|28|

**Comment by edsu7** [comment]
Data migration is progress. @edsu7 will audit again following data freeze in Mid-October

**Comment by justincorrigible** [comment]
Closing ticket as done. Will open a new similar ticket if needed later.
