### ISSUE TITLE
Workflow Run Failure - Run is completed but return the state of `SYSTEM_ERROR`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#351]
## Detailed Description

The run already completes all the tasks successfully, however the returned state is `SYSTEM_ERROR`.
Notice that the completed timestamp is always before started timestamp, and the duration is negative number. 

## List all runids affected
wes-69a0e5aee3d44ba79427d274419e0af7
wes-c56544940bea4042ab8c8864bd8493db
wes-f63059947de9492689d582a805797317
wes-679c44b53776473ca5d7f4e7529d0643
wes-0190a69a323b4fa398a8517f3223291c

## Exit criteria
- [ ] Root cause is found
- [ ] Run state is corrected

**Comment by edsu7** [comment]
```
wes-69a0e5aee3d44ba79427d274419e0af7
wes-c56544940bea4042ab8c8864bd8493db
wes-b1f810926c024e75844910b4785d005d
wes-eecb7b559fc64881a58bbfa9c91c321c
wes-0190a69a323b4fa398a8517f3223291c
wes-679c44b53776473ca5d7f4e7529d0643
```

`wes-f63059947de9492689d582a805797317` seems to be a different issue with multi `DnaAln:oxog' and `scoreUpload` failing

**Comment by UmmulkiramR** [comment]
The statuses of the run Ids have been updated to COMPLETE.
