### ISSUE TITLE
Correcting issues and downstream implications concerning argo-metadata-schemas/issues/69

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#355]
See https://github.com/icgc-argo/argo-metadata-schemas/issues/69 for breakdown of the bug.

We will have a number of items to address in response to the bug

- [x] Correct QA/Dev Submission.SONG schema (sequencing_experiments)
- [x] Correct QA/Dev SONG schema (sequencing_alignment, qc_metrics, splice_junctions, supplement)
- [x] Correct Production Submission.SONG.schema (sequencing_experiments)
- [x] Correct Production SONG schema (sequencing_alignment, qc_metrics, splice_junctions, supplement)
- [x] Correct QA/Dev Submisison.SONG payloads (sequencing_experiments)
- [x] Correct Production Submission.SONG payloads (sequencing_experiments)
- [x] Correct QA/Dev SONG Payloads (alignments)
- [x] Correct Production SONG payloads (alignments)
- [x] Identify any other schema with typo

**Comment by lindaxiang** [comment]
[Here](https://docs.google.com/spreadsheets/d/1FhJzrUO_1GGKcEuX7ykVnoDf4OsPMRdvjAGGbcH4XMk/edit?usp=sharing) is the auditing results for section `experiment` in all the Prod Song analysis. 
The problematic records are summarized as following, and the fields with issue are **bolded**. 

**analysis\_type**|**analysis\_id**|**study\_id**|**platform**|**experimental\_strategy**|**sequencing\_date**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
sequencing\_experiment|b13fef95-7dcd-498d-bfef-957dcd998dab|POG-CA|**illumina**|WGS|2017-06-16
sequencing\_experiment|d6211af1-4594-4045-a11a-f14594104540|POG-CA|**illumina**|WGS|2017-06-16
sequencing\_alignment|19ce7a46-c3d2-4531-8e7a-46c3d27531f0|POG-CA|**illumina**|WGS|2017-06-16
sequencing\_alignment|9eaae7f6-5c96-448d-aae7-f65c96648d83|POG-CA|**illumina**|WGS|2017-06-16
qc\_metrics|b054f9c4-5ae2-4bfc-94f9-c45ae28bfc66|POG-CA|**illumina**|WGS|2017-06-16
qc\_metrics|fff56bde-6d01-41f0-b56b-de6d0101f0a7|POG-CA|**illumina**|WGS|2017-06-16
sequencing\_experiment|0b753bb2-4acd-4d8d-b53b-b24acd2d8ddc|TEST-INTL|**Illumina**|WGS|**NULL**
sequencing\_experiment|5df9be9a-543e-4884-b9be-9a543e288419|TEST-INTL|**Illumina**|WGS|

**Comment by lindaxiang** [comment]
- All the above 8 Song analysis in **Prod** have been corrected for the problematic fields:
-- platform:     "illumina" ---> "ILLUMINA" and "Illumina" ---> "ILLUMINA"
-- sequencing_date:   "NULL" ---> null

- All the 54 Song analysis (`sequencing_experiment`) in **QA** have been updated for field `platform`
[UBCPC-CA.submission-song-qa.update.txt](https://github.com/icgc-argo/workflow-roadmap/files/11491496/UBCPC-CA.submission-song-qa.update.txt)

**Comment by puneet-oicr** [comment]
Resolved, but keeping it open till the check box items are addressed.
Invalid value in prod has been all cleared out and schema has been corrected.

**Comment by edsu7** [comment]
No more updates. Closing.
