### ISSUE TITLE
Feature Request  - Workflow automation needs to pick up the correct song/score client containers and versions 

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#356]
## Detailed Description

Many time, song/score clients need to bump versions to address issues. Workflow automation will need to be able to pick up the correct song/score clients containers and versions. 
The params which defined the song/score client containers and versions are:
```
params.song_container
params.song_container_version
params.score_container
params.score_container_version
```
## Implementation
Params are only stored in wf registry, need to update registry schema to add these params.

## Next Steps
1. Where to get these params? 
2. How to maintain them?

**Comment by UmmulkiramR** [comment]
The params have been added to the registry and are now available in QA

**Comment by UmmulkiramR** [comment]
As @lindaxiang suggested we will not be adding song and score versions in the registry but instead we will have them in the workflow itself to keep WES agnostic to workflows

**Comment by UmmulkiramR** [comment]
closing the ticket based on the comment above.
