### ISSUE TITLE
Update the docs site for new molecular data submission workflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#357]
The docs site for molecular data submission needs to be updated to use the new molecular data submission workflow, specifically the following sections:
- https://docs.icgc-argo.org/docs/submission/molecular-data-prep
- https://docs.icgc-argo.org/docs/submission/submitting-molecular-data

The draft guideline for new molecular data submission workflow is:
https://docs.google.com/document/d/14crfWmOaCJ85kVgKtik9kVJQ-pTDud_iX04wbviFDj4/edit?usp=sharing

**Comment by lindaxiang** [comment]
Draft PR is created: https://github.com/icgc-argo/argo-docs/pull/555
Review the updated docs at: https://deploy-preview-555--argo-docs.netlify.app/
Branch with updates: https://github.com/icgc-argo/argo-docs/tree/data-submission-wf

**Comment by lindaxiang** [comment]
Thanks to Justin, merged and deployed.

**Comment by edsu7** [comment]
Closing!
