### ISSUE TITLE
Update SCORE documentation on ARGO site

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#359]
Existing URL:
https://docs.icgc-argo.org/docs/data-access/data-download

Things to add/update:
- CRAM specific flags
- Double check with Aditya if any additional changes were added that should be addressed

**Comment by edsu7** [comment]
ping Leo and Mitchell

**Comment by edsu7** [comment]
https://docs.google.com/document/d/1tJH38mqxb4SAaeHsCG9Sr5XGiWDDv8m4FVt8-SzzR90/edit

**Comment by lindaxiang** [comment]
Already done.
