### ISSUE TITLE
Update Nextflow to DSL2: workflows 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#36]
- Once the song/score module is updated to run nextflow DSL2, all current workflows need to have that module imported and a new version published.
- check with @junjun-zhang if any more wf changes needed for DSL2 upgrade

- [x] Bug in work found: https://github.com/icgc-argo/nextflow-data-processing-utility-tools/issues/23

These are the workflows that need to be upgrades with both SONG/Score module upgrade and minor DSL2 Upgrades:
- [x]  Mutect 2
--- https://github.com/icgc-argo/gatk-mutect2-variant-calling/issues/13 
- [x] Alignment 
--- https://github.com/icgc-argo/dna-seq-processing-wfs/issues/49
- [x] Sanger WXS
--- https://github.com/icgc-argo/sanger-wxs-variant-calling/issues/6
- [x] Sanger WGS
--- https://github.com/icgc-argo/sanger-wgs-variant-calling/issues/3

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/nextflow-data-processing-utility-tools/releases/tag/2.0.0 

@junjun-zhang new version is ready and tagged!

We need to import this into all workflows, and test them in argo-qa environment.

**Comment by junjun-zhang** [comment]
as discussed, we will start the work from mutect2 workflow to use the updated the SONG/SCORE modules which have been updated with DSL2 syntax and removed api token as explicit param. Once everything works as expected, we will move on to other three production workflows.

**Comment by rosibaj** [comment]
@junjun-zhang i made a ticket for the import into each of the wfs - i didnt assign anyone or anything :) As discussses once all have been updated and tested, i just want to confirm with the release version pasted above on the ticket so we can coordinate deploy!

**Comment by junjun-zhang** [comment]
tested Mutect2 workflow (in DSL2 syntax with [latest SONG/SCORE](https://github.com/icgc-argo/nextflow-data-processing-utility-tools/releases/tag/2.1.0)) in the QA (Nextflow 20.07) environment. When `api_token` explicitly provided, the workflow ran successfully from A to Z. Auto-injection of api token via pod secret seems not functioning properly, awaiting this being addressed before proceed with further testing.

**Comment by rosibaj** [comment]
Blocked by https://github.com/icgc-argo/nextflow-data-processing-utility-tools/issues/23

**Comment by rosibaj** [comment]
@junjun-zhang whats the confirmed working tag for the mutect wf?

**Comment by junjun-zhang** [comment]
the branch we are testing is [0.3-dev](https://github.com/icgc-argo/gatk-mutect2-variant-calling/tree/0.3-dev), it's not formally released yet, awaiting completion of test using WGS input on QA.

**Comment by rosibaj** [comment]
all previous three prod workflows have been update to enable dsl2 and use song/score 2.3.0:
-  https://github.com/icgc-argo/dna-seq-processing-wfs/releases/tag/1.4.0
- https://github.com/icgc-argo/sanger-wxs-variant-calling/releases/tag/3.1.6-3-1.2 
- https://github.com/icgc-argo/sanger-wgs-variant-calling/releases/tag/2.1.0-9-1.2
- https://github.com/icgc-argo/gatk-mutect2-variant-calling/releases/tag/4.1.8.0-1.0
