### ISSUE TITLE
Workflow Run Failure: Score upload

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#37]
## Detailed Description

![Screen Shot 2020-09-01 at 10 40 01 AM](https://user-images.githubusercontent.com/7522294/91865860-d478c200-ec3f-11ea-980f-6169422be8c5.png)

Key error message is here:
`ERROR: Data transfer has been interrupted. Some parts are missing. Waiting to retry... Total execution time: 1.276 s Total bytes read : 0 Total bytes written : 65,039,366 ERROR: Command error: java.io.IOException: Please check the log for detailed error messages`

Issue observed around Aug 12 - Ceph upgrade changes in this time (No Song/Score version upgrades). Changes being investigated.  

## List all runids affected

wes-85a1e3002f81419289b9e32a8203b68c
wes-90d65b89fc0640e19e1c224f20155719
wes-da9b0c5e981843399b84270784543c68
wes-84c2609e83284497816a25dd80ccab3a
wes-111519ad0f2141feacf1dcd0a4b93e16
wes-7971ffc395af40858065633d83973db7
wes-b71b6b355ecf4ce18e91b5f645059dd0
wes-bfaca87058e544cd8c5fa1d62ae31469
wes-a25402d6d9684b588c475df36c5edcfc
wes-476de54d536e4bbfa3324a1b13844b63
wes-3573a43e09754fb7a84a121fcd1c7486
wes-a365878b6e6a40eeba946dbd48f16f6e
wes-68a14166ccc2434b864dec2015f264d4
wes-47d9e31e2b354cf4b80f24040157237a
wes-9d7e9d28a620445dba671524bf15624d
wes-7f6f349d90bb437c9d7db6401a51535f
wes-b7532d7ea0d9468db09407664f858cc1
wes-536a05c9ddb9405990ad1073bd6ccd9a
wes-03b6f2992d214b47827ed99ef508fd5a
wes-005796b4d9874275b7a928daa1edf7bd

## Exit criteria
- [x] Issue has been resolved
- [x] Run is resumed

**Comment by lindaxiang** [comment]
These jobs are worth trying resume using the workaround @junjun-zhang mentioned. Needs to discuss the doable steps with @lepsalex  after score upload issue being resolved.

**Comment by lepsalex** [comment]
all jobs have been resumed, most have already completed, this can be closed.

**Comment by rosibaj** [comment]
last runnin job will take > 7 days. we have IT shudown over weekend, so job will not be able to complete.  closing this issue as all other jobs have completed upload.
