### ISSUE TITLE
Data Release 7.0

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#372]
1. - [x] APGI-AU:  icgc25k donors with new Clinical data  (83 donors have both core completetion and molecular data released)
   RE: Amber is working with them to complete all the clinical data. Confident they will complete by October. Also awaiting the additional exception for dose. 
2. - [x] PTC-SA: icgc25k donors with new Clinical data (239 donors have both core completetion and molecular data released) 
3. - [x] PACA-CA icgc25k donors with new Clinical data (87 donors now have 20%-60% of core completion, 49 donors have no clinical submission yet)
     RE: Amber met with the team last week, they are prioritising the remaining clinical data, she has advised of the deadline. Confident they will complete by October. 
4. - [ ] OCCAMS-GB  icgc25k donors with new Clinical data (409 donors have 40% core completion)
    RE: Amber is helping to submit clinical data. Will need clinical exceptions on certain fields. Amber will share with DCC soon.
5. - [ ] Subset of 515 MUTO-INTL argo donors with both Clinical and Molecular data
      - a. Clinical data submission (blocked by lost to follow-up)
      - b. https://github.com/icgc-argo/workflow-roadmap/issues/292
6. - [ ] Molecular data QC: staging + prod
     - a. https://github.com/icgc-argo/workflow-roadmap/issues/391
7. - [ ] Documentation
         - a. data release note
         - b. clinical data downloading instruction
8. - [ ] Muto-intl to lift embargo: https://github.com/icgc-argo/roadmap/issues/972

**Comment by lindaxiang** [comment]
Data status: https://docs.google.com/spreadsheets/d/1aKLLbisDwI01qhijoWoy7U5fj3J1whRLQzC2USuCazI/edit#gid=313800117

**Comment by edsu7** [comment]
@lindaxiang can you please add OCCAMS-GB to the above checklist

- @hknahal will connect with Amber for a progress update.
  - PACA-CA clinical submission in progress. 
  - OCCAMS-GB
  - APGI-AU working to submit

- PTC-SA is ready.

- MUTO-INTL
  - we're prioritizing releasing all alignment and MUTECT2 from 505 donors, (~300) subset sanger calls.
  - clinical still blocked by lost to follow up
  
We can check with Melanie and Amber if we want to include `POG-CA`

**Comment by lindaxiang** [comment]
@puneet-oicr @justincorrigible 
We can close the ticket for now sinceData Release 7.0 is done with the following
- APGI-AU: 84 donors have new clinical data
- PACA-CA: 38 donors have new clinical data
- PTC-CA: 239 donors have new clinical data

However, 
1. the following data need to push to Data Release 8.0
- MUTO-INTL: 515 donors with new clinical and molecular data
- OCCAMS-GB: 400 donors with new clinical data

2. the following tasks need to be prioritized before DR8.0:
- Core completion policy changes and new type of exceptions (whole table exception) setting up. (CMD, Melanie, etc.)
- Platform updates to support core completion changes. (Jon and dev team)
- Work with data submitter to get their data in (Bioinfo)
- Documentation of clinical data downloading instruction (Bhavik)
