### ISSUE TITLE
Process MUTO-INTL Sanger Workflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#373]
Sanger worksheet: https://docs.google.com/spreadsheets/d/13uxLJEjv5m6Q4nNOAsgeIKs8gm2rMctBK2CDXL5c4lU/edit#gid=955963386

Status - 505 donors in total

**Comment by lindaxiang** [comment]
3 jobs completed. No major issues.

**Comment by lindaxiang** [comment]
68/505 completed.

**Comment by lindaxiang** [comment]
The following sanger job failed with `ASCAT failed to generate a solution`:
```
https://wes.rdpc.cancercollaboratory.org/runs/wes-07d058e2d222416fa6af7f8131a7b4ab
```
This is a known issue regarding sanger ASCAT caller: https://github.com/icgc-argo/workflow-roadmap/issues/144

**Comment by edsu7** [comment]
185/505 completed.

**Comment by lindaxiang** [comment]
258/505 completed

**Comment by lindaxiang** [comment]
435/505 completed. 10 failed jobs, 58 queued jobs, 2 still running jobs. 
This ticket can be closed. 

Next step: open new ticket to tackle failed jobs and start jobs on cumulus rdpc.

**Comment by lindaxiang** [comment]
Open new QC ticket: https://github.com/icgc-argo/workflow-roadmap/issues/400
