### ISSUE TITLE
Process MUTO-INTL Mutect2 Workflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#374]
Mutect2 worksheet: https://docs.google.com/spreadsheets/d/13uxLJEjv5m6Q4nNOAsgeIKs8gm2rMctBK2CDXL5c4lU/edit#gid=20816066

Status - 505 donors in total

**Comment by lindaxiang** [comment]
23 out of 505 jobs completed in ~1 week. No major workflow issues.

**Comment by lindaxiang** [comment]
85/505 jobs completed.

**Comment by edsu7** [comment]
301/505 completed.

**Comment by lindaxiang** [comment]
356/505 completed

**Comment by lindaxiang** [comment]
499/505 completed. 6/505 failed due to input alignments downloading issue. 
This ticket can be closed. 

Next step: start new ticket for QC the results and debugging failed jobs.

**Comment by lindaxiang** [comment]
QC ticket has been created: https://github.com/icgc-argo/workflow-roadmap/issues/399
