### ISSUE TITLE
🐛 MUTO-INTL Duplicate read groups in analysis

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#378]
The problem:
- the following analyses have duplicate read submitter read groups.

Additional context:
- these analyses were submitted back in Nov 2022 predating data submission workflow
- Inspection of BAM files show data has the correct read group names, just the payloads are incorrect
- Read group level should be modifiable via PATCH

Solution
- parse the BAM's headers to retrieve the correct data, and update the payloads
- Send updated payloads to Jing wei for confirmation
- For sanity's sake, run seq-tools to verify nothing else is wrong with the data

```
https://submission-song.rdpc.cancercollaboratory.org/studies/MUTO-INTL/analysis/0ae00836-7cea-4418-a008-367cea7418d6
https://submission-song.rdpc.cancercollaboratory.org/studies/MUTO-INTL/analysis/2e0b71e6-cde1-457a-8b71-e6cde1357a78
https://submission-song.rdpc.cancercollaboratory.org/studies/MUTO-INTL/analysis/ba1aa2fc-e60c-42bf-9aa2-fce60c02bf1c
https://submission-song.rdpc.cancercollaboratory.org/studies/MUTO-INTL/analysis/cce9b526-76e5-43c6-a9b5-2676e553c6d8
```

**Comment by edsu7** [comment]
Stephen confirmed payloads have the correct read group IDs. Payloads have been updated to reflect correct read group IDs.  Additionally performed seq-tools check on all four files without issues. @lindaxiang should be good for alignment.

**Comment by lindaxiang** [comment]
Sounds great and thank you @edsu7
