### ISSUE TITLE
Workflow Run Failure: sangerWGS

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#38]
## Detailed Description

Likely be terminated because of out of memory issue. 

## List all runids affected
wes-d31933ad912a4189be39747f00c0d096
wes-2b11b0d1d2fc4d71b83a223e0076ad4a
wes-55f1ccd0658f4b5eaacad6873f776540
wes-005796b4d9874275b7a928daa1edf7bd(resume by wes-55fdf4f090f044bc9960effb1fcb42a8)

## Approach to address this
Adjust the cpu/mem parameter and re-run the jobs. 

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by rosibaj** [comment]
Potential to not resume, but re-do after upgrade.  Discuss with Linda  and Alex

**Comment by lindaxiang** [comment]
Yes, I agree. It is better to re-do these three jobs with adjusted params(cpu and mem) after upgrades.  @rosibaj

**Comment by rosibaj** [comment]
mark do not retry

**Comment by lindaxiang** [comment]
These three have been re-run and completed successfully before upgrade. 
wes-d31933ad912a4189be39747f00c0d096
wes-2b11b0d1d2fc4d71b83a223e0076ad4a
wes-55f1ccd0658f4b5eaacad6873f776540

Only one is left to re-run after upgrade:
wes-005796b4d9874275b7a928daa1edf7bd(resume by wes-55fdf4f090f044bc9960effb1fcb42a8 and failed again.)

**Comment by rosibaj** [comment]
@lindaxiang is the fourth run here still failing?

**Comment by lindaxiang** [comment]
@rosibaj , just checked. The fourth one was already redo and completed:
https://wes.rdpc.cancercollaboratory.org/runs/wes-c61f804185da45ba95a983852ba79a3d
We can close this issue now.

**Comment by rosibaj** [comment]
@lindaxiang ok great i will close this then!
