### ISSUE TITLE
🐛 Unable to un-register/delete LUCA-KR samples

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/workflow-roadmap#380]
## Description
Attempting to unregister samples from LUCA-KR which have incorrectly submitted submitter_specimen_ids (were submitted using incorrect characters such as commas, brackets, tilde characters): [LUCA-KR_samples_to_delete.csv](https://github.com/icgc-argo/workflow-roadmap/files/12443496/LUCA-KR_samples_to_delete.csv). The delete endpoint does not delete the sampleIds that were submitted.

## Steps to reproduce
**Example 1:**
Unable to un-register sampleIds `SA611376` and `SA611250` from LUCA-KR program (because of the incorrectly submitted submitter_specimen_ids `S1529515-1B, 1D` and `S1529515-1B, 1D_N`)

|donorId|	submitter_donor_id|	specimenId|	submitter_specimen_id|	tumour_normal_designation|	sampleId|	submittter_sample_id|
|--|--|--|--|--|--|--|
|DO250577|	34991616|	SP211187|	S1529515-1B, 1D|	Tumour|	SA611376|	PSW-0809|
|DO250577|	34991616|	SP211440|	S1529515-1B, 1D_N|	Normal|	SA611250|	PS-0809|

Endpoint:
```
curl -X 'DELETE' \
  'https://clinical.platform.icgc-argo.org/submission/program/LUCA-KR/registration/unregister?dryRun=false&sampleSubmitterIds=SA611376%2CSA611250' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer <my_eg_token>'```
```

Output:
- Donor and specimens are not removed
![unregister_luca-kr_sample_output](https://github.com/icgc-argo/workflow-roadmap/assets/4992044/93c19e66-2cce-4d02-b817-bf149a320162)

Still able to query submitter_sample_id `PSW-0809`:
```
https://clinical.platform.icgc-argo.org/clinical/samples/id?programId=LUCA-KR&submitterId=PSW-0809
```

Output: ```SA611376```

**Example 2:**
Tried to delete this sample (which does not have any incorrectly submitted identifiers with strange characters). Same error (deletion endpoint does not work and sample does not get deleted):
|donorId|	submitter_donor_id|	specimenId|	submitter_specimen_id|	tumour_normal_designation|	sampleId|	submittter_sample_id|
|--|--|--|--|--|--|--|
|DO250604|25638179|SP211268|S1440436|Tumour|SA611327|PS-0198|

## Expected behaviour
Expected sampleIds `SA611376` and `SA611250` to be deleted from clinical and if a query for the unregistered submitter_sample_id `PSW-0809` is run, it should not return a sampleId.

**Comment by edsu7** [comment]
Confirmed `SA611376` and `SA611250` no longer exist in clinical, submission song or song.

Confirmed `SA611327` does not exist in clinical or song and suppressed in submission song.

Closing.
