### ISSUE TITLE
Collab VMs auditing and data migration

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#383]
With Collaboratory shutting down at the end of 2023, we need to audit all Collab VMs and migrate needed data from Collab to Azure/Cumulus.
- This [google sheet](https://docs.google.com/spreadsheets/d/1zvmxtIKj5_ROo7o0O6T5MsEsbmqyp3UJVc989CDT1H4/edit?usp=sharing) contains Bioinfo's Collab VMs info and audit results.

**Comment by lindaxiang** [comment]
Have reviewed all the VM I have access. Data has been transferred. VMs have been deleted.

**Comment by justincorrigible** [comment]
Closing as completed
