### ISSUE TITLE
🐛 Running workflow of nf-core framework in RDPC-QA got incorrect `nextflow.config` under launchDir

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#388]
## Describe the bug
A `nextflow.config` file is auto-generated under `launchDir` when we kick off a job. E.g,
```
/nfs/nfs-dev-1/vol-qa-2/wfgn-launch/nextflow.config
```
The information should come from input parameters and `nextflow.config` under `projectDir`. 
```
/nfs/nfs-dev-1/vol-qa-2/wfgn-project/icgc-argo-workflows/prealnqc/nextflow.config
```
However auto-generated `nextflow.config` under `launchDir` contains cached information which are from neither input parameters nor `nextflow.config` under `projectDir`. E.g,
```
cpus = { check_max( 1    * task.attempt, 'cpus'   ) }
   memory = { check_max( 6.GB * task.attempt, 'memory' ) }
   time = { check_max( 4.h  * task.attempt, 'time'   ) }
   errorStrategy = { task.exitStatus in [143,137,104,134,139] ? 'retry' : 'finish' }
   maxRetries = 1
   maxErrors = '-1'
   withLabel:process_single {
      cpus = { check_max( 1                  , 'cpus'    ) }
      memory = { check_max( 6.GB * task.attempt, 'memory'  ) }
      time = { check_max( 4.h  * task.attempt, 'time'    ) }
   }
   withLabel:process_low {
      cpus = { check_max( 2     * task.attempt, 'cpus'    ) }
      memory = { check_max( 12.GB * task.attempt, 'memory'  ) }
      time = { check_max( 4.h   * task.attempt, 'time'    ) }
   }
   withLabel:process_medium {
      cpus = { check_max( 6     * task.attempt, 'cpus'    ) }
      memory = { check_max( 36.GB * task.attempt, 'memory'  ) }
      time = { check_max( 8.h   * task.attempt, 'time'    ) }
   }
   withLabel:process_high {
      cpus = { check_max( 12    * task.attempt, 'cpus'    ) }
      memory = { check_max( 72.GB * task.attempt, 'memory'  ) }
      time = { check_max( 16.h  * task.attempt, 'time'    ) }
   }
   withLabel:process_long {
      time = { check_max( 20.h  * task.attempt, 'time'    ) }
   }
   withLabel:process_high_memory {
      memory = { check_max( 200.GB * task.attempt, 'memory' ) }
   }
```
The configure file contains a function `check_max` which cause the following error.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to 'https://wes.rdpc-qa.cancercollaboratory.org/runs'
2. Click on 'NEW RUN'
3. Input the following and submit RUN:
Workflow URL: https://github.com/icgc-argo-workflows/prealnqc
Workflow Params: 
```
{
   "study_id":"TEST-QA",
   "analysis_ids":"875ef550-e536-4456-9ef5-50e5362456df",
   "song_url_download":"https://submission-song.rdpc-qa.cancercollaboratory.org",
   "score_url_download":"https://submission-score.rdpc-qa.cancercollaboratory.org",
   "song_url":"https://song.rdpc-qa.cancercollaboratory.org",
   "score_url":"https://score.rdpc-qa.cancercollaboratory.org"
}
```
Workflow Engine Params:
```
{
	"launchDir": "/nfs-dev-1-vol-qa-1/wfgn-launch",
	"projectDir": "/nfs-dev-1-vol-qa-1/wfgn-project",
	"revision": "main",
	"workDir": "/nfs-dev-1-vol-qa-1/wfgn-work"
}
```
4. See error: 
`
Error Msg: Error executing process > 'PREALNQC:STAGE_INPUT:SONG_SCORE_DOWNLOAD:songGet (9bb63c49-86c8-44e2-b63c-4986c804e274)' Caused by: No signature of method: nextflow.script.ScriptBinding.check_max() is applicable for argument types: () values: []
`

## Expected behaviour
The job can be kicked off successfully.

**Comment by UmmulkiramR** [comment]
prealnqc jobs now run and complete succcessfully in QA.

**Comment by lindaxiang** [comment]
Thanks to @UmmulkiramR . 
I can confirm that both prealnqc and dnaalnqc runs can be kicked off and complete successfully in QA. 
prealnqc: https://wes.rdpc-qa.cancercollaboratory.org/runs/wes-c6f9a8842bcd48c4a5430384f6fb8e98
dnaalnqc: https://wes.rdpc-qa.cancercollaboratory.org/runs/wes-3f7cdfe35468484491e2f42e1964008d

**Comment by UmmulkiramR** [comment]
closing this issue.
