### ISSUE TITLE
MUTO-INTL data QC reports

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#391]
Compile the QC reports for process MUTO-INTL data.

**Comment by lindaxiang** [comment]
MUTO-INTO processed genomic data release criteria:

**analysis workflow**|**QC criteria**|**analysisType**|**file access**
-----|-----|-----|-----
dna alignment|1. must have mutect2 or sanger called successfully<br />2. cross_sample_contamination <4% | squencing_alignment | controlled
sanger variant calling|1. exclude ASCAT failed donors<br />2. exclude purity < 30% donors<br />3. exclude purity=100% donors | variant_calling | controlled
mutect2 variant calling | | variant_calling | controlled

Note: 
1. Sarah Moody has confirmed (by email) that all submitted samples in the submitted cohorts have been manually curated and passed the quality check on mutographs end, however there're 123 cases going through the partial pipeline instead of the regular sanger pipeline. 
2. We came up with the following strategy to QC sanger results
-----------------------------
- If germline BAF changes are present: if matched normal is blood = run partial pipeline.  If matched normal is adjacent normal tissue = exclude
- If purity is <30%, reject and run partial pipeline
- If purity is 100%, review ASCAT sunrise and run partial pipeline if there is a purity issue
-----------------------------
3. Since we currently do not have the partial pipeline available, we will put those affected cases on hold. 
4. To verify the efficiency of the above strategy, we will compile a list of MUTO samples for Sarah to cross reference her records.

**Comment by lindaxiang** [comment]
Based on QC audit on Oct.19th, the attached song analysis are generated by failed or duplicated runs which have been suppressed. 

[suppress.Oct19.txt](https://github.com/icgc-argo/workflow-roadmap/files/13049024/suppress.Oct19.txt)

**Comment by lindaxiang** [comment]
Based on QC audit on Oct.19th, the attached 2812 song analysis and 482 donors are candidates to be released. 
[donor.txt](https://github.com/icgc-argo/workflow-roadmap/files/13049382/donor.txt)
[analysis.txt](https://github.com/icgc-argo/workflow-roadmap/files/13049383/analysis.txt)
[release_list_info.txt](https://github.com/icgc-argo/workflow-roadmap/files/13049386/release_list_info.txt)

**Comment by lindaxiang** [comment]
Please refer to https://github.com/icgc-argo/workflow-roadmap/issues/418#issuecomment-1974096585 for updated QC criteria.

**Comment by justincorrigible** [comment]
Closing as completed with DR 8
