### ISSUE TITLE
Data may be corrupted in Prod and submisison.prod

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#392]
The following data objects are not able to be transferred from ARGO Prod object store to Azure, needs further investigation to confirm whether they are corrupted data (CRAM and from `MUTO-INTL`):
```
2021-04-01 10:43:10 76022105751 data/03208477-4703-54b9-919f-3394c91184b5
2023-09-24 11:34:14 64144999153 data/3b44736f-aea8-5170-a588-32798ed61194
2023-09-08 21:33:36 64173335439 data/8140ddf0-daf0-5f3a-9ebd-0b93cb4f1af0
2023-09-22 15:29:43 28386687611 data/a63f20fc-c7f6-5d1c-aa58-32b03987cba6
2023-09-24 05:21:49 51274193270 data/bd03cd71-ed3c-5750-93e0-05faf6d05430
2023-09-25 01:52:03 30227569356 data/c5937a93-8b4b-58ca-bcef-27ee479aec1a
2023-09-25 08:05:40 62762772529 data/d2e59446-8fec-5b1f-939a-460ee0d64e4d
```

Submission Prod (`POG-CA`):
```
2022-10-04 16:14:49 140599205824 1820e4c6-ad59-573d-b168-6778f3e09a59
2022-09-20 17:32:40 69143695051 5b8636ba-059f-5d52-ba2c-dd40fdb73bcc
```

**Comment by lindaxiang** [comment]
Edmund confirms that
```
https://song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/files/03208477-4703-54b9-919f-3394c91184b5
```
is from
```
https://song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/analysis/d8a0d6d2-fbff-47d9-a0d6-d2fbff57d989
```
which is suppressed.

**Comment by edsu7** [comment]
Objects:
```
1820e4c6-ad59-573d-b168-6778f3e09a59
5b8636ba-059f-5d52-ba2c-dd40fdb73bcc
```
are related to analysisIds:
```
https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/e26a8fe8-2678-44e6-aa8f-e8267894e6a1
https://submission-song.rdpc.cancercollaboratory.org/studies/POG-CA/analysis/a82ed194-974a-455a-aed1-94974a455a8c
```

Both:
`e26a8fe8-2678-44e6-aa8f-e8267894e6a1` and `a82ed194-974a-455a-aed1-94974a455a8c` failed processing b/c of scoreDownload errors, their runs respectively:
https://wes.rdpc.cancercollaboratory.org/runs/wes-33212318259944e6a659f2177819caf5
https://wes.rdpc.cancercollaboratory.org/runs/wes-8e8e927e1d6d45d59f99cfa92a471728

**Comment by jmimico** [comment]
I did another synchronization and here is the new master list of object ID's which are problematic (unable to be copied, downloaded, etc)

```
ARGO
------
8140ddf0-daf0-5f3a-9ebd-0b93cb4f1af0
a63f20fc-c7f6-5d1c-aa58-32b03987cba6
03208477-4703-54b9-919f-3394c91184b5
3b44736f-aea8-5170-a588-32798ed61194
bd03cd71-ed3c-5750-93e0-05faf6d05430
c5937a93-8b4b-58ca-bcef-27ee479aec1a
d2e59446-8fec-5b1f-939a-460ee0d64e4d
585f5ad4-111d-5cad-9295-14f7554039b8

ARGO submission
------------------
b2bed8da-7bf0-53eb-be49-0e93b0dfa852
5b8636ba-059f-5d52-ba2c-dd40fdb73bcc
1820e4c6-ad59-573d-b168-6778f3e09a59
a2cf2a90-0511-54fa-92fb-29c5fb92ac74

**Comment by edsu7** [comment]
Update concerning the following objects post azure transfer

ARGO		
------------------
|objectId|analysisId|studyId|Notes|
|----|---|---|---|
|8140ddf0-daf0-5f3a-9ebd-0b93cb4f1af0|eee3bfa3-9bb8-41fa-a3bf-a39bb8a1fa46|MUTO-INTL|See analysis `3b0dda11-4dae-4b68-8dda-114dae4b68e9`|
|a63f20fc-c7f6-5d1c-aa58-32b03987cba6|95d89def-01f5-4683-989d-ef01f5a683af|MUTO-INTL|See analysis `1233cfbd-adfb-4e28-b3cf-bdadfb4e2886`|
|3b44736f-aea8-5170-a588-32798ed61194|9cd44a20-ed00-4548-944a-20ed00854879|MUTO-INTL|See analysis `6ef4d6df-9744-4c97-b4d6-df9744dc9799`
|bd03cd71-ed3c-5750-93e0-05faf6d05430|75710349-7878-4941-b103-497878e9416b|MUTO-INTL|See analysis `2e13debc-45ee-44c1-93de-bc45eed4c1af`|
|c5937a93-8b4b-58ca-bcef-27ee479aec1a|89ecc5ae-64f6-4505-acc5-ae64f6550595|MUTO-INTL|SUPPRESSED|
|d2e59446-8fec-5b1f-939a-460ee0d64e4d|d3be4e4e-4720-4bfb-be4e-4e4720abfb78|MUTO-INTL|See analysis `e342e297-e315-4671-82e2-97e3154671f9`
|585f5ad4-111d-5cad-9295-14f7554039b8|26f10c29-5411-4e2a-b10c-295411ae2acf|MUTO-INTL|See analysis `06409701-5652-4490-8097-0156520490f1`
- [x] no action for `03208477-4703-54b9-919f-3394c91184b5` as associated analysis is `SUPRESSED`
- [ ] Suppress analyses
- [x] Retrigger alignments

		
ARGO	submission	
------------------
|objectId|analysisId|studyId|Notes|
|----|---|---|---|
|b2bed8da-7bf0-53eb-be49-0e93b0dfa852|2d2dac2f-49eb-4f1d-adac-2f49eb5f1d15|P1000-US|[UNPUBLISHED and sample will be removed](https://github.com/icgc-argo/workflow-roadmap/issues/419)|
|5b8636ba-059f-5d52-ba2c-dd40fdb73bcc|e26a8fe8-2678-44e6-aa8f-e8267894e6a1|POG-CA| UNPUBLISHED and program notified
|1820e4c6-ad59-573d-b168-6778f3e09a59|a82ed194-974a-455a-aed1-94974a455a8c|POG-CA|Alignment Complete|
|a2cf2a90-0511-54fa-92fb-29c5fb92ac74|560b2915-983e-433a-8b29-15983ee33a54|P1000-US|[UNPUBLISHED and sample will be removed](https://github.com/icgc-argo/workflow-roadmap/issues/419)|
|35881d2b-8214-5837-9ea2-3c46ff571394|0a4f8e03-976c-4be0-8f8e-03976c4be058|MUTO-INTL|UNPUBLISHED and program notified|
|5b8636ba-059f-5d52-ba2c-dd40fdb73bcc|6f8c8772-a69d-4c26-8c87-72a69dbc262e|POG-CA|UNPUBLISHED and program notified|
- [ ] Suppress analyses
- [ ] Inform programs for resubmission

**Comment by justincorrigible** [comment]
Closing as Done
