### ISSUE TITLE
Delete RNA samples for P1000-US

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#394]
Per Cam Karnes (ckarnes@nygenome.org) email, they'd like to remove RNA samples associated with the following donors:
```
NYGC254
NYGC252
NYGC303
NYGC309
NYGC315
NYGC379
NYGC384
NYGC77
NYGC81
```

Items to do:
- [x] Confirm with Cam the identified samples are correct
- [x] Suppress analyses in submission
- [x] Remove specimens and samples in clinical (confirm donor are not affected)
- [x] Remove samples and specimen in submission

The following files have been identified:
https://docs.google.com/spreadsheets/d/1GiODkxZDH5SIfUxKR7PZN08cXT8QhfoIDMno5WYFWmw/edit?usp=sharing

**Comment by edsu7** [comment]
Jon cleared most samples in both clinical and dereference them in submission song. Specimens and samples remaining for `NYGC252` and `NYGC254` as there were unconfirmed DNA-seq needed to be suppressed.

Will contact NYGC to verify these analyses can be deleted.

**Comment by edsu7** [comment]
Cam added more samples to remove. Jon has assisted to remove those.

Regarding `NYGC252` and `NYGC254`, multiple donor records cannot sit empty (system assigns null to them). For now `NYGC252` is empty and `NYGC254` has a dummy placeholder.

This allows samples and specimens to be submitted for `NYGC252` and `NYGC254`. The placeholder will be removed once Cam informs us.

**Comment by edsu7** [comment]
More samples have been registered under `NYGC252` and `NYGC254`. Placeholder can be removed. Will inform @joneubank

**Comment by justincorrigible** [comment]
Closing as completed. Program has been informed of and acknowledged the change
