### ISSUE TITLE
MUTO-INTL first batch of 515 donors alignment QC

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#398]
Alignment worksheet: https://docs.google.com/spreadsheets/d/13uxLJEjv5m6Q4nNOAsgeIKs8gm2rMctBK2CDXL5c4lU/edit#gid=834210998

Status - 1030 samples in total
Until Nov 22: All 1030 samples alignment have completed.

This ticket needs to QC the alignment and address any jobs or output files which are not in good shape. 
Re-run the jobs in Cumulus RDPC.

**Comment by lindaxiang** [comment]
515/515 donors (1030 samples) have all finished alignments.
The following 7 samples need to suppressed the analysis from duplicated runs. 
```
SA610791
SA610507
SA610848
SA611013
SA610921
SA610953
SA610479
```

**Comment by justincorrigible** [comment]
closing as completed with DR 8
