### ISSUE TITLE
MUTO-INTL first batch of 515 donors Mutect2 variant calling QC

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#399]
Mutect2 worksheet: https://docs.google.com/spreadsheets/d/13uxLJEjv5m6Q4nNOAsgeIKs8gm2rMctBK2CDXL5c4lU/edit#gid=20816066

Nov 22 Status - 515 donors in total, 499/515 completed. 6/515 failed due to input alignments downloading issue.

This ticket is to debug the failed jobs and re-run the jobs in Cumulus RDPC.

**Comment by lindaxiang** [comment]
All 515/515 donors have completed Mutect2 variant calling.

**Comment by justincorrigible** [comment]
Closing as completed with DR 8
