### ISSUE TITLE
Workflow Run Failure: OxoG

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#4]
## Detailed Description
![image](https://user-images.githubusercontent.com/15824252/77325838-4fcc6400-6cef-11ea-82ef-25f18ab07a02.png)

## List all runids affected
wes-d48d124cab8348f9aa2c2f0397effcbf

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by junjun-zhang** [comment]
Same job has been tested on QA K8S with run_id wes-213aa6bf860f492c8a5e7e6abc8230ee, it completed successfully.

This is likely a transient workflow execution issue due to high load.
