### ISSUE TITLE
MUTO-INTL first batch of 515 donors sanger variant calling QC

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#400]
Sanger worksheet: https://docs.google.com/spreadsheets/d/13uxLJEjv5m6Q4nNOAsgeIKs8gm2rMctBK2CDXL5c4lU/edit#gid=955963386

Nov.22th Status - 515 donors in total, 435/515 completed. 10 failed jobs, 58 queued jobs, 2 still running jobs.

This ticket is to debug failed jobs, QC the results,  and start new jobs on cumulus rdpc.

**Comment by lindaxiang** [comment]
445/515 completed sanger calls.

**Comment by justincorrigible** [comment]
Ticket to be rolled over to DR 9+

**Comment by edsu7** [comment]
Rolled over to 
https://github.com/icgc-argo/workflow-roadmap/issues/429
