### ISSUE TITLE
Planning: Target-Seq analysis workflow

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#402]
Context: https://docs.google.com/document/d/1TcHswu3bbgc-qXGnjsXjCUqOvDbT7aPJPaEIvUSfmlM/edit
Major considerations:
1. The interval files are provided given the “target_capture_kit” information
2. Add variant callers which support tumour-only and panel variant calling

**Comment by edsu7** [comment]
Completed.
