### ISSUE TITLE
Gender swap for P1000-US

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#403]
Following specimens need a correction to their gender in submission song and clinical's `sample_registration`.

| SubmitterDonorId  | SubmitterSpecimenId | SubmitterSampleId | Current Value | Updated Value |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| NYGC315  | NYGC315NormalDNA  | NYGC315NormalDNA-L1-RCRK128  | Female |  Male  | 
| NYGC315 | NYGC315TumorDNA  | NYGC315TumorDNA-L1-RPEL136 | Female  |  Male  |

**Comment by joneubank** [comment]
Data updated.

**Comment by justincorrigible** [comment]
closing as completed
