### ISSUE TITLE
Process P1000-US workflows

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#404]
P1000-US workflow status: https://docs.google.com/spreadsheets/d/17cyMniEtzoV2565vmyvFmVm2YqLV817vtrZjq6bTuuE/edit?usp=sharing

**Comment by edsu7** [comment]
Alignment:
77/78

Notes:
DO253941 - Processed one normal and one tumour , but submitter registered 2 normals.
DO253962 - to be processed

Mutect2:
55/78

Notes:
20 are in progress

**Comment by edsu7** [comment]
Closing.

Remaining jobs will be rolled over to:
- Aligments : https://github.com/icgc-argo/workflow-roadmap/issues/427
- Mutect2 : https://github.com/icgc-argo/workflow-roadmap/issues/428
