### ISSUE TITLE
MUTO-INTL fix matching normal

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#405]
Fix normalIds for the following below. 
Should be `NNNNb2` instead of `NNNNb` however `NNNNb2` samples are not registered. Notified program and to clarify and perhaps register the missing normal samples first.

```
"PD50393a",
"PD50397a",
"PD50401a",
"PD50403a",
"PD50404a",
"PD50405a",
"PD50406a",
"PD50408a",
"PD50411a",
"PD50412a",
"PD50413a",
"PD50415a",
"PD50420a",
"PD50421a",
"PD50422a",
"PD50425a",
"PD50438a",
"PD50440a",
"PD50441a",
"PD50442a",
"PD50443a",
"PD50444a",
"PD50462a",
"PD50607a",
"PD51235a"
```

**Comment by edsu7** [comment]
The following samples have been registered:
```
PD50415b2
PD50403b2
PD50607b2
PD50422b2
PD50401b2
PD50440b2
PD50406b2
PD50411b2
PD50442b2
PD50408b2
PD50405b2
PD50404b2
PD50412b2
PD50421b2
PD50420b2
PD50413b2
PD50462b2
PD50443b2
PD50441b2
PD50393b2
PD50397b2
PD50444b2
PD50425b2
PD51235b2
PD50438b2
```
"B" counterparts have not be deregistered as ongoing clinical submissions locks the system preventing changes.

Additionally in SONG `PD50393a`/`8047a709-8b73-4dec-87a7-098b73cdec11`'s `matchedNormalSubmitterSampleId` will have to be altered from `PD50393b` to `PD50393b2`

**Comment by joneubank** [comment]
Data updated.

**Comment by justincorrigible** [comment]
Awaiting for the program to finish their submission, before we can unregister these records

**Comment by edsu7** [comment]
Thomas has responded and unblocked.

"B" counterparts have been deregistered.
