### ISSUE TITLE
Cumulus RDPC workflows benchmark 

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#408]
We're using P1000-US DNA-Seq alignment jobs as dataset for benchmark. The purposes are to determine:
- Proper cpu/memory setting for running each DNA-Sequencing task, especially bwa-mem module
- Proper number of bwa-mem tasks per node
- Max number of jobs per workDir

**Comment by lindaxiang** [comment]
1. Cluster setting between Jan 2-14, 2024
1 job/workDir
14 nodes with 64CPU/128GB
bwa-mem request: 18cpu/56GB

**Comment by justincorrigible** [comment]
To confirm whether we still need this ticket

**Comment by edsu7** [comment]
Second update see:
https://docs.google.com/presentation/d/1QThEXonaT9zcEjs8NfNqNuPy6qsoJnDeavTgeWYMO8U/edit#slide=id.g2e1d6ca196e_0_23

Conclusion:
Not entirely comparable as workflows were mainly mutect2 and less IO heavy compared to alignments, therefore may not reflect refactor changes.

Action items:
- open new ticket to explore once more alignment workflows are available
