### ISSUE TITLE
Increase allowed max dna seq alignment jobs per workDir in Cumulus RDPC Prod

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#409]
We will increase allowed max dna seq alignment jobs per workDir in Cumulus RDPC Prod to test the NFS I/O performance.
Current it is 1 job/workDir, will increase to 5 job/workDir.

**Comment by UmmulkiramR** [comment]
each work directory can currently hold 6 dna seq jobs.

**Comment by justincorrigible** [comment]
Closing as Done
