### ISSUE TITLE
Separate wf jobs into dedicated namespace

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#41]
- Separate the workflow job namespace from the service namespace. 
--- Services will be in  `rdpc-collab-dev`, `rdpc-collab-qa`, and `rdpc-collab-prod` environments 
--- make the namespace and point workflow management to talk to `wes` namespace where the wf pods will launch 
--- `rdpc-wes-dev`, `rdpc-wes-qa`, and `rdpc-wes-prod` environments 

- Assign the network policies for the namespace (follow the map)
---- wf management in infra namespace needs to schedule in the `wes` namespace
---- `wes` namespace pods need to report to replay in the infra namespace

- Echo config for `rdpc-wes-dev`, `rdpc-wes-qa`, and `rdpc-wes-prod` environments 

Environments:
- [x] rdpc-wes-dev
- [x] rdpc-wes-qa
- [x] rdpc-wes-prod

**Comment by rosibaj** [comment]
- Dev is completed
- want to make sure this is working with application first. this means waiting on confirmation of: https://github.com/icgc-argo/roadmap/issues/585

**Comment by akachru-github** [comment]
Rob is doing the final set of work to enable emptydir here https://github.com/icgc-argo/roadmap/issues/585
@yalturmes will confirm the work done for this ticket up until now. We will then close this ticket and create a new one for production provisioning of the new namespace which is dependent on Rob's benchmarking / testing of emptydir.

**Comment by akachru-github** [comment]
Emptydir is now working in the DEV environment. New tikets have been created to benchmark the use of Emptydir to measure the improvements in DEV. 
If Emptydir passes initial set of tests, the next step would be to deploy this setup into QA and subsequently Prod.

**Comment by akachru-github** [comment]
@rosibaj , @lepsalex , @lindaxiang , @junjun-zhang , @hknahal , 

The devops work to support support emptydir in QA will be disruptive. We can talk more about how we want to coordinate the devops work as @yalturmes can likely pick this up next week some time.

**Comment by akachru-github** [comment]
This is done. 
Empty is in prod and functional.
