### ISSUE TITLE
Update whole exome sequencing samples song analysis in QA/Dev

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#411]
For both submission-song, song, and intermediate-song

**Comment by edsu7** [comment]
- [x] Do an audit on each of the SONGs
(include `analysisId`,`studyID`,`schema ver`,`analysis type` (make sure is WXS and Target-seq)
- [x] Start with submission SONG version
   - [x] Confirm latest schemas are correct and following https://github.com/icgc-argo/argo-metadata-schemas/tree/master/schemas
   - [x] identify the changes from earliest schema to latest
   - [x] Patch analyses to match current schema
- [x] Do as above but for other SONG analysis types

**Comment by guanqiaofeng** [comment]
# Submission Song

### 1. Retrieve all published program names from submission song - Study - GetAllStudyIds
https://submission-song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Study/findAllStudiesUsingGET

Program list:
[
  "DASH-CA",
  "TEST-QA",
  "TEST-INTL",
  "RDPCDEV-CA",
  "TEST-PR",
  "TCRB-CA",
  "APGI-AU",
  "DATA-CA",
  "TEST-CA",
  "SEQ-CA",
  "DEMO-CA",
  "UBCPC-CA",
  "TEST-GR"
]

### 2. Retrive all published analysis of the above studies from Submission Song - Analysis - GetAnalysesForStudy 
https://submission-song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Analysis/getAnalysisUsingGET_1

Download the json files as PROGRAM_ID_NAME.json

DASH-CA.json
TEST-QA.json
TEST-INTL.json
RDPCDEV-CA.json
TEST-PR.json
TCRB-CA.json
APGI-AU.json
DATA-CA.json
TEST-CA.json
SEQ-CA.json
DEMO-CA.json
UBCPC-CA.json
TEST-GR.json

### 3. Write a python code to extract analysisId, studyID, schema ver ,analysis type when analysis type is WXS or Target-seq. 

```
python3 extract_all_print_no_match.py
```
Output (Print out programs with no WXS or Target-seq analysis)
```
Data extracted and written to out.tsv successfully.
Files with zero matches:
APGI-AU.json
TEST-INTL.json
TEST-GR.json
UBCPC-CA.json
DEMO-CA.json
DATA-CA.json
TEST-CA.json
```

out.tsv (summary of all WXS and Target-seq analysis and their current analysis schema, total 44)
<img width="757" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHc0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1191affb36865b2e26a45b77e0e6eb341d105d77/image.png" alt="image.png" />

### 4. Submission Song Schemas
Retrive all schema for Submission Song sequencing_experiment analysisType (total 12, 1-12, newest version: 12)

https://submission-song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Schema/getAnalysisTypeVersionUsingGET

Download each schema jason file:
sequencing_experiment_schema1.json
sequencing_experiment_schema2.json
sequencing_experiment_schema3.json
sequencing_experiment_schema4.json
sequencing_experiment_schema5.json
sequencing_experiment_schema6.json
sequencing_experiment_schema7.json
sequencing_experiment_schema8.json
sequencing_experiment_schema9.json
sequencing_experiment_schema10.json
sequencing_experiment_schema11.json
sequencing_experiment_schema12.json --latest

### 5. Version updates
Versions which has updates in terms "WXS" or "Targeted-Seq": 1, 2, 9, 11, 12

#### Schema 1
<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69acd063e7cba6f201316a2957447e130058f2d7/Screenshot%202024-02-12%20at%204.28.40%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.40 PM.png" />

#### Schema 2 <== allowing "Targeted-Seq"
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d9c9ce50fce72fd8fe2052fce3346cc857f6ba1/Screenshot%202024-02-12%20at%204.28.55%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.55 PM.png" />

#### Schema 9 <== added 3 required fields "target_capture_kit", "capture_target_regions", "primary_target_regions"
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--911641231f932260ffec6c3ed1a7671cf8063aa0/Screenshot%202024-02-12%20at%204.28.55%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.55 PM.png" />

<img width="503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHhQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aca7de2e81b6503cca0064940095ea4105c79210/Screenshot%202024-02-12%20at%204.25.06%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.25.06 PM.png" />

#### Schema 11 <== added format requirement for the newly added three fields
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce6f38826be9b9fa548925f14031c8e79daed181/Screenshot%202024-02-12%20at%204.28.55%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.55 PM.png" />

<img width="949" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVZQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3d515b9c183880d68bca5890ed55d608b94e9c1/Screenshot%202024-02-12%20at%204.26.18%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.26.18 PM.png" />

**Comment by guanqiaofeng** [comment]
# Song Song

### 1. Retrieve all published program names from Song song - Study - GetAllStudyIds
https://song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Study/findAllStudiesUsingGET

[
  "TEST-CA",
  "TEST-PR",
  "OCCAMS-GB",
  "EUCANCAN-BE",
  "PACA-CA",
  "PTC-SA",
  "JAS-CA",
  "DASH-CA",
  "ROSI-RU",
  "TEST-QA",
  "APGI-AU",
  "RDPCDEV-CA",
  "JASTEST-QA",
  "TEST-TCRB",
  "TCRB-CA",
  "TEST-JP",
  "RAND-CA",
  "TEST-GR",
  "SEQ-CA",
  "UBCPC-CA",
  "MUTO-INTL",
  "LUCA-KR"
]

### 2. Retrive all published analysis of the above studies from Song song - Analysis - GetAnalysesForStudy 
https://song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Analysis/getAnalysisUsingGET_1

Download the json files as PROGRAM_ID_NAME_song.json

TEST-CA_song.json
OCCAMS-GB_song.json
EUCANCAN-BE_song.json
PACA-CA_song.json
PTC-SA_song.json
JAS-CA_song.json
DASH-CA_song.json
ROSI-RU_song.json
TEST-QA_song.json
APGI-AU_song.json
RDPCDEV-CA_song.json
JASTEST-QA_song.json
TEST-TCRB_song.json
TCRB-CA_song.json
TEST-JP_song.json
RAND-CA_song.json
TEST-GR_song.json
SEQ-CA_song.json
UBCPC-CA_song.json
MUTO-INTL_song.json
LUCA-KR_song.json

* TEST-PR Error: Gateway Time-out (504)

### 3. Write a python code to extract analysisId, studyID, schema ver ,analysis type when analysis type is WXS or Target-seq. 

```
python3 extract_all_print_no_match.py
```
Output (Print out programs with no WXS or Target-seq analysis)
```
Data extracted and written to out.tsv successfully.
Files with zero matches:
UBCPC-CA_song.json
TEST-GR_song.json
LUCA-KR_song.json
MUTO-INTL_song.json
TEST-CA_song.json
TEST-TCRB_song.json
TEST-JP_song.json
RAND-CA_song.json
JAS-CA_song.json
OCCAMS-GB_song.json
JASTEST-QA_song.json
EUCANCAN-BE_song.json
```

out.tsv (summary of all WXS and Target-seq analysis and their current analysis schema, total 668)
<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTA2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f01f417f093ee870169346e6adf49c3801dcbc3/image.png" alt="image.png" />

<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkE2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7421479a00494b6e5a93c371ce8a43d35317095b/image.png" alt="image.png" />

### 4. AnalysisType involved in WXS or Target-seq analysis (total 5)
```
cut -f 5 out.tsv | sort | uniq
```
```
analysisType
qc_metrics
sequencing_alignment
variant_calling
variant_calling_supplement
variant_processing
```

```
cut -f 5,6 out.tsv | sort | uniq | sort  
```
```
analysisType    analysisTypeVersion
qc_metrics      13
qc_metrics      14
qc_metrics      15
qc_metrics      18
qc_metrics      21
qc_metrics      23
qc_metrics      24
sequencing_alignment    10
sequencing_alignment    11
sequencing_alignment    15
sequencing_alignment    17
sequencing_alignment    18
sequencing_alignment    9
variant_calling 13
variant_calling 9
variant_calling_supplement      10
variant_processing      1
variant_processing      2
```

Lowest version of each analysis type:
qc_metrics      13
sequencing_alignment    9
variant_calling 9
variant_calling_supplement      10
variant_processing      1

### 5. Submission Song Schemas
Retrive all schema for Song Song in analysisTypes (from the lowest version identified above to the latest version):

https://song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Schema/getAnalysisTypeVersionUsingGET

qc_metrics      (version 13-24, newest 24)
sequencing_alignment    (version 9-18, newest 18)
variant_calling (version 9-15, newest 15)
variant_calling_supplement      (version 10-12, newest 12)
variant_processing      (version 1-3, newest 3)

Download each schema jason file:
..

### 6. Schema versions which has updates in terms "WXS" or "Targeted-Seq"
#### variant_processing (1, 3)
#### Schema 1/2
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ZQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d762aa8b5e2c98a76560403ac3f857287140ec6/Screenshot%202024-02-12%20at%204.28.55%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.55 PM.png" />


#### Schema 3 <==added 3 required fields "target_capture_kit", "capture_target_regions", "primary_target_regions" and the pattern setting
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05QQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc900df2dd45b0eddf1469bce8fe08a5d27de456/Screenshot%202024-02-12%20at%204.28.55%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.55 PM.png" />

<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7ae49151a1119af73be9eda8b626d55dab20e00/Screenshot%202024-02-12%20at%204.51.41%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.51.41 PM.png" />

#### variant_calling_supplement (10, 11, 12 same)
#### Schema 10/11/12
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d122e2e5595e36c8538e2b7770c83253363230ef/Screenshot%202024-02-12%20at%204.28.55%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 4.28.55 PM.png" />

variant_calling (9-15)

**Comment by guanqiaofeng** [comment]
## Schema Roadmap
<img width="1675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a6e589e9cf6c33ece5d1d5cd9178813ccef3653/Screenshot%202024-02-14%20at%204.43.58%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.43.58 PM.png" />

A3:
<img width="468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ff776df0c48dc023555e96041546d8ac3b7d9a4/A3.png" alt="A3.png" />

A5:
<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlJqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78fe22801af5cca87312a4041716b166841ac924/A5.png" alt="A5.png" />

A6: 
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e50dcd7058acdb3f4a435d96eb7feb48f010f3a9/A6.png" alt="A6.png" />

Bt (t means "type"):
<img width="503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlpqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec571b08f924ba2b062f33da7592884e3646ff51/Bt.png" alt="Bt.png" />

Btp (t: type; p: pattern):
<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56658e9987cda87e003b4a03a527b0165710e9aa/Btp.png" alt="Btp.png" />

**Comment by guanqiaofeng** [comment]
# Song_submission schema update results:
## Total 44 analysis, 38 updated successfully
<img width="630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d6640c745f28ae455fcc5472c5ccf8e1f0a5a16/Screenshot%202024-02-14%20at%204.49.40%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.49.40 PM.png" />

## 6 remaining: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkpjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95e0a90b6920aadada6705cd70ceb20dd5c8c3ad/Screenshot%202024-02-14%20at%204.45.44%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.45.44 PM.png" />

# Song_song schema update results:
## Total 668 analysis, 646 updated successfully
<img width="630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--931f4a4c58bccbc5711fbde36244ee639ba13c59/Screenshot%202024-02-14%20at%204.49.40%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.49.40 PM.png" />

## 22 remaining: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjFjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--647aa1bf557ff1d9a8dfe76e64d50b2094f5daf3/Screenshot%202024-02-14%20at%204.46.40%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.46.40 PM.png" />

**Comment by guanqiaofeng** [comment]
Tried to verify whether it is data sanity issue for publish error 409

```
{
  "errorId": "mismatching.storage.object.checksums",
  "httpStatusCode": 409,
  "httpStatusName": "CONFLICT",
  "requestUrl": "https://song.rdpc-qa.cumulus.genomeinformatics.org/studies/TCRB-CA/analysis/publish/454827e1-ffd3-4848-8827-e1ffd3684825?ignoreUndefinedMd5=false",
  "datetime": "2024-02-15T20:27:31.311Z[UTC]",
  "timestamp": 1708028851311,
  "message": "[AnalysisService::mismatching.storage.object.checksums] - Found files with a mismatching md5 checksum in the storage server. ObjectIds with an undefined md5 checksum(1): [6742cf46-09ab-582c-8f55-3fdea43eda2f]. The analysisId '454827e1-ffd3-4848-8827-e1ffd3684825' cannot be published until all files with an undefined checksum are ignored and ones with a defined checksum are matching",
```

Checked these two cases by the following step:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8189aae663283d6c8c71a03d9df709f7d4147f1a/Screenshot%202024-02-15%20at%203.59.58%E2%80%AFPM.png" alt="Screenshot 2024-02-15 at 3.59.58 PM.png" />

1. set `?ignoreUndefinedMd5=true"` and publish the analysis in Song API UI
2. download the data with score-client
3. compute the md5 of downloaded files and compare to md5 in Song

```
gfeng@ml7010-gfeng Work % md5 TCRB-CA.DO262483.SA622770.wxs.20230113.aln.cram
MD5 (TCRB-CA.DO262483.SA622770.wxs.20230113.aln.cram) = 23db499a896e7e528a4051a33a2ba0e6
gfeng@ml7010-gfeng Work % md5 TCRB-CA.DO262483.SA622770.wxs.20230113.aln.cram.crai 
MD5 (TCRB-CA.DO262483.SA622770.wxs.20230113.aln.cram.crai) = 941d80fc2eb754e79b59bb58bdfc7ecd
gfeng@ml7010-gfeng Work % 
gfeng@ml7010-gfeng Work % md5 SEQ-CA.DO263272.SA624742.wxs.20230602.aln.cram.crai 
MD5 (SEQ-CA.DO263272.SA624742.wxs.20230602.aln.cram.crai) = d904ca19ce9e6e902135e8cbf85eab79
gfeng@ml7010-gfeng Work % md5 SEQ-CA.DO263272.SA624742.wxs.20230602.aln.cram     
MD5 (SEQ-CA.DO263272.SA624742.wxs.20230602.aln.cram) = f055f510c229f61c22ff0f4b90725897
```

The md5 values all match.
