### ISSUE TITLE
Clinical and molecular data submission tests in QA

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#412]
- Resource
Submission Overview: https://docs.icgc-argo.org/docs/submission/submission-overview
Sample registration: 
                                     https://docs.icgc-argo.org/docs/submission/registering-samples
Clinical data submission: https://docs.icgc-argo.org/docs/submission/submitting-clinical-data
Molecular data submission: https://docs.icgc-argo.org/docs/submission/submitting-molecular-data
Example clinical & molecular data
https://drive.google.com/drive/u/1/folders/1xmUGM03CP_XD9-pXz0LrrVpJZWGBNKlv
- QA ENV
Platform: https://platform-ui.argo-qa.cumulus.genomeinformatics.org/
Mailhog: https://mailhog.argo-qa.cumulus.genomeinformatics.org/
molecular data submission: please use “-profile rpdc_qa,docker” instead of “-profile rdpc,docker”
- Output: Document with issues, feedback & suggestions

**Comment by guanqiaofeng** [comment]
## Data submission using ICGC ARGO platform
### 1. DEMO-CA
### 1.1 Sample registration
Successful with data provided
### 1.2 Clinical Data submission (3 error messages with data provided)
1.2.1 Error 1 & 2: Follow_up Interval_of_followup (343, 689) must be less than Donor Survival_time (229)
Fixation: Donor Survival_time change 229 --> 690

1.2.2 Error 3: Treatment and treatment_type files are required to be initialized together. Please upload a corresponding treatment file in this submission.
Fixation: Radiation submitter_treatment_id, change tr02 --> tr02_03

Successful after the 2 fixations

### 1.3 Molecular Data submission
To be done

### 2. TEST-CA
### 2.1 Sample registration
Error: "Samples can only be registered to a single specimen, this sample has already been registered to specimen BL201. Please correct your file of contact DCC to update the registered data."
Fix: submitter_sample_id: BL834 --> BL835

Successful after fixation
### 2.2 Clinical Data submission
Successful with data provided
### 2.3 Molecular Data submission
To be done

**Comment by guanqiaofeng** [comment]
## Molecular Data Submission -- Software installation
### I. Nextflow installation https://www.nextflow.io/
1. install SDK
   
`
curl -s "https://get.sdkman.io" | bash
`

`
source "/Users/gfeng/.sdkman/bin/sdkman-init.sh"
`

2. install java

`
sdk install java 17.0.6-amzn
`

3. install nextflow

```
cd /Users/gfeng/Documents/Programs
curl -s https://get.nextflow.io | bash
```

Error in this step:

```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

/Users/gfeng/Documents/Programs/nextflow: line 289: /bin/java: No such file or directory
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /bin/java
 NXF_OPTS: 
```

Solve it with the help of ChatGPT
find the path of java

```
which java
/Users/gfeng/.sdkman/candidates/java/current/bin/java

vim ~/.zshrc
```
added "export PATH=$PATH:/Users/gfeng/.sdkman/candidates/java/current/bin" in the begining of ~/.zshrc

rerun nextflow installation
```
curl -s https://get.nextflow.io | bash
```

Successful
```
N E X T F L O W
      version 23.10.1 build 5891
      created 12-01-2024 22:01 UTC (17:01 EDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io


Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /Users/gfeng
- you may complete the installation by moving it to a directory in your $PATH
```

add `export PATH=$PATH:/Users/gfeng` to ~/.zshrc 
```
source ~/.zshrc
```

Now `nextflow` command can be executed directly

### II Docker Installation https://docs.docker.com/desktop/install/mac-install/

1. install Rosetta 2
```
softwareupdate --install-rosetta
```
Successful

2. follow the above link
   
Successfully installed Docker

### III Singularity Installation https://docs.sylabs.io/guides/3.0/user-guide/installation.html
1. install homebrew (https://brew.sh/)
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/gfeng/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
brew help
```
Successful

2. Install vagrant and vagrant-box

```
brew install vagrant
brew cask install vagrant-manager
```
Successful

3. Install Virtualbox
Could not install virtualbox. Following is the error messge. Skip installing virtualbox for now.
```
Error: Cask virtualbox depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
```
Docker is enough to proceed molecular data submission. Will proceed without singularity for now.

**Comment by guanqiaofeng** [comment]
## Molecular Data Submission -- Download github workflow and do a dry run

```
git clone https://github.com/icgc-argo/argo-data-submission.git
cd argo-data-submission
nextflow run -preview main.nf -profile rdpc,docker -params-file example-params.local.json --api_token YOUR_API_TOKEN
```
Got the below output
```
N E X T F L O W  ~  version 23.10.1
* PREVIEW * null [ridiculous_leibniz] DSL2 - revision: 96123fbdeb
[-        ] process > ArgoDataSubmissionWf:sanityCheck        -
[-        ] process > ArgoDataSubmissionWf:checkCramReference -
[-        ] process > ArgoDataSubmissionWf:pGenExp            -
[-        ] process > ArgoDataSubmissionWf:valSeq             -
[-        ] process > ArgoDataSubmissionWf:uploadWf:songSub   -
[-        ] process > ArgoDataSubmissionWf:uploadWf:songMan   -
[-        ] process > ArgoDataSubmissionWf:uploadWf:scoreUp   -
[-        ] process > ArgoDataSubmissionWf:uploadWf:songPub   -
[-        ] process > ArgoDataSubmissionWf:submissionReceipt  -
[-        ] process > ArgoDataSubmissionWf:printOut           -

```

**Comment by guanqiaofeng** [comment]
## Molecular Data Submission -- DEMO-CA

Copied main.nf in the above github repository to working directory `/Users/gfeng/Documents/Work/Jan/Data-Submission/DEMO-CA/molecular`

Run the below code for data submission
```
nextflow run main.nf \
  -profile rdpc_qa,docker \
  --study_id DEMO-CA \
  --download_mode local \
  --experiment_info_tsv experiment.tsv \
  --read_group_info_tsv read_group.tsv \
  --file_info_tsv file.tsv \
  --api_token 1bc8de4e-7114-4312-a152-3d29351399e9
```
Got the below message
```
N E X T F L O W  ~  version 23.10.1
Launching `main.nf` [astonishing_saha] DSL2 - revision: 96123fbdeb
ERROR ~ No such file or directory: Can't find a matching module file for include: ./wfpr_modules/github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/song-score-upload@2.9.3/main.nf

 -- Check script 'main.nf' at line: 168 or see '.nextflow.log' file for more details
```
Will continue to work on it...

This issue is solved by updating the directory in line 168-177 of main.nf to actual local location

**Comment by guanqiaofeng** [comment]
Issues in molecular data submission and solution:
1. Update main.nf line 168-177 of to actual local location
2. Docker Image issue: run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before run nextflow
3. Update clinical url in nextflow.config line 79 from `https://clinical.qa.argo.cancercollaboratory.org` to `https://clinical.argo-qa.cumulus.genomeinformatics.org`
4. Upldate main.nf line 48 from `params.score_mem = 20` to `params.score_mem = 16`

Then it successed. 

```
nextflow run main.nf \
  -profile rdpc_qa,docker \
  --study_id DEMO-CA \
  --download_mode local \
  --experiment_info_tsv experiment.tsv \
  --read_group_info_tsv read_group.tsv \
  --file_info_tsv file.tsv \
  --api_token 1bc8de4e-7114-4312-a152-3d29351399e9 \
  --max_mem 2 --max_cpus 2 \
  -resume
 
N E X T F L O W  ~  version 23.10.1
Launching `main.nf` [peaceful_woese] DSL2 - revision: 0abfff030b
executor >  local (10)
[d8/3a9768] process > ArgoDataSubmissionWf:sanityCheck                                             [100%] 1 of 1 ✔
[d2/8fa56b] process > ArgoDataSubmissionWf:checkCramReference                                      [100%] 1 of 1 ✔
[60/82005e] process > ArgoDataSubmissionWf:pGenExp                                                 [100%] 1 of 1 ✔
[cc/4b1ed3] process > ArgoDataSubmissionWf:valSeq                                                  [100%] 1 of 1 ✔
[d0/eeb062] process > ArgoDataSubmissionWf:uploadWf:songSub (DEMO-CA)                              [100%] 1 of 1 ✔
[d9/43de52] process > ArgoDataSubmissionWf:uploadWf:songMan (fc64103f-7fa8-4ab7-a410-3f7fa81ab7cd) [100%] 1 of 1 ✔
[5b/5194b2] process > ArgoDataSubmissionWf:uploadWf:scoreUp (fc64103f-7fa8-4ab7-a410-3f7fa81ab7cd) [100%] 1 of 1 ✔
[f3/8636be] process > ArgoDataSubmissionWf:uploadWf:songPub (fc64103f-7fa8-4ab7-a410-3f7fa81ab7cd) [100%] 1 of 1 ✔
[dd/e71ef8] process > ArgoDataSubmissionWf:submissionReceipt                                       [100%] 1 of 1 ✔
[d5/a6f85a] process > ArgoDataSubmissionWf:printOut                                                [100%] 1 of 1 ✔

Payload JSON File : /Users/gfeng/Documents/Work/Jan/Data-Submission/DEMO-CA/molecular/work/60/82005e41af21e11c95f7357f72c3b3/22238313-dca3-4c85-be58-17348979a583.sequencing_experiment.payload.json
Analysis ID : fc64103f-7fa8-4ab7-a410-3f7fa81ab7cd
Submission TSV Receipt: /Users/gfeng/Documents/Work/Jan/Data-Submission/DEMO-CA/molecular/work/dd/e71ef860db3c411446bfe5e24cfa6c/fc64103f-7fa8-4ab7-a410-3f7fa81ab7cd_submission_receipt.tsv
Completed at: 23-Jan-2024 17:10:22
Duration    : 1m 2s
CPU hours   : 0.1
Succeeded   : 10

**Comment by guanqiaofeng** [comment]
# Molecular Data Submission -- TEST-CA

1. Run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before run nextflow
2. Asked Edmund to remove previous publication of TEST-CA, system catches duplicated submissions. The previous submission need to be unpublished before resubmit.
3. update experiment_local.tsv submitter_matched_normal_sample_id `SL834` to `SL835`

It seems successful, but the output is little different from DEMO-CA submission
```
nextflow run main.nf \                             
  -profile rdpc_qa,docker \
  --study_id TEST-CA \
  --download_mode local \
  --experiment_info_tsv experiment_local_update.tsv \
  --read_group_info_tsv read_group_local.tsv \
  --file_info_tsv file_local.tsv \
  --api_token 1bc8de4e-7114-4312-a152-3d29351399e9
N E X T F L O W  ~  version 23.10.1
Launching `main.nf` [astonishing_maxwell] DSL2 - revision: 0abfff030b
executor >  local (10)
[f8/1b9925] process > ArgoDataSubmissionWf:sanityCheck                                             [100%] 1 of 1 ✔
[92/d03165] process > ArgoDataSubmissionWf:checkCramReference                                      [100%] 1 of 1 ✔
[4f/18f797] process > ArgoDataSubmissionWf:pGenExp                                                 [100%] 1 of 1 ✔
[07/9558f8] process > ArgoDataSubmissionWf:valSeq                                                  [100%] 1 of 1 ✔
[ed/716472] process > ArgoDataSubmissionWf:uploadWf:songSub (TEST-CA)                              [100%] 1 of 1 ✔
[ea/fb8969] process > ArgoDataSubmissionWf:uploadWf:songMan (57704ccd-432c-4373-b04c-cd432cd373ab) [100%] 1 of 1 ✔
[50/2833cf] process > ArgoDataSubmissionWf:uploadWf:scoreUp (57704ccd-432c-4373-b04c-cd432cd373ab) [100%] 1 of 1 ✔
[6a/dee553] process > ArgoDataSubmissionWf:uploadWf:songPub (57704ccd-432c-4373-b04c-cd432cd373ab) [100%] 1 of 1 ✔
[12/35a4e1] process > ArgoDataSubmissionWf:submissionReceipt                                       [100%] 1 of 1 ✔
[45/07eb9c] process > ArgoDataSubmissionWf:printOut                                                [100%] 1 of 1 ✔

Payload JSON File : /Users/gfeng/Documents/Work/Jan/Data-Submission/TEST-CA/molecular/work/4f/18f7976e435883baba2ed996ea3dc8/050a3b41-39c0-4aef-a31d-93b028208a94.sequencing_experiment.payload.json
Analysis ID : 57704ccd-432c-4373-b04c-cd432cd373ab
Submission TSV Receipt: /Users/gfeng/Documents/Work/Jan/Data-Submission/TEST-CA/molecular/work/12/35a4e1744298421f7c67f5ef01cef6/57704ccd-432c-4373-b04c-cd432cd373ab_submission_receipt.tsv

```

**Comment by guanqiaofeng** [comment]
Verification of submission:
Method1. 1 Platform program dashboard. https://platform-ui.argo-qa.cumulus.genomeinformatics.org/submission/program/TEST-CA/dashboard
`Last update` date should be the new submission date. 
`Raw reads` (molecular data) number should reflect the data submitted.

Note: Platform information is not updated. So could not verify from this method.

Method2. Song submission API https://submission-song.rdpc-qa.cumulus.genomeinformatics.org/swagger-ui.html#/Analysis/readUsingGET 

Using Analysis ID and program ID, analysis (submission) details can be retrived by `ReadAnalysis`

I could verify the submission from this method. Submission is successful. <img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--176dbc56a9f181c8dfec7da4225ea5b7487aebf8/Screenshot%202024-01-26%20at%209.00.10%E2%80%AFAM.png" alt="Screenshot 2024-01-26 at 9.00.10 AM.png" />

**Comment by guanqiaofeng** [comment]
## Possible improvement for dev in molecular data submission: 

**Issue:** 
Submission pipeline is not applicable to Mac ARM64 

**Error message in submission**:
```
Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  Unable to fetch. Status code : 503
``` 
**Temporary solution for me to get away with this issue:**
run `export DOCKER_DEFAULT_PLATFORM=linux/amd64` before run nextflow pipleline

**Suggestion:** 
Make submission pipeline applicable to Mac ARM64, so users can submit molecular data with Mac arm64 system.

## Reminder for users in molecular data submission
1. Update main.nf line 168-177 of to actual local location
2. Upldate main.nf params.score_mem
line 48 from params.score_mem = 20 to params.score_mem = 16
when recieving error message like this:
```
Caused by:
  Process requirement exceeds available memory -- req: 20 GB; avail: 16 GB
```

**Comment by justincorrigible** [comment]
Closing ticket as completed
