### ISSUE TITLE
Correcting prod analyses object with data integrity issues  

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#416]
Following the conclusion of Jared's data audit:
https://docs.google.com/spreadsheets/d/1z3Xb0_5dcd7pYil4rUayJz61ey25KDNGDyeV1_jpSFo/edit#gid=201303263

57 objects remain corrupted post recopy.

Of those 57,  47 are `PUBLISHED`.

The 47 files (and 47 donors) are all alignment files and used downstream in variant call and qc analyses, thus if we regenerate the alignment files we should also regenerate thee downstream ones.

The number of objects (47 aforementioned + associated downstream) is 1287 of which 688 is also on file repo.

Audit report:
https://docs.google.com/spreadsheets/d/1Tj7SNvoSjka0VfVBfAEogvPPe4jg1SQWG840LEG3uPg/edit#gid=210385962

A follow up epic may be needed.

**Comment by justincorrigible** [comment]
Closing as Done
