### ISSUE TITLE
Data release 8.0 - data QC

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#418]
Need to QC the process data from MUTO, POG and P1000
- MUTO QC report: https://github.com/icgc-argo/workflow-roadmap/issues/391
- POG QC report: https://github.com/icgc-argo/workflow-roadmap/issues/422
- P1000 QC report: https://github.com/icgc-argo/workflow-roadmap/issues/423

Expected output:
- compile the list of donors, analysis, and objects to be released for DR8.0

**Comment by lindaxiang** [comment]
Processed genomic data release criteria:

**analysis workflow**|**QC criteria**|**analysisType**|**file access**
-----|-----|-----|-----
dna alignment|1. must have mutect2 or sanger called successfully <br />2. normal coverage > 25X, tumour coverage > 30X (use column `normal/tumour_estimated_coverage`)  <br />3. donors with multiple tumour/normal pairs must have all samples processed  | squencing_alignment, qc_metrics | controlled
sanger variant calling|1. exclude ASCAT failed donors<br />2. exclude purity < 30% donors<br />3. exclude purity=100% donors | variant_calling, qc_metrics | controlled
mutect2 variant calling |1. cross_sample_contamination <4% (use column `normal/tumour_mutect2_contamination`) | variant_calling, qc_metrics | controlled

**Comment by edsu7** [comment]
Results of QC + Notes per columns
[updated_DR8.2024-03-04.qc.xlsx](https://github.com/icgc-argo/workflow-roadmap/files/14487809/updated_DR8.2024-03-04.qc.xlsx)


Summary of results of DR8 ready files (excluding indices):

|study|objects|donors|analyses|
|--|--|--|--|
|MUTO-INTL|15123|448|4882|
|P1000-US|2814|67|469|
|Total|17937|515|5351|

Summary of results of DR8 ready files (including indices):

|study|objects|donors|analyses|
|--|--|--|--|
|MUTO-INTL|18091|448|4882|
|P1000-US|3082|67|469|
|Total|21173|515|5351|


List of `objectIds`,`donorIds` and `analysisIds`
[REVISED_DR8_2024-03-04.qc_files.xls](https://github.com/icgc-argo/workflow-roadmap/files/14515915/REVISED_DR8_2024-03-04.qc_files.xls)
- Revised, previous version included Sanger calls that did not meet critieria

~[DR8_2024-03-04.qc_files.xlsx]
(https://github.com/icgc-argo/workflow-roadmap/files/14487769/DR8_2024-03-04.qc_files.xlsx)~

**Comment by justincorrigible** [comment]
Closing as completed 👍
