### ISSUE TITLE
Japanese MONSTAR 2000 donor - XML - understanding data type and content

### ISSUE THREAD

**Issue by guanqiaofeng** [icgc-argo/workflow-roadmap#420]
Example data:
https://drive.google.com/drive/folders/1Pb7lnI1txPF8K2M1ntrBNIhJzV_hdrxy

Extract all the information from the xml file.

**Comment by guanqiaofeng** [comment]
Summary - update
https://docs.google.com/presentation/d/1NTMfot_2yGzRx8O2LPFH1wwSE-ukefk2/edit#slide=id.p1

short variant
https://docs.google.com/spreadsheets/d/1FZsLO9BYf43n4D1QWNJ0HUX4YHqVjUhn/edit#gid=1050629740

rearrangement
https://docs.google.com/spreadsheets/d/11zfOb2GvBitUz1XJUsOgpsxpkHZGb_pY/edit#gid=1974635432

**Comment by edsu7** [comment]
@lindaxiang and @edsu7 to review Guangqiao's findings

**Comment by guanqiaofeng** [comment]
Final output: 
https://drive.google.com/drive/folders/1w6y0f6CPYUNJt77_llGLmM0z6364XwkX
short variant: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHZWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d7361f154302349acab4e56219c21fec0d0fded/Screenshot%202024-03-12%20at%204.39.06%E2%80%AFPM.png" alt="Screenshot 2024-03-12 at 4.39.06 PM.png" />


rearrangement:
<img width="1400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHpWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59d5d811d082be7e9527b3bc1545b3ea954468a8/Screenshot%202024-03-12%20at%204.38.54%E2%80%AFPM.png" alt="Screenshot 2024-03-12 at 4.38.54 PM.png" />

**Comment by justincorrigible** [comment]
Closing as investigation has been completed
