### ISSUE TITLE
DR9 - QC ~1400 MUTO-INTL/POG-CA Donors

### ISSUE THREAD

**Issue by edsu7** [icgc-argo/workflow-roadmap#429]
@edsu7 can you take a look at the following QC criteria?

Processed genomic data release criteria:

**analysis workflow**|**QC criteria**|**analysisType**|**file access**
-----|-----|-----|-----
dna alignment|1. must have mutect2 or sanger called successfully <br />2. normal coverage > 25X, tumour coverage > 30X (use column `normal/tumour_estimated_coverage`)  <br />3. donors with multiple tumour/normal pairs must have all samples processed  | squencing_alignment, qc_metrics | controlled
sanger variant calling|1. exclude ASCAT failed donors<br /> | variant_calling, qc_metrics | controlled
mutect2 variant calling |1. cross_sample_contamination <4% (use column `normal/tumour_mutect2_contamination`) | variant_calling, qc_metrics | controlled

**Comment by edsu7** [comment]
To suppress:
- analysisIds associated with `wes-a4df7a50b59e4b7cba4225475db52c30`
  - `DO250000` already has run with open access calls `wes-79a9299f0c8444f59ec1843bb57730d4`
```
12567dd8-0721-4e94-967d-d807219e9418
86990ee0-c317-4b63-990e-e0c3174b63be
7669dda5-f4f6-44a2-a9dd-a5f4f6a4a2c9
58b3f5c2-5b5f-42f6-b3f5-c25b5f92f60e
a8ac1de3-5ba0-4664-ac1d-e35ba04664ac
437866d4-21a8-4ad3-b866-d421a88ad3ab
```
- analysisIds associated with `wes-e8fdc169af9b4e10a9201706c71a4de2`
  - `DO252093` already has run with calls `wes-63271bda2dee4194a1e3f5c0a3d3cf37`
```
760de433-b4bd-4e30-8de4-33b4bd1e308d
f09eca25-143d-4b4f-9eca-25143d3b4f66
fe25cad2-5aff-444d-a5ca-d25aff544d69
```

**Comment by edsu7** [comment]
Current summary of eligible donors based on QC metrics

[DR9_summary_report.xls](https://github.com/icgc-argo/workflow-roadmap/files/15287678/DR9_summary_report.xls)

Pinging @lindaxiang and @guanqiaofeng for review

**Comment by lindaxiang** [comment]
@edsu7 I found the follow analysis which may need attention:
MUTO-INTL
- The following 8 donors have generated sanger variant calling results in 2021, but they were recently re-running the sanger workflows. So the recent new runs' results will need to be suppressed.

**studyId**|**donorId**|**workflow\_name**|**old\_run\_id**|**old\_run\_complete\_date**|**new\_run\_id**|**new\_run\_complete\_date**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
MUTO-INTL|DO250007|sanger-wgs-variant-calling|wes-74c85dc74824415193591434f7fc6d18|2021-07-25 12:26|wes-c96e46f774824840ba815ba18e6059c2|2024-05-11 18:34
MUTO-INTL|DO250009|sanger-wgs-variant-calling|wes-69487332b04f4763b8194ecdc23c05e4|2021-07-25 11:29|wes-6d357325de134e88b4c963ac986c3a66|2024-05-11 15:18
MUTO-INTL|DO250003|sanger-wgs-variant-calling|wes-41510444576241f195b85973d8af0792|2021-07-25 0:46|wes-7d164f0f9ff841b2b7dabf7eb868338c|2024-05-11 13:32
MUTO-INTL|DO250008|sanger-wgs-variant-calling|wes-6c2b5093f56f473b8fb546387ef84eff|2021-07-25 7:29|wes-92c4cd3cb7c54990b04555bcd5054b25|2024-05-11 13:40
MUTO-INTL|DO250006|sanger-wgs-variant-calling|wes-c34a3e0b13e64e36a79be7f5b66ef4e2|2021-07-25 18:28|wes-292cc6cbb7554247aebd4d40e8c149e0|2024-05-12 1:36
MUTO-INTL|DO250002|sanger-wgs-variant-calling|wes-f2436f8b10a4472a9f246bc3fea6aa8d|2021-07-25 8:42|wes-6797dff1ac3a4fb081713b5bb6dfb3ed|2024-05-12 4:23
MUTO-INTL|DO250005|sanger-wgs-variant-calling|wes-3845044ef62e45a3aeeaa02b1bdb8406|2021-07-25 0:35|wes-d73fe47da7444f3997cf770351b1dccf|2024-05-12 5:10
MUTO-INTL|DO250004|sanger-wgs-variant-calling|wes-d0c6f25b417740feadff72df32b18dc5|2021-07-25 6:56|wes-16d50d9a3d9f49c3adbf5215e99b4666|2024-05-11 12:41

- Donor **DO250000**:  analysisIds associated with `wes-a4df7a50b59e4b7cba4225475db52c30` are all already in `UNPUBLISHED` state

POG-CA
- Donor: **DO252093** already run with calls `wes-63271bda2dee4194a1e3f5c0a3d3cf37`, however one of the inputs was suppressed for some reason: `56e6afad-d00f-4dbe-a6af-add00f4dbeb4`. Do we know the reason?
- Donor: **DO252253**
 has an alignment run `wes-f63059947de9492689d582a805797317`
 whose input analysis `6f8c8772-a69d-4c26-8c87-72a69dbc262e` is `UNPUBLISHED`. Do we know the reason why the input was suppressed? We will need to suppress it's output analysis `29830a95-8882-48e5-830a-95888288e5c5`


> To suppress:
> 
> * analysisIds associated with `wes-a4df7a50b59e4b7cba4225475db52c30`
>   
>   * `DO250000` already has run with open access calls `wes-79a9299f0c8444f59ec1843bb57730d4`
> 
> ```
> 12567dd8-0721-4e94-967d-d807219e9418
> 86990ee0-c317-4b63-990e-e0c3174b63be
> 7669dda5-f4f6-44a2-a9dd-a5f4f6a4a2c9
> 58b3f5c2-5b5f-42f6-b3f5-c25b5f92f60e
> a8ac1de3-5ba0-4664-ac1d-e35ba04664ac
> 437866d4-21a8-4ad3-b866-d421a88ad3ab
> ```
> 
> * analysisIds associated with `wes-e8fdc169af9b4e10a9201706c71a4de2`
>   
>   * `DO252093` already has run with calls `wes-63271bda2dee4194a1e3f5c0a3d3cf37`
> 
> ```
> 760de433-b4bd-4e30-8de4-33b4bd1e308d
> f09eca25-143d-4b4f-9eca-25143d3b4f66
> fe25cad2-5aff-444d-a5ca-d25aff544d69
> ```

**Comment by edsu7** [comment]
## Update:
> The following 8 donors have generated sanger variant calling results in 2021, but they were recently re-running the sanger workflows. So the recent new runs' results will need to be suppressed.
- graphql query did not populate properly as a result these analyses were rerun.
<img width="1850" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d30b6b5693eeba25cd1f1b9cd4d53338f81482eb/image.png" alt="image.png" />
- Analyses affiliated with runs to be suppressed
>Donor `DO2500001`: analysisIds associated with `wes-a4df7a50b59e4b7cba4225475db52c30` are all already in UNPUBLISHED state
- unpublished to not interfere with QC
> Donor: `DO252093` already run with calls `wes-63271bda2dee4194a1e3f5c0a3d3cf37`, however one of the - inputs was suppressed for some reason: `56e6afad-d00f-4dbe-a6af-add00f4dbeb4`. Do we know the reason?
- run `wes-e8fdc169af9b4e10a9201706c71a4de2`  used tumour alignment `8c2a20cb-b133-4c66-aa20-cbb133ec660b`
- run `wes-63271bda2dee4194a1e3f5c0a3d3cf37` used tumour alignment `56e6afad-d00f-4dbe-a6af-add00f4dbeb4`
- `56e6afad-d00f-4dbe-a6af-add00f4dbeb4` was unpublished as a duplicate `8c2a20cb-b133-4c66-aa20-cbb133ec660b` was kept
- analyses associated with `wes-63271bda2dee4194a1e3f5c0a3d3cf37` should be unpublished and those associated with `wes-e8fdc169af9b4e10a9201706c71a4de2` should be republished
> Donor: `DO252253`
has an alignment run `wes-f63059947de9492689d582a805797317`
whose input analysis `6f8c8772-a69d-4c26-8c87-72a69dbc262e` is UNPUBLISHED. Do we know the reason why the input was suppressed? We will need to suppress it's output analysis `29830a95-8882-48e5-830a-95888288e5c5`
- run `wes-f63059947de9492689d582a805797317` had failed at QC generation step but alignment went through `29830a95-8882-48e5-830a-95888288e5c5`
- sample was not rerun b/c source `6f8c8772-a69d-4c26-8c87-72a69dbc262e` was corrupted as per https://github.com/icgc-argo/workflow-roadmap/issues/392#issuecomment-1944992340

## Actions:

### Analyses to REPUBLISH
|Run|Analysis|Study|
|--|--|--|
|`wes-e8fdc169af9b4e10a9201706c71a4de2`|`760de433-b4bd-4e30-8de4-33b4bd1e308d`|`POG-CA`|
|`wes-e8fdc169af9b4e10a9201706c71a4de2`|`f09eca25-143d-4b4f-9eca-25143d3b4f66`|`POG-CA`|
|`wes-e8fdc169af9b4e10a9201706c71a4de2`|`fe25cad2-5aff-444d-a5ca-d25aff544d69`|`POG-CA`|

### Analyses to UNPUBLISH
|Run|Analysis|Study|
|--|--|--|
|`wes-c96e46f774824840ba815ba18e6059c2`|`c55dc153-488b-4a13-9dc1-53488bca134d`|`MUTO-INTL`|
|`wes-c96e46f774824840ba815ba18e6059c2`|`c6055da5-85dc-49ff-855d-a585dce9ff87`|`MUTO-INTL`|
|`wes-c96e46f774824840ba815ba18e6059c2`|`70341068-904f-4522-b410-68904f4522a9`|`MUTO-INTL`|
|`wes-c96e46f774824840ba815ba18e6059c2`|`b9c0e450-842f-4d7b-80e4-50842f5d7b17`|`MUTO-INTL`|
|`wes-c96e46f774824840ba815ba18e6059c2`|`b77c8991-2f93-40da-bc89-912f93b0daee`|`MUTO-INTL`|
|`wes-c96e46f774824840ba815ba18e6059c2`|`c1379b77-f025-43a6-b79b-77f02523a673`|`MUTO-INTL`|
|`wes-6d357325de134e88b4c963ac986c3a66`|`34e1f714-e59f-4f65-a1f7-14e59fff657c`|`MUTO-INTL`|
|`wes-6d357325de134e88b4c963ac986c3a66`|`6d58f65c-e03e-4385-98f6-5ce03ee385a0`|`MUTO-INTL`|
|`wes-6d357325de134e88b4c963ac986c3a66`|`294573ac-3250-4211-8573-ac3250221171`|`MUTO-INTL`|
|`wes-6d357325de134e88b4c963ac986c3a66`|`679e56ce-7660-451f-9e56-ce7660051fc2`|`MUTO-INTL`|
|`wes-6d357325de134e88b4c963ac986c3a66`|`c8b20881-3d1f-4b99-b208-813d1f0b9933`|`MUTO-INTL`|
|`wes-6d357325de134e88b4c963ac986c3a66`|`19e1819f-bba2-4690-a181-9fbba266901e`|`MUTO-INTL`|
|`wes-7d164f0f9ff841b2b7dabf7eb868338c`|`a225c265-18f8-422f-a5c2-6518f8d22f79`|`MUTO-INTL`|
|`wes-7d164f0f9ff841b2b7dabf7eb868338c`|`acb15727-ad44-40c3-b157-27ad4490c3a0`|`MUTO-INTL`|
|`wes-7d164f0f9ff841b2b7dabf7eb868338c`|`8b364fd1-e83d-4c48-b64f-d1e83d7c484b`|`MUTO-INTL`|
|`wes-7d164f0f9ff841b2b7dabf7eb868338c`|`42428d16-8e43-4651-828d-168e43e65196`|`MUTO-INTL`|
|`wes-7d164f0f9ff841b2b7dabf7eb868338c`|`c10d85a6-6e52-44a4-8d85-a66e5234a40c`|`MUTO-INTL`|
|`wes-7d164f0f9ff841b2b7dabf7eb868338c`|`1b0fd7db-e1b9-44a3-8fd7-dbe1b9d4a3e6`|`MUTO-INTL`|
|`wes-92c4cd3cb7c54990b04555bcd5054b25`|`1a58b446-9f36-4943-98b4-469f368943d7`|`MUTO-INTL`|
|`wes-92c4cd3cb7c54990b04555bcd5054b25`|`d7346401-bd09-45ba-b464-01bd0925ba76`|`MUTO-INTL`|
|`wes-92c4cd3cb7c54990b04555bcd5054b25`|`2975248c-f7ba-4a6d-b524-8cf7baea6da9`|`MUTO-INTL`|
|`wes-92c4cd3cb7c54990b04555bcd5054b25`|`8f08e66a-ec07-488b-88e6-6aec07e88b4a`|`MUTO-INTL`|
|`wes-92c4cd3cb7c54990b04555bcd5054b25`|`2c69ddba-6c3a-4a12-a9dd-ba6c3a0a12e5`|`MUTO-INTL`|
|`wes-92c4cd3cb7c54990b04555bcd5054b25`|`c3d3bbbc-45fc-409a-93bb-bc45fcb09a44`|`MUTO-INTL`|
|`wes-292cc6cbb7554247aebd4d40e8c149e0`|`c6b11cd0-6bd4-414d-b11c-d06bd4014d88`|`MUTO-INTL`|
|`wes-292cc6cbb7554247aebd4d40e8c149e0`|`59ccf72f-0822-4c60-8cf7-2f08221c6086`|`MUTO-INTL`|
|`wes-292cc6cbb7554247aebd4d40e8c149e0`|`191154a4-ebe3-454b-9154-a4ebe3654b15`|`MUTO-INTL`|
|`wes-292cc6cbb7554247aebd4d40e8c149e0`|`73551258-25dd-4983-9512-5825dd898307`|`MUTO-INTL`|
|`wes-292cc6cbb7554247aebd4d40e8c149e0`|`7f4a78f7-a9dc-45c5-8a78-f7a9dc75c502`|`MUTO-INTL`|
|`wes-292cc6cbb7554247aebd4d40e8c149e0`|`ef04040a-a2e4-4a51-8404-0aa2e49a51c5`|`MUTO-INTL`|
|`wes-6797dff1ac3a4fb081713b5bb6dfb3ed`|`042a8a95-bc80-41a5-aa8a-95bc80e1a5a8`|`MUTO-INTL`|
|`wes-6797dff1ac3a4fb081713b5bb6dfb3ed`|`d2094dc8-7f2e-4b84-894d-c87f2efb844c`|`MUTO-INTL`|
|`wes-6797dff1ac3a4fb081713b5bb6dfb3ed`|`f8db7bb9-4e65-42ab-9b7b-b94e65f2ab1a`|`MUTO-INTL`|
|`wes-6797dff1ac3a4fb081713b5bb6dfb3ed`|`0865972e-e370-47e4-a597-2ee37097e420`|`MUTO-INTL`|
|`wes-6797dff1ac3a4fb081713b5bb6dfb3ed`|`9b000de6-4931-459d-800d-e64931059d33`|`MUTO-INTL`|
|`wes-6797dff1ac3a4fb081713b5bb6dfb3ed`|`21d3de4f-0d18-40f1-93de-4f0d1870f160`|`MUTO-INTL`|
|`wes-d73fe47da7444f3997cf770351b1dccf`|`b34169d7-ae59-460e-8169-d7ae59760e32`|`MUTO-INTL`|
|`wes-d73fe47da7444f3997cf770351b1dccf`|`5eb9029d-c918-46f1-b902-9dc91826f1c8`|`MUTO-INTL`|
|`wes-d73fe47da7444f3997cf770351b1dccf`|`140aaaff-7d45-4892-8aaa-ff7d45f89283`|`MUTO-INTL`|
|`wes-d73fe47da7444f3997cf770351b1dccf`|`f3e45a22-826e-40f1-a45a-22826ef0f119`|`MUTO-INTL`|
|`wes-d73fe47da7444f3997cf770351b1dccf`|`38bff8b5-ee74-46f5-bff8-b5ee7466f5a3`|`MUTO-INTL`|
|`wes-d73fe47da7444f3997cf770351b1dccf`|`97f9af80-701a-4392-b9af-80701a9392cc`|`MUTO-INTL`|
|`wes-16d50d9a3d9f49c3adbf5215e99b4666`|`dada6cf4-ef7d-4f94-9a6c-f4ef7dbf949e`|`MUTO-INTL`|
|`wes-16d50d9a3d9f49c3adbf5215e99b4666`|`b2860ffb-0eef-4f92-860f-fb0eef8f924f`|`MUTO-INTL`|
|`wes-16d50d9a3d9f49c3adbf5215e99b4666`|`80085ecc-53da-4fdb-885e-cc53da4fdb80`|`MUTO-INTL`|
|`wes-16d50d9a3d9f49c3adbf5215e99b4666`|`abbc7af4-6be1-43b3-bc7a-f46be193b349`|`MUTO-INTL`|
|`wes-16d50d9a3d9f49c3adbf5215e99b4666`|`b09b7107-ec3d-4c39-9b71-07ec3d5c393d`|`MUTO-INTL`|
|`wes-16d50d9a3d9f49c3adbf5215e99b4666`|`94a18826-3977-46a9-a188-26397786a959`|`MUTO-INTL`|
|`wes-63271bda2dee4194a1e3f5c0a3d3cf37`|`66cce45e-8a2c-48bb-8ce4-5e8a2cb8bb8b`|`POG-CA`|
|`wes-63271bda2dee4194a1e3f5c0a3d3cf37`|`5aae9b4e-ee04-4f48-ae9b-4eee04cf4808`|`POG-CA`|
|`wes-63271bda2dee4194a1e3f5c0a3d3cf37`|`1945d58e-be16-4aa4-85d5-8ebe163aa42a`|`POG-CA`|
|`wes-f63059947de9492689d582a805797317`|`29830a95-8882-48e5-830a-95888288e5c5`|`POG-CA`|

**Comment by edsu7** [comment]
Updated summary report with clinical flags.

Current Summary


|  | P1000-US | POG-CA | MUTO-INTL
|-- | -- | -- | --
|# Of sample combinations flagged by QC |   |   |  
| no new files | 54 |   | 310
| missing pair |   | 17 |  
| coverage issue |   | 1 | 60
| clinically incomplete |   | 294 | 59
| variants not called | 1 |   | 1
| contamination | 6 |   |  
|# Of sample combinations okay for release | 17 | 358 | 1128
|total | 78 | 670 | 1558

| | P1000-US | POG-CA | MUTO-INTL
|-- | -- | -- | --
|New Donors | 4 | 300 | 913
|Previous Donors | 13 |   | 102
|# Donors eligible for release | 17 | 300 | 1015
|# Analyses eligible for release | 112 | 2448 | 16246
|# Files eligible for release | 466 | 8064 | 42748


|  | P1000-US | POG-CA | MUTO-INTL
|-- | -- | -- | --
|# of donor by workflow |   |   |  
|DNA Seq | 4 | 300 | 913
|GATK Mutect | 4 | 300 | 912
|Sanger WGS | 14 | 58 | 911

|  | P1000-US | POG-CA | MUTO-INTL
|-- | -- | -- | --
|# of files by workflow |   |   |  
|DNA Seq | 168 | 4562 | 18168
|GATK Mutect | 32 | 2400 | 7296
|Sanger WGS | 266 | 1102 | 17284

[DR9_summary_reportV2.xls](https://github.com/icgc-argo/workflow-roadmap/files/15336650/DR9_summary_reportV2.xls)

**Comment by lindaxiang** [comment]
@edsu7 
For MUTO-INTL, there's one more run which has duplicated runs. It has generated sanger variant calling results in 2021, but got recently re-running the sanger workflows. So the recent new runs' results will need to be suppressed.

**studyId**|**donorId**|**sampleId**|**tumourNormalDesignation**|**experimental\_strategy**|**input\_analysisId**|**workflow\_name**|**new\_runId**|**new_run\_complete\_time**|**old\_runId**|**old_run_complete\_time**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
MUTO-INTL|DO250001|SA610008|Tumour|WGS|2c7146e0-ab88-466b-b146-e0ab88066bff|sanger-wgs-variant-calling|wes-5c898b17153a4fd290ea70ed99c50b94|2024-05-17 22:33|wes-2feb9e4f3e094e9a975bdb275a794b10|2021-07-25 8:05

**Comment by lindaxiang** [comment]
@edsu7 
P1000-US RNA-Seq alignment have the following duplicated runs. 

**studyId**|**donorId**|**sampleId**|**tumourNormalDesignation**|**experimental\_strategy**|**input\_analysisId**|**workflow\_name**|**latest\_complete\_time**|**runId**|**complete\_time**|**output\_analysis\_to\_suppress**|**output\_analysis\_state**|**reason**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
P1000-US|DO253949|SA617171|Tumour|RNA-Seq|04eca176-c474-44da-aca1-76c47464dae9|rna-seq-alignment|2024-05-09 6:16|wes-a02991687ea24492bd38d314e042d9ed|2024-05-06 4:54|['3c3a3c7e-78c6-4023-ba3c-7e78c6f02395', 'b02b1dde-33b4-4ebb-ab1d-de33b45ebb83', 'bc2f15a0-3437-4d2e-af15-a034375d2ecf', '270ebdc2-4e3e-4f35-8ebd-c24e3e7f358a', '8da64e4e-2379-42e3-a64e-4e237952e39b']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253917|SA617057|Tumour|RNA-Seq|0972b0a6-d4fa-4b2c-b2b0-a6d4fa3b2ca4|rna-seq-alignment|2024-05-08 12:47|wes-9f4bae552bb648fba3134c22b2ebf535|2024-05-03 23:09|['c4256f91-72eb-4406-a56f-9172eb7406fc', 'afd810a9-d0a8-4f5a-9810-a9d0a84f5a76', '84b52624-f1f8-4dec-b526-24f1f80decba', 'a1312d71-63ce-4564-b12d-7163ced56427', '1ba15c5e-facd-4372-a15c-5efacdd3720c']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253939|SA617123|Tumour|RNA-Seq|17279b30-f62e-4c65-a79b-30f62e2c65fd|rna-seq-alignment|2024-05-09 3:59|wes-45b6c1ef3b4b4f8abbd8e0e28604867f|2024-05-06 22:43|['e65cbf7d-2bb8-41a3-9cbf-7d2bb8b1a3a8', '8d8460d5-59b2-42d3-8460-d559b2e2d3ec', '76156451-4208-45b7-9564-51420855b791', '9d9a46ac-6a56-4c0f-9a46-ac6a566c0f58', '1fb5f90b-c39a-4984-b5f9-0bc39a59849c']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253901|SA617186|Tumour|RNA-Seq|79af8e5d-23fb-4c59-af8e-5d23fb5c592f|rna-seq-alignment|2024-05-07 11:35|wes-715c1b1fa7af4bc1982c10342af9c11e|2024-05-04 0:46|['fbd82921-b040-4fd1-9829-21b040cfd19e', '93c5bc09-b604-494b-85bc-09b604994b36', '9fbf4477-4ca8-4fda-bf44-774ca86fdaa9', '28ec610a-cf71-4de9-ac61-0acf71bde9d6', 'fbaa1940-7d8e-4eef-aa19-407d8e5eef46']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253909|SA617032|Tumour|RNA-Seq|65024161-d0da-4f74-8241-61d0da5f74c8|rna-seq-alignment|2024-05-08 0:40|wes-4a7e644217fe4090a6a21931a84931ca|2024-05-04 6:21|['c6665059-5d46-49bd-a650-595d4679bd5e', 'cd692b2d-815d-4957-a92b-2d815d5957b7', '7f2334e5-c951-4a9e-a334-e5c951ba9e97', '36827bbe-c973-4181-827b-bec973a181a9', 'c7e20158-6308-46e6-a201-586308b6e687']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253964|SA617194|Tumour|RNA-Seq|0f546188-38d5-4f71-9461-8838d57f7180|rna-seq-alignment|2024-05-10 10:11|wes-1eadf596de2444be9493a17ceb5cad1d|2024-05-06 22:27|['25fcde12-0d59-400e-bcde-120d59800e38', '9c502a9a-87a3-4b0b-902a-9a87a35b0bf9', 'aef0bcb9-ed34-4cfa-b0bc-b9ed346cfa95', '0cedc342-7738-484a-adc3-427738c84a93', 'fc25318d-9c3e-4ab5-a531-8d9c3e0ab585']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253950|SA617173|Tumour|RNA-Seq|25737a61-b6b9-4971-b37a-61b6b9697104|rna-seq-alignment|2024-05-09 3:11|wes-4e30ba46b3734308b2297d8f1a4e3081|2024-05-06 5:50|['d35308bc-a846-4ed5-9308-bca8469ed54e', '5db5f242-130b-4cbc-b5f2-42130b5cbcf8', '16fea05f-201c-4838-bea0-5f201c683863', 'daa5ae7a-29e3-40e5-a5ae-7a29e3e0e5bf', '7ea95cd8-7bbe-4f4a-a95c-d87bbeaf4a80']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253947|SA617182|Tumour|RNA-Seq|e50e9e90-72a9-4981-8e9e-9072a94981cb|rna-seq-alignment|2024-05-09 0:37|wes-a7f0452778a44fd6ad7530386b02e611|2024-05-06 3:24|['e32fefe3-08fa-4258-afef-e308fad25838', 'a5725bc5-9e6f-4570-b25b-c59e6f85701c', 'bb6c516b-2004-42f6-ac51-6b2004f2f6e4', '7166aa64-8ac9-4017-a6aa-648ac9001701', '8dbfc35c-af23-43e3-bfc3-5caf2333e3bb']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253941|SA617255|Tumour|RNA-Seq|5244fc3f-15a6-40af-84fc-3f15a6f0af24|rna-seq-alignment|2024-05-08 19:01|wes-b9db353fe5164d3c897fac6f21540d1b|2024-05-06 9:11|['9bc87ecf-67ab-4307-887e-cf67ab5307a4', '6a65033e-63bb-47f5-a503-3e63bb77f56f', '5541fe18-2bbe-4092-81fe-182bbef09262', '2cab51d3-d7e5-4b9e-ab51-d3d7e57b9e0b', '061c4ab4-e83c-49f0-9c4a-b4e83c69f0d1']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253934|SA617308|Tumour|RNA-Seq|4e3f6253-b8d7-42b6-bf62-53b8d742b607|rna-seq-alignment|2024-05-08 5:29|wes-573c2571da674f2abfc2565ca23c06b1|2024-05-06 4:31|['48b3194e-c55f-49de-b319-4ec55ff9de55', '27fbe1e1-7209-4f99-bbe1-e17209af994b', 'd57897b1-2658-452e-b897-b12658952e75', '9cf93a49-87a9-4ef0-b93a-4987a9cef00a', 'ee1fc592-30d5-4423-9fc5-9230d51423ed']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis
P1000-US|DO253937|SA617297|Tumour|RNA-Seq|43a216a8-2e52-4110-a216-a82e5211104e|rna-seq-alignment|2024-05-10 5:14|wes-1a52a11e3fcf4155bf584b93b021bd47|2024-05-06 19:42|['f2c491c6-525d-4bb6-8491-c6525d1bb6cc', '8e05a5ef-313f-46e4-85a5-ef313f86e44e', 'f6decccc-9a9d-4c37-9ecc-cc9a9d1c378b', '1eb4c2ca-8a34-4ddd-b4c2-ca8a345ddda3', '1b40501e-f1d8-43d2-8050-1ef1d883d2db']|['PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED', 'PUBLISHED']|duplicated\_run\_output\_analysis

**Comment by edsu7** [comment]
Following have been unpublished
|run_id|analysis_id|study_id|
|--|--|--|
|wes-5c898b17153a4fd290ea70ed99c50b94|33d69f24-1167-4d7f-969f-2411679d7ffc|MUTO-INTL|
|wes-5c898b17153a4fd290ea70ed99c50b94|31c20875-2c46-440f-8208-752c46c40f50|MUTO-INTL|
|wes-5c898b17153a4fd290ea70ed99c50b94|3f837349-3eed-486d-8373-493eed286d31|MUTO-INTL|
|wes-5c898b17153a4fd290ea70ed99c50b94|1540c52f-12a7-433b-80c5-2f12a7233b5c|MUTO-INTL|
|wes-5c898b17153a4fd290ea70ed99c50b94|a0e62970-a340-426f-a629-70a340c26f1d|MUTO-INTL|
|wes-5c898b17153a4fd290ea70ed99c50b94|14213261-4351-46cd-a132-61435106cd68|MUTO-INTL|

**Comment by edsu7** [comment]
Completed. Closing
