### ISSUE TITLE
Missing entity exceptions from POG & MUTO

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#436]

**Comment by lindaxiang** [comment]
Here are the POG and MUTO submitter donor lists for missing entity exceptions. 
[MUTO-INTL.EntityExceptionRequest.list_submitter_losttofup_695.20240507.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5jQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ab1670ee0142d7b92222adb054495576ef022c3/MUTO-INTL.EntityExceptionRequest.list_submitter_losttofup_695.20240507.txt)
[POG-CA.EntityExceptionRequest.list_submitter_losttofup_78.20240507.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXZjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--047ca0f26c09f391c6d552f5f46615b6d39ed849/POG-CA.EntityExceptionRequest.list_submitter_losttofup_78.20240507.txt)

The requests have been approved by CMD on May10th.
The exceptions are granted for given donors on May14th.

**Comment by lindaxiang** [comment]
This ticket is done and can be closed.

**Comment by edsu7** [comment]
Closing!
