### ISSUE TITLE
Document MONSTAR xml to vcf conversion 

### ISSUE THREAD

**Issue by guanqiaofeng** [icgc-argo/workflow-roadmap#454]

**Comment by guanqiaofeng** [comment]
Documentation available: 
https://docs.google.com/document/d/18HEaYr6bQ6IQkM4f6mnKVeqId4A9SegvBv8VAUIWS3U/edit

**Comment by guanqiaofeng** [comment]
@lindaxiang @edsu7 for review

**Comment by edsu7** [comment]
Closing, work will shift to public document
