### ISSUE TITLE
Workflow Run Failure - Duplicate Analysis Produced

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#48]
## Detailed Description
- the query size model tee is doing is 1000 max
- its been rolling over
- resulted in duplicate analysis 

## Exit criteria
- [x] Analyses have been suppressed

**Comment by lindaxiang** [comment]
@junjun-zhang @rosibaj , this is list of duplicated analysis generated by either duplicated runs or failed runs. 
the analysisId listed in column `run_output_analysis_to_suppress` are the analysis will be suppressed once we verified. 
Can you help to take a look and double check them? 
[suppress.txt](https://github.com/icgc-argo/workflow-roadmap/files/5348709/suppress.txt)

**Comment by rosibaj** [comment]
@lindaxiang i did some spot checking and it looks ok to me

**Comment by junjun-zhang** [comment]
look fine to me

**Comment by rosibaj** [comment]
@lindaxiang can we go ahead with suppression here then?

**Comment by lindaxiang** [comment]
@rosibaj . Yes. I will go to suppress them.

**Comment by lindaxiang** [comment]
@rosibaj I already suppressed all the analysis listed in the above `suppress.txt` file. Can you help to spot checking some of them? Thanks.

**Comment by rosibaj** [comment]
@lindaxiang I spot checked the first 50 and all look to be correctly suppress and removed from the index! i think this can be considered done :)
