### ISSUE TITLE
Workflow Run Failure: OxoG 2

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#5]
## Detailed Description

![image](https://user-images.githubusercontent.com/15824252/77326393-22cc8100-6cf0-11ea-96df-1faa078e1d07.png)

## List all runids affected
wes-574c88584b37417a86c06721903c4070
## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by junjun-zhang** [comment]
This is likely similar to #4 , ie, transient problem due to high load.
