### ISSUE TITLE
Workflow Run Failure - Mismatch CRAM and CRAI basename in input alignment files

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#51]
## Detailed Description

Mutect2 wf expects the input CRAM and CRAI files have the same basename, however
due to the [issue](https://github.com/icgc-argo/data-processing-utility-tools/issues/93) that date string could be different for all files in one SONG payload, there are alignment files happened to have different data string in the filename, which makes CRAM and CRAI have different basename, therefore cause the failure. 

## List all runids affected
wes-52a6c109af0543b881fbbca81a696400 (without BQSR)
wes-49e6698d1d2f4876be6c08f261b449cc (with BQSR)

## Approach to address this
Address the [issue](https://github.com/icgc-argo/data-processing-utility-tools/issues/93) and re-run the failed jobs. 

## Exit criteria
- [x] Issue has been resolved
- [ ] Run is resumed

**Comment by junjun-zhang** [comment]
Alignment workflow has been update to address this: https://github.com/icgc-argo/dna-seq-processing-wfs/releases/tag/1.5.1
