### ISSUE TITLE
Data QC - check and list all the data files with mismatch primary and index basenames

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#52]
Due to the issue that date string could be different for all files in one SONG payload, we need to thoroughly check and list all the data files(both alignment and variant calls) which have mismatch primary and index basenames.

**Comment by lindaxiang** [comment]
Here are 10 `Aligned Reads` which have the symptom of mismatch primary and index basenames because of different Date string. 
| analysisId   |      Aligned Reads filename  | Align Reads Index filename|
|----------|:-------------:|:-------------:|
|f8e9362f-6383-433b-a936-2f6383433b21 |PACA-CA.DO35210.SA601301.wgs.20200807.aln.cram |PACA-CA.DO35210.SA601301.wgs.20200808.aln.cram.crai|
|fcb8db74-7014-4a9f-b8db-7470148a9f88 |PACA-CA.DO221544.SA558741.wgs.20200504.aln.cram |PACA-CA.DO221544.SA558741.wgs.20200505.aln.cram.crai|
|1aa13f77-c052-440a-a13f-77c052440a43 |PACA-CA.DO51484.SA533701.wgs.20200512.aln.cram |PACA-CA.DO51484.SA533701.wgs.20200513.aln.cram.crai|
|42063881-e920-4404-8638-81e9200404a8 |PACA-CA.DO49424.SA520185.wgs.20200514.aln.cram |PACA-CA.DO49424.SA520185.wgs.20200515.aln.cram.crai|
|733ef15c-6088-4c23-bef1-5c60883c2300 |PACA-CA.DO49445.SA520168.wgs.20200420.aln.cram |PACA-CA.DO49445.SA520168.wgs.20200421.aln.cram.crai|
|b21c4815-a515-4922-9c48-15a5159922f5 |OCCAMS-GB.DO50434.SA528916.wgs.20201001.aln.cram |OCCAMS-GB.DO50434.SA528916.wgs.20201002.aln.cram.crai|
|b24d7930-0db3-463e-8d79-300db3063ecf |OCCAMS-GB.DO50384.SA528941.wgs.20200409.aln.cram |OCCAMS-GB.DO50384.SA528941.wgs.20200410.aln.cram.crai|
|f3522bc6-01b8-472d-922b-c601b8572d29 |OCCAMS-GB.DO50389.SA528947.wgs.20200411.aln.cram |OCCAMS-GB.DO50389.SA528947.wgs.20200412.aln.cram.crai|
|15a48953-123c-413a-a489-53123ce13af7 |OCCAMS-GB.DO50345.SA528823.wgs.20201004.aln.cram| OCCAMS-GB.DO50345.SA528823.wgs.20201005.aln.cram.crai|
|5276d937-39c8-470f-b6d9-3739c8770f34 |OCCAMS-GB.DO50448.SA528938.wgs.20200405.aln.cram |OCCAMS-GB.DO50448.SA528938.wgs.20200406.aln.cram.crai

**Comment by lindaxiang** [comment]
Currently there is no vcf files have the above symptom. Details see info in:
[variant_calls.filename.txt](https://github.com/icgc-argo/workflow-roadmap/files/5372834/variant_calls.filename.txt)

**Comment by lindaxiang** [comment]
@junjun-zhang @rosibaj here is the list of analysis(alignment+sanger) which are affected by the above 10 mismatch index alignment analysis, can you please help to double check of them. 
- Among these 10 sets of files, 2 (`15a48953-123c-413a-a489-53123ce13af7` and `b21c4815-a515-4922-9c48-15a5159922f5`)were duplicated runs recently which have been suppressed in https://github.com/icgc-argo/workflow-roadmap/issues/48
- one analysis(`f8e9362f-6383-433b-a936-2f6383433b21`) does not have sanger results
- The total number of analysis to be suppressed are: 8 * 2 alignment + 7 * 6 sanger = 58

**Comment by rosibaj** [comment]
@lindaxiang i spot-checked 5 and they all look to be correct selections to me

**Comment by lindaxiang** [comment]
thanks @rosibaj . I will proceed to suppress them once I get green light from Junjun.

**Comment by junjun-zhang** [comment]
@lindaxiang I got exactly the same list of 10 alignment SONG analysis objects, spot-checked a few variant calls, all good to me

**Comment by junjun-zhang** [comment]
qc_metrics SONG analysis associated with those 10 alignments need to be suppressed as well

**Comment by lindaxiang** [comment]
Thanks @junjun-zhang . The qc_metrics SONG analysis are also added to the list. 
[mismatch_index_affected_analysis.txt](https://github.com/icgc-argo/workflow-roadmap/files/5387333/mismatch_index_affected_analysis.txt)

**Comment by lindaxiang** [comment]
The analysisId listed in `mismatch_index_affected_analysis.txt` are all suppressed.
