### ISSUE TITLE
Data QC - suppress  analysis which are affected by the OCCAMS-GB donors/specimens re-name issue

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#53]
Details are described in https://github.com/icgc-argo/ega-file-transfer/issues/1
This ticket will address the following:

- [x] get a list of affected `donorId/sampleId/specimenId`
- [x] get a list of affected `analysisId` in Prod SONG
- [x] suppress the analysis in SONG.

**Comment by hknahal** [comment]
List of affected OCCAMS-GB `donorId/sampleId/specimenId/analysisId`: https://docs.google.com/spreadsheets/d/1WxBcuFcsXBir6aVidf-VVFrHzuAYhnUyPOeo-omxm20/edit?usp=sharing
Note: These are either completed or cancelled jobs in the `Align-Prod` worksheet.

**Comment by lindaxiang** [comment]
@hknahal , here is the list of alignment/qc_metrics SONG analysis in Prod which will be suppressed due to this issue. Please help to spot check the correctness. 
[OCCAMS-GB_rename_issue_analysisId.txt](https://github.com/icgc-argo/workflow-roadmap/files/5387447/OCCAMS-GB_rename_issue_analysisId.txt)

**Comment by hknahal** [comment]
@lindaxiang Looks good. It contains all the analyses to suppress.
