### ISSUE TITLE
Define K8s manifest 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#54]
- define what configs to deploy with the workflow graph nodes  (ingest) + (align) + (sanger) 
- nodes will be using the schema registry for validation of input parameters
- will translate into helm or a management-api later

## Expected Behavior 
Can do a test-run https://github.com/icgc-argo/workflow-roadmap/issues/39 in `QA` env

**Comment by andricDu** [comment]
Created: https://hub.docker.com/repository/docker/icgcargo/workflow-graph-node
Was missing and required for this to work.

**Comment by andricDu** [comment]
The investigative work is here: https://github.com/icgc-argo/argo-sandbox/tree/master/wfg
