### ISSUE TITLE
Workflow Run Failure - Score upload failure for ~600GB alignment file

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#58]
## Detailed Description
This job has generated ~600GB alignment CRAM file, which failed at Score uploading.
The alignment song analysis: https://song.rdpc.cancercollaboratory.org/studies/PACA-CA/analysis/aec0537a-95d8-4492-8053-7a95d8249270

## List all runids affected
https://wes.rdpc.cancercollaboratory.org/runs/wes-391c87976f804e888ab13ffd37c8eb2f

## Exit criteria
- [ ] Issue has been resolved
- [ ] Run is resumed

**Comment by rosibaj** [comment]
Resume job

**Comment by lepsalex** [comment]
complete: https://wes.rdpc.cancercollaboratory.org/runs/wes-83a3a904ed184faa95215f9fd4ae7265
