### ISSUE TITLE
Ingest Node from Song Publish from Submission Song

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#60]

**Comment by andricDu** [comment]
Kubernetes manifest to deploy ingest: https://github.com/icgc-argo/argo-sandbox/blob/master/wfg/ingest.yml

**Comment by andricDu** [comment]
Netpols updated on rabbit and kafka.

**Comment by andricDu** [comment]
Currently this is not production ready. 
The changes to make it prod ready are blocked until this is done: https://github.com/overture-stack/SONG/issues/674

**Comment by andricDu** [comment]
Further work:
- https://github.com/icgc-argo/workflow-graph-ingest-node/issues/11
- https://github.com/icgc-argo/workflow-graph-ingest-node/issues/12
