### ISSUE TITLE
Align Node - Filter, GQL, Activation Function, and Schema 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#61]

**Comment by andricDu** [comment]
Closing this as it is deployed, configured to talk to the correct queues and apis and it did successfully schedule a workflow. 

This issues arose in testing: 
- https://github.com/icgc-argo/workflow-graph-lib/issues/27
- https://github.com/icgc-argo/workflow-graph-ingest-node/issues/11
- https://github.com/icgc-argo/workflow-graph-node/issues/41
