### ISSUE TITLE
Workflow Run Failure - payload JSON has an invalid value

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#63]
## Detailed Description
The issue was caused by payload JSON which has a field populated with invalid value.
`"oxoQ_score":NaN,`

## List all runids affected
https://wes.rdpc.cancercollaboratory.org/runs/wes-cb274f93529f4624a03a831e09166f0d

## Approach to address this
Fix the tool: https://github.com/icgc-argo/gatk-tools/issues/70
Re-run the job. 

## Exit criteria
- [x] Issue has been resolved
- [x] Run is resumed

**Comment by lindaxiang** [comment]
Based on the QC metrics we collected, this input data is `single ended` dataset, we need to hold on this job for further investigation.

**Comment by lindaxiang** [comment]
@lepsalex can you re-run this job with latest version of aln-wf: 
https://github.com/icgc-argo/dna-seq-processing-wfs/releases/tag/1.5.6
The latest version has a fix to handle this type of error.

**Comment by lepsalex** [comment]
New run: https://wes.rdpc.cancercollaboratory.org/runs/wes-ceea5c8087eb45b4ac041310bd907a12

**Comment by lindaxiang** [comment]
The job has completed successfully. @lepsalex
