### ISSUE TITLE
RDPC-Gateway callable restart task in jenkins is no longer working

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/workflow-roadmap#66]
The original work was done here:
https://github.com/icgc-argo/workflow-roadmap/issues/24

This is no longer working. It seems to now be failing due to permission issues. @andricDu  has commented this out for now and has to manually do this restart.

**Comment by yalturmes** [comment]
Problem summary:
Jenkins agent pod label must be hyphen free. I haven't seen this particular restriction documented anywhere but encountered this behaviour in other pipelines with similar pod labels. The issue solved by removing hyphen from pod label in agent pod spec defined in Jenkinsfile.
PR with changes necessary to fix the issue have been created.
