### ISSUE TITLE
Investigate local write in workflows

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#7]
Bioinformatics tools write some files to the local disk; Reduce the network traffic of some files 

- [ ] Investigate ability to use the temp-dir/empty-dir to write local, temporary files
- [ ] Reduce the network traffic to speed up the wf

**Comment by junjun-zhang** [comment]
`tempdir` optional param was introduced for `bwaMemAligner` and `bamMergeSortMarkdup`  in https://github.com/icgc-argo/dna-seq-processing-tools/pull/98 and https://github.com/icgc-argo/dna-seq-processing-tools/pull/99.

To enable it just add `tempdir` param as follow:
```
"bwaMemAligner": {
    "tempdir": "/path/to/local/dir"
},
"bamMergeSortMarkdup": {
    "tempdir": "/path/to/local/dir"
}
```

**Comment by rosibaj** [comment]
The directory in the pod needs to be clarified

**Comment by lepsalex** [comment]
based on previous and summarized discussions I've created this wiki page, could be used as a starting point to create tickets: https://wiki.oicr.on.ca/display/icgcargotech/Local+Disk+Usage
