### ISSUE TITLE
🐛 Song data not accurately reflected in RDPC api

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#73]
## Describe the bug
Follow-up to #49

## Steps To Reproduce
1. query  https://api.rdpc-qa.cancercollaboratory.org/graphql to see the analysis that is in submission song
```
# Write your query or mutation here
query {
  analyses(filter:{studyId:"DASH-CA", analysisId: "e6a9189b-c9be-46e3-a918-9bc9bea6e326"} page:{from:0, size:200}) {
    inputForRuns{
      state
      inputAnalyses{
        analysisId
      }
    }
    analysisId
    analysisState
    repositories{
      url
      code
    }
    donors {
      donorId
      submitterDonorId
      specimens{
        submitterSpecimenId
        specimenId
      }
    }
  }
}

```
![image](https://user-images.githubusercontent.com/15824252/100135658-f4dba580-2e57-11eb-8a5a-145230d52276.png)

2. Check that same analysis in submission song 

```
curl --location --request GET 'https://submission-song.rdpc-qa.cancercollaboratory.org/studies/DASH-CA/analysis/e6a9189b-c9be-46e3-a918-9bc9bea6e326' \
--header 'Authorization: Bearer ----
```
![image](https://user-images.githubusercontent.com/15824252/100135715-091fa280-2e58-11eb-908f-4226d78a6022.png)

3. Observe that the information does not match.  Song says `PUBLISHED` and rdpc-api says `UNPUBLISHED` for the same analysis. It looks like the publish event is not making it somehow. 

For example:
Steps to reproduce the behaviour:
1. Check https://song.rdpc.cancercollaboratory.org/studies/LUCA-KR/analysis/f3c3ff0c-a45c-412f-83ff-0ca45ce12f2e
the analysis is `SUPPRESSED`
2. However if we go to https://api.rdpc.cancercollaboratory.org/graphql
use the query:
![Screen Shot 2020-11-25 at 10 12 15 AM](https://user-images.githubusercontent.com/7522294/100246082-bea92f00-2f06-11eb-98ea-9aa3427e1480.png)

3. the response is
![Screen Shot 2020-11-25 at 10 15 49 AM](https://user-images.githubusercontent.com/7522294/100246492-3414ff80-2f07-11eb-8635-044010f1c17c.png)
The analysisState is still "PUBLISHED" not "SUPPRESSED"
## Expected behaviour
The RDPC-API should reflect the latest state of the Song analysis. 

## Possible Implementation

Maestro only changes the repository field on update.  It should also change these other administrative fields:
- `State` 
- `updatedAt`
- `firstPublishedAt`
- `publishedAt`

- Update the mappings in maestro to include the new fields 
- Update the upsert in maestro to include these fields.

**Comment by andricDu** [comment]
@rosibaj ready for test in QA

**Comment by rosibaj** [comment]
Tested in QA
- unpublished this analysis:
curl --location --request GET 'https://submission-song.rdpc-qa.cancercollaboratory.org/studies/DASH-CA/analysis/03fa2ee8-79c2-4513-ba2e-e879c215131c' \
--header 'Authorization: Bearer ---'
- checked api, but it still says published 
![image](https://user-images.githubusercontent.com/15824252/101502398-e5bc2380-393e-11eb-974b-750c860fff6d.png)

**Comment by rosibaj** [comment]
i had to republish this test analysis as model-tee is running.
