### ISSUE TITLE
🐛 RDPC-API does not sync with SONG data for analysisState

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#74]
## Describe the bug
There are many song analysis have been `suppressed` for QC reasons. However the RDPC api does not sync with SONG data for the `analysisState`.

## Steps To Reproduce
For example:
Steps to reproduce the behaviour:
1. Check https://song.rdpc.cancercollaboratory.org/studies/LUCA-KR/analysis/f3c3ff0c-a45c-412f-83ff-0ca45ce12f2e
the analysis is `SUPPRESSED`
2. However if we go to https://api.rdpc.cancercollaboratory.org/graphql
use the query:
![Screen Shot 2020-11-25 at 10 12 15 AM](https://user-images.githubusercontent.com/7522294/100246082-bea92f00-2f06-11eb-98ea-9aa3427e1480.png)

3. the response is
![Screen Shot 2020-11-25 at 10 15 49 AM](https://user-images.githubusercontent.com/7522294/100246492-3414ff80-2f07-11eb-8635-044010f1c17c.png)
The analysisState is still "PUBLISHED" not "SUPPRESSED"

## Expected behaviour
The RDPC-API should be sync-ed with SONG data.

**Comment by rosibaj** [comment]
Closing as duplicate of https://github.com/icgc-argo/workflow-roadmap/issues/73
