### ISSUE TITLE
List of empty-dir changes 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#79]
Prep for empty-dir release i new year with a checklist to get to QA, then to Prod

**Comment by lepsalex** [comment]
Updated wiki to reflect latest hive knowledge: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=137548363

@akachru-github will take a pass as well

**Comment by akachru-github** [comment]
Added a few lines to represent the agreed to additional changes for adding a dedicated namespace for the webhooks and reordered things a little bit to bring up the non-disruptive changes first.
