### ISSUE TITLE
Suppress duplicated analysis

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#81]
The following sampleId was imported into intermediate song twice and cause duplicated `sequencing_experiment` analysis in `intermediate-song` and `sequencing_alignment` analysis in `rdpc-song`:
```
SA412480
SA412486
SA412510
SA412515
SA412581
SA412611
SA412738
SA412804
SA412874
SA412880
SA412965
SA413061
SA413162
```

We will need to find the related analysisId and suppressed them on respective song.

**Comment by hknahal** [comment]
Summary of duplicated analysis IDs: https://docs.google.com/spreadsheets/d/1G_l7Hqw-mHLO21x3ARtJz9KSZ_QK-ZuR1hrRJ1k_Tvs/edit?usp=sharing

Green rows: We will keep these analysis IDs since these are correct.
Pink rows: These are duplicated analysis IDs and will be suppressed.
Purple rows: These are not actually duplicated analysis IDs. The project uses the same submitterSampleId for both WGS and WXS, so these analysis IDs are correct and should not be suppressed.

Next Steps: I will go ahead and suppress the duplicated analyses in intermediate-song (pink rows in table)

**Comment by lindaxiang** [comment]
According to the information above, the responding **analysisId** (the second column) need to be suppressed in `rdpc-prod-song`:

sequencing_experiment_analysisId | **analysisId** | studyId | analysisType
-- | -- | -- | --
128ef01e-a4a2-4e91-8ef0-1ea4a2ce9176 | 1bf92ef8-1294-4078-b92e-f81294807827 | PACA-CA | qc_metrics
128ef01e-a4a2-4e91-8ef0-1ea4a2ce9176 | 8652e3e5-f81a-42cb-92e3-e5f81a72cb83 | PACA-CA | sequencing_alignment
1e5de74a-da7b-4056-9de7-4ada7b505677 | 65e76b5a-582f-4b9b-a76b-5a582ffb9b80 | PACA-CA | qc_metrics
1e5de74a-da7b-4056-9de7-4ada7b505677 | fca5ec44-fc0b-4f13-a5ec-44fc0b7f1395 | PACA-CA | sequencing_alignment
3b2c74b1-8f17-49ef-ac74-b18f1749ef5e | 04dbab3d-f9e2-44d9-9bab-3df9e2f4d95f | PACA-CA | qc_metrics
3b2c74b1-8f17-49ef-ac74-b18f1749ef5e | 6fa56592-5d9e-4120-a565-925d9e31200a | PACA-CA | sequencing_alignment
83ac1fb3-cd0a-4413-ac1f-b3cd0ab413ff | 39decec7-ebf0-4088-9ece-c7ebf08088f6 | PACA-CA | sequencing_alignment
83ac1fb3-cd0a-4413-ac1f-b3cd0ab413ff | eb56247a-21eb-43a5-9624-7a21ebe3a570 | PACA-CA | qc_metrics
94684d53-7ec7-4d3e-a84d-537ec7cd3ea9 | 5a4d6dad-4c49-441e-8d6d-ad4c49141eb3 | PACA-CA | sequencing_alignment
94684d53-7ec7-4d3e-a84d-537ec7cd3ea9 | 6e5b2ad7-8165-4997-9b2a-d781658997a1 | PACA-CA | qc_metrics
9a2cf789-0119-4cee-acf7-890119dceea0 | 0d782b65-aa5e-4bb1-b82b-65aa5ebbb1b3 | PACA-CA | sequencing_alignment
9a2cf789-0119-4cee-acf7-890119dceea0 | a070f804-742a-4139-b0f8-04742ad13921 | PACA-CA | qc_metrics
a8fac20e-7c27-477f-bac2-0e7c27d77fc7 | 23a5206a-86be-4ca1-a520-6a86be4ca111 | PACA-CA | qc_metrics
a8fac20e-7c27-477f-bac2-0e7c27d77fc7 | 409ea71e-9efd-4b04-9ea7-1e9efd9b043a | PACA-CA | sequencing_alignment
afb36c2e-757c-4537-b36c-2e757cb53790 | d7f90a88-2174-433b-b90a-882174e33b54 | PACA-CA | qc_metrics
afb36c2e-757c-4537-b36c-2e757cb53790 | f5aea5d8-2350-446c-aea5-d82350946ca9 | PACA-CA | sequencing_alignment
b3397388-851f-4f81-b973-88851f3f8146 | 10a7a327-5eff-4978-a7a3-275eff1978bc | PACA-CA | qc_metrics
b3397388-851f-4f81-b973-88851f3f8146 | 1289e87c-dd2c-4d13-89e8-7cdd2cdd136d | PACA-CA | sequencing_alignment
ba9758a3-8750-4807-9758-a387500807a6 | 1da0df0a-b5db-4a5a-a0df-0ab5db0a5a8c | PACA-CA | sequencing_alignment
ba9758a3-8750-4807-9758-a387500807a6 | ff0c931a-caf8-467b-8c93-1acaf8467bc4 | PACA-CA | qc_metrics
c4a6605d-bc5a-438c-a660-5dbc5a238cb0 | 32e8a8c4-3cd0-4e53-a8a8-c43cd0ae539d | PACA-CA | qc_metrics
c4a6605d-bc5a-438c-a660-5dbc5a238cb0 | cb58c7b9-fd05-4a49-98c7-b9fd051a497f | PACA-CA | sequencing_alignment
f2a2454a-569b-4b13-a245-4a569b6b1379 | a5db475f-f5e2-4c8d-9b47-5ff5e22c8d7f | PACA-CA | sequencing_alignment
f2a2454a-569b-4b13-a245-4a569b6b1379 | e89271fc-5e40-4722-9271-fc5e40f72218 | PACA-CA | qc_metrics
f51ccde9-06e4-4d30-9ccd-e906e4bd30c8 | 44f00053-9841-4d88-b000-5398418d881b | PACA-CA | qc_metrics
f51ccde9-06e4-4d30-9ccd-e906e4bd30c8 | 9e3fd222-e8d4-453b-bfd2-22e8d4253bea | PACA-CA | sequencing_alignment

**Comment by lindaxiang** [comment]
@hknahal I am done with the suppression of alignment-wf outputs analysisId in `rdpc-prod-song`

**Comment by hknahal** [comment]
@lindaxiang I suppressed the following analysis IDs in `intermediate-song`:


analysisId | sampleId | submitterSampleId
-- | -- | --
a8fac20e-7c27-477f-bac2-0e7c27d77fc7 | SA412480 | PCSI_0111_Ly_R
128ef01e-a4a2-4e91-8ef0-1ea4a2ce9176 | SA412486 | PCSI_0103_Ly_R
9a2cf789-0119-4cee-acf7-890119dceea0 | SA412510 | PCSI_0101_Ly_R
b3397388-851f-4f81-b973-88851f3f8146 | SA412515 | PCSI_0102_Pa_P
94684d53-7ec7-4d3e-a84d-537ec7cd3ea9 | SA412581 | PCSI_0179_Ly_R
f51ccde9-06e4-4d30-9ccd-e906e4bd30c8 | SA412611 | PCSI_0044_Ly_R
f2a2454a-569b-4b13-a245-4a569b6b1379 | SA412738 | PCSI_0078_Pa_X
3b2c74b1-8f17-49ef-ac74-b18f1749ef5e | SA412804 | PCSI_0082_Ly_R
afb36c2e-757c-4537-b36c-2e757cb53790 | SA412874 | PCSI_0084_Pa_X
1e5de74a-da7b-4056-9de7-4ada7b505677 | SA412880 | PCSI_0047_Ly_R
c4a6605d-bc5a-438c-a660-5dbc5a238cb0 | SA412965 | MPCC_0032_Pa_C
ba9758a3-8750-4807-9758-a387500807a6 | SA413061 | PCSI_0075_Ly_R
83ac1fb3-cd0a-4413-ac1f-b3cd0ab413ff | SA413162 | PCSI_0208_Pa_P

**Comment by lindaxiang** [comment]
Thanks @hknahal . All done and close this ticket now.
