### ISSUE TITLE
Double the WF Execution - Collab + OICR IT Hardware

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#84]
We will be receiving new hardware and access to processing power for the Canadian RDPC.

There will be 2 execution centers for WF processing, but a single Song/Score. 

This can be used a model for Cloud Bursting for compute in future. 

## Expected Outcome 
Wiki page detailing the design of how we can connect a second execution center, and any potential changes/middleware services needed to support this. 

Include a risk assessment for any issues that could arise between different compute environment.

**Comment by andricDu** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Multi-Site+RDPC
