### ISSUE TITLE
Git as the source of Config truth, not helm. 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#85]
The RDPC Infra charts do not match what is actually deployed; they can get out of sync.  - RDPC Infra values do not match the actual values deployed.   

## Possible Implementation 
- Update the git with automation, and deploy from git.  Jenkins apply what is in git only!
- Right now, it is only applied if someone initiates a deploy or something, 
- When Infra is updated in git, Jenkins should initiate it and apply it. 

## Expected Outcome 
- Right now the source of truth is helm, but services think it is git. 
- Design for new implementation of the config source, launched automatically from Jenkins jobs. 
- Changes to service configurations or infrastructure conjurations should be done _exclusively_ through Jenkins.  no `helm` or `kube-ctl` commands should be run. 
- List of tickets for implementation

**Comment by akachru-github** [comment]
cc. @yalturmes , @henro001

**Comment by andricDu** [comment]
Currently investigating terraform. 

We will still publish and use helm charts, and we will still maintain helm values, but gluing them together will be terraform's job, as terraform is both declarative in how you describe what you want your final state to be and it actually assumes responsibility in delivering that state unlike helm.

**Comment by andricDu** [comment]
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=154537125

**Comment by andricDu** [comment]
If these connected tickets are completed successfully, implementing this in RDPC QA and Prod will be simple as the terraform file will already be written, just need to create the tfvars file. 

Implementing this for the ARGO Platform staging/prod environment can be a separate epic/ticket set depending on the output of the efforts here.
