### ISSUE TITLE
Kafka Backup and Restore test

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#88]
- about a day of work. Full disaster simulation.
- wipe kafka/ES in dev.  full reset.  nothing should be there at all. 
- restart the system 
- get the back up running.  run 10 jobs. save the kafka/es for this. 
- wipe kafka/es again.  Restore from the backup into kafka and replay relay from the very beginning. 
- Should stream everything to ES.  perform the same query and make sure the output is exactly the same as before.

**Comment by lepsalex** [comment]
Disaster test completed successfully!

Results here: https://docs.google.com/spreadsheets/d/1ObKFTCvZ70qgpZUca5xW08CKSh1kGS7-y2-5G7y0M3E/edit?usp=sharing
