### ISSUE TITLE
Empty-dir verifications for production deploy 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-roadmap#89]
- [x]  verify the cleanup of the existing namespace {rdpc-collab].  This has a bunch of complete pods, config maps, and secrets that are artifacts of runs. these can be removed. 
- [x] verify when the run is done, verify empty-dir is `deleted`.  
- [x] if there are multiple pods on the same node, mounting empty-dir.  Are they using a shared `empty-dir` or does each pod get its own `empty-dir` that is deleted.

**Comment by akachru-github** [comment]
verify the cleanup of the existing namespace {rdpc-collab]. This has a bunch of complete pods, config maps, and secrets that are artifacts of runs. these can be removed.
- @yalturmes removes complete pods before moving persistent vols to new namespace
- Not aware of any other artifacts
- Can we add config maps and secrets to this cleanup as long as there is an alternative setup. Let's verify in dev and QA before going to prod.

verify when the run is done, verify empty-dir is deleted.
- @yalturmes -  emptydir is a runtime only storage location, so when the pod is gone, the emptydir should be gone as well. 

if there are multiple pods on the same node, mounting empty-dir. Are they using a shared empty-dir or does each pod get its own empty-dir that is deleted.
- @henro001 - emptydir's are unique per pod.
