### ISSUE TITLE
Workflow Run Failure - one Sanger-wxs job failed

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#90]
## Detailed Description

Error executing process > 'SangerWxs:upSupp:scoreUp (c3905700-9eb0-4b9f-9057-009eb03b9fb3)' Caused by: Process `SangerWxs:upSupp:scoreUp (c3905700-9eb0-4b9f-9057-009eb03b9fb3)` terminated with an error exit status (1) Command executed: export METADATA_URL=https://song.rdpc.cancercollaboratory.org export STORAGE_URL=https://score.rdpc.cancercollaboratory.org export TRANSPORT_PARALLEL=4 export TRANSPORT_MEMORY=2 export ACCESSTOKEN=`cat /tmp/rdpc_secret/secret` score-client upload --manifest manifest.txt Command exit status: 1 Command output: (empty) Command error: Starting... Running... Validating repository connection... ERROR: Command error: java.io.IOException: Access refused by repository. Ensure client is running as part of repository cloud. Please check the log for detailed error messages Work dir: /nfs-3-c1/work/7b/b817427b7ad4dd71e095fc05f7def6 Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

## List all runids affected
https://wes.rdpc.cancercollaboratory.org/runs/wes-414fb0eaddc34d4f9eea908c5a226ac2

## Approach to address this
resume the job

## Exit criteria
- [ ] Issue has been resolved
- [x] Run is resumed

**Comment by lindaxiang** [comment]
@lepsalex , can you resume this one? it looks like it was failed at uploading step. let's see whether resume can solve the problem. Thanks.

**Comment by lepsalex** [comment]
Running: https://wes.rdpc.cancercollaboratory.org/runs/wes-7a637b8557c44e7b8e6f6e812c7c8f73

**Comment by lindaxiang** [comment]
The job has completed successfully. Thanks @lepsalex !
